### PR TITLE
Revert "Adding code to prefilter the Lb to Lc pi candidates (Anastasis)"

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
This reverts commit 881503420f7f3cdefc730584880818389b345306.

Incomplete commit, needs revision --> revert

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Hello @lvermunt @ginnocen 
For now I just reverted the commit. Let me know what you think

**Comment by benedikt-voelkel** [comment]
@qgp could you give a +1?

**Comment by cterrevo** [comment]
+1

**Comment by benedikt-voelkel** [comment]
Thanks @cterrevo :)

**Pull request merged**
