### PR TITLE
PWGGA/GammaConv: MC embedding changes - see ALIROOT-7145

### PR DESCRIPTION
**Pull request by dmuhlhei**

### CODE REVIEW

**Comment by dmuhlhei** [comment]
@dberzano I am confused that this pull request does not change its status. Is there possibly any reason for that?

**Comment by dmuhlhei** [comment]
okay, apparently it just did change - sorry for the spam

**Comment by dberzano** [comment]
+test - for the record, if a PR has more than 50 files changed its approval falls back on the admins.

**Comment by dmuhlhei** [comment]
That we do know. For hours, the pull-request just did not get to the status where 'review' was displayed, it seemed to me it was hanging in its state. Right after my posting the status changed and the usual message with 'approval required' popped up.

**Comment by dmuhlhei** [comment]
Is there a reason that this pull-request has not been approved so far?

**Comment by dberzano** [comment]
+1 (I see it's only you and @FriederikeBock as admins in this directory, so it's fine.)

**Comment by dmuhlhei** [comment]
thanks a lot - sorry for the large one, but all changes are closely related - thus should be in one pull-request.

**Pull request merged**
