### PR TITLE
Updated OADB for LHC16s

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
Hello Everyone,

I am a bit confused about what happened in this thread. First of all, the system asked two times for approval of the same pull request, to which I promptly "+1"-ed... but the system then went on to not acknowledge the approval and ask again another two times for approval, which then meant this request missed today's tag as I had to again approve the same thing... was it me who did something wrong or misunderstood how things are supposed to work?...

Thanks a lot!
Cheers,
David

**Comment by dberzano** [comment]
Hi @ddobrigk, it seems you have hit a glitch in the GitHub APIs, preventing our system from acknowledging the PR at first. We'll investigate on Monday.

**Pull request merged**
