### PR TITLE
Fix crash when efficiency input is not initialized/found

### PR DESCRIPTION
**Pull request by dstocco**

### CODE REVIEW

**Comment by dstocco** [comment]
See [ALIROOT-7321.](https://alice.its.cern.ch/jira/browse/ALIROOT-7321)

**Comment by dberzano** [comment]
For the record this is the real fix to #1367. @dstocco bear in mind that after my revert in the aforementioned commit, you still need to bring `PWGPP/MUON/lite/trigEffQA.C` to the latest version, probably.

**Comment by dstocco** [comment]
For the record, I restored the  modification on `PWGPP/MUON/lite/trigEffQA.C` (see [#1377](https://github.com/alisw/AliPhysics/pull/1377) )
Cheers,
Diego

**Comment by dberzano** [comment]
OK thanks!

**Pull request merged**
