### PR TITLE
Fix strategy to identify univocally an event in a run for both MC and Data

### PR DESCRIPTION
**Pull request by ginnocen**
@qgp

### CODE REVIEW

**Comment by ginnocen** [comment]
@shahor02 Ciao Ruben, we added the event identification as you recommended. In general it works just fine. But I see some very rare case (~2 MC events in a pretty big test dataset) where I have duplicated indices. I will do some extra checks and let you know. Thanks for your help.

**Comment by qgp** [comment]
+test

**Comment by qgp** [comment]
+test

**Comment by qgp** [comment]
+1

**Pull request merged**
