### PR TITLE
PWGGA/GammaConv: Fix PHOS Pi0 Sigma

### PR DESCRIPTION
**Pull request by jluehder**

### CODE REVIEW

**Comment by jokonig** [comment]
+1

**Comment by fjonasALICE** [comment]
Hi @ktf ! I read your mail about problems with yesterdays tag. This PR was tested succesfully and not merged. Will it be in todays tag or do we need to trigger some re-testing for it to be in?

Thanks for your help!

**Comment by fjonasALICE** [comment]
Either @ktf solved it or it solved itself just after I wrote. Thanks a lot! All good now

**Comment by ktf** [comment]
It solved itself.

**Pull request merged**
