### PR TITLE
Extent the eta range

### PR DESCRIPTION
**Pull request by SiyuTang**
Hi all,

Please approve this commits. Thanks! 

Siyu

### CODE REVIEW

**Comment by vvislavi** [comment]
+1

**Comment by SiyuTang** [comment]
Hi all,

It seems that the errors are related to the problems of PR check system. Now it is fixed. Can someone help to approve the test again? Thanks! 

Siyu

**Comment by rihanphys** [comment]
+test

**Comment by rihanphys** [comment]
@SiyuTang it would be better if you close this one and create new PR.

**Comment by SiyuTang** [comment]
> @SiyuTang it would be better if you close this one and create new PR.

Hi Rihan, thank you! I opened a new PR in https://github.com/alisw/AliPhysics/pull/20170  
Could you please approve the test of it again? Thanks!

**Pull request closed without merging**
