### PR TITLE
Adding an option to bypass the L1 gamma trigger simulation

### PR DESCRIPTION
**Pull request by e-masson**

### CODE REVIEW

**Comment by efranzis** [comment]
+test

**Comment by dlodato** [comment]
+1

**Comment by e-masson** [comment]
Thanks @efranzis and @dlodato for your rapidity!
Best, Erwann

**Comment by e-masson** [comment]
Hi again @efranzis and @dlodato,
The PR seems to be stuck in "test required" state despite the +test comment... Usually this is not so long, is there something that can be done?
Thanks and best, Erwann

**Comment by dlodato** [comment]
Hi @e-masson, 
well it could be that the machines are busy with the propagation of the new tag, or something like it.
Since this commit will be available at best from tomorrow tag, let's wait until tomorrow morning and in case we decide what to do (new PR, or new comment or contact the expert).
Does this work for you?
Cheers, 
Davide

**Comment by e-masson** [comment]
Hi @dlodato,
This is fine for me, thank you.
Best, Erwann

**Comment by dlodato** [comment]
+1

**Comment by e-masson** [comment]
Well, I was in a hurry apparently :)...
Thanks and sorry for the inconvenience, best,
Erwann

**Pull request merged**
