### PR TITLE
missing comma added

### PR DESCRIPTION
**Pull request by adubla**

### CODE REVIEW

**Comment by fprino** [comment]
+test

**Comment by adubla** [comment]
I have checked the details and the error does not look to me coming from the modification done in the pull request.
Is this possible?

Thanks
Andrea

**Comment by dberzano** [comment]
You are right. It's just a glitch due to the manual merging of #5910. It will clear out automatically, don't worry.

**Comment by fprino** [comment]
Can I give the plus one?
Or should I wait that the errors clears out?

**Comment by dberzano** [comment]
@fprino you can't, it will be ignored until the error is fixed. You'll be notified appropriately.

**Comment by fprino** [comment]
OK. Thanks, I'll wait.

**Comment by dberzano** [comment]
+1 @fprino I am taking care of it

**Pull request merged**
