### PR TITLE
Hfe multiplicity task with tracklet correction implemented

### PR DESCRIPTION
**Pull request by pdhankhe**

### CODE REVIEW

**Comment by sashingo** [comment]
+1

**Comment by sashingo** [comment]
+test

**Comment by pdhankhe** [comment]
The pull request still needs the review approval. Can you please check?

**Comment by sashingo** [comment]
+test

**Comment by sashingo** [comment]
+1

**Comment by sawenzel** [comment]
+test

**Comment by sawenzel** [comment]
Testing the PR.  Quickly looking at the commits, I had difficulties to understand the commits structure. Please avoid using the same commit message twice or commit message like "File upload via interface" who are not informing about **what** is being achieved.

Suggestion:

In general, it would be perfect to just provide a single and clean commit and this can be done incrementally via the `git commit --amend; git push --force` mechanism. Meaning: you can modify/fixup commits until they compile fine or are accepted.

**Comment by sawenzel** [comment]
Does this compile for you using alibuild?

**Comment by pdhankhe** [comment]
Sorry for being unclear. I will keep this in mind next time. The task is running fine locally with alibuild as well as on grid. But When I am trying to commit. It is showing library dependency issue.

**Pull request closed without merging**
