### PR TITLE
Added Tasks for ZDC gain calibration

### PR DESCRIPTION
**Pull request by rihanphys**
Added Analysis Task 'AliAnalysisTaskZDCGainEq' and corresponding 'AddTaskZDCGainEq.C' for ZDC gain calibration.

### CODE REVIEW

**Comment by jmargutt** [comment]
+1

**Comment by rbertens** [comment]
Hi @rihanphys ,

The proposed code could probably use a bit of cleanup before it's merged. E.g.
- are all the headers necessary? I don't think you use NTuples or TApplicatoins for example. for pointer members in the header of the class itself, a forward declaration suffices to reduce the work of preprocessing
- could you use consistent indentation?  this will make reading / validating easier
- maybe change the author contacts in the header ? 
- you start with 'version 2' of the class layout (in the ClassDef) but this is a new class

it would be good if you could address these issues (even though they won't affect compilation).
thanks,
redmer

**Comment by rihanphys** [comment]
Hi @rbertens I made the changes you suggested. Can you please test and merge. Thanks.

**Comment by dberzano** [comment]
+test

**Comment by rbertens** [comment]
+1
Thanks for the swift action @rihanphys, I approved for merging.

**Pull request merged**
