### PR TITLE
Implement O2 vertexer in the task to compare run3 and run2

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by fprino** [comment]
Dear @MichaelLettrich, @ktf,

I am a bit puzzled by the failure of build/AliPhysics/release: if I click on "Details" I get a page which says "No errors found, so I do not know what to check.

Best regards, Francesco

**Comment by ktf** [comment]
You mean the root6 one? @TimoWilken could you check?

**Comment by ktf** [comment]
@fprino in the meanwhile could you check what goes wrong in the standard build?

https://ali-ci.cern.ch/alice-build-logs/alisw/AliPhysics/16160/a1a9bac3bff10df3cbe035446d4968843a5c6ab7/build_AliPhysics_release/pretty.html

**Comment by fprino** [comment]
Hi @ktf 
somehow I was getting the wrong page when checking build/AliPhysics/release.
I had a look now at the correct link, and this is the error:

In file included from /mnt/mesos/sandbox/sandbox/aliphysics-release/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-7/include/c++/7.3.0/array:35:0,
--
                 from /mnt/mesos/sandbox/sandbox/aliphysics-release/sw/SOURCES/AliPhysics/build_AliPhysics_release/0/PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h:13,
                 from /tmp/rootcint_cBZ6t5.h:58,
                 from /tmp/yXS66D_cint.cxx:1:
/mnt/mesos/sandbox/sandbox/aliphysics-release/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice2-7/include/c++/7.3.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

which seems related to the compiler options. Locally I can compile successfully AliPhysics.
Do I need to add something in the CMakeLists.txt file?

Thanks!

Cheers, Francesco

**Comment by TimoWilken** [comment]
> You mean the root6 one? @TimoWilken could you check?

@ktf: the error is:
```
ERROR: Error on 'git ls-remote --heads https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git': fatal: Authentication failed for 'https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git/'
```

But I still don't know how that happens! (The git credentials for the CERN GitLab are written out correctly.) The first time I run it, the command doesn't work:
```
# ls -A
[...] .gitconfig .git-creds
# HOME=$PWD git ls-remote --heads https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.cern.ch/ALICEPrivateExternals/DPMJET.git/'
```

But trying again a minute later, it does work! Is GitLab configured to rate-limit requests?

**Comment by ktf** [comment]
Ok, let's follow this up in service now.

**Comment by fprino** [comment]
Hi,

I think I found, thanks to Maximiliano the issue with ROOT5 build: the o2 vertexer uses c++11 headers and does not work with ROOT5. I just committed a modification of CMakeLists and linkdef files to enable compilation and linking of the class only for root6.

Cheers, Francesco

**Pull request merged**
