### PR TITLE
Added FlowModes task

### PR DESCRIPTION
**Pull request by naghmehmohammadi**
Non-linear flow modes for identified particles

### CODE REVIEW

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
Hi @naghmehmohammadi , 
you've added the task and your addtask macro, but didn't make any changes to the PWG/FLOW/Tasks.CMakeLists.txt and PWG/FLOW/Tasks/PWGflowTasksLinkDef.h to have the code included for compilation. Did you perhaps forget this? Let me know how you want to proceed.
Thanks,
redmer

**Comment by naghmehmohammadi** [comment]
Hi Redmer,

Yeah I did forget but I was a little occupied. Thanks for letting me know anyways. I’ll try to recommit them with making changes to the Cmake file

Cheers,
Naghmeh

**Comment by rbertens** [comment]
Hi @naghmehmohammadi , You can just make a new PR with only the changes to the CMake/PWGLinkdef file. This new PR will then be added to the PR that's still open ,and I can approve it all in one go.

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
+1

**Pull request merged**
