### PR TITLE
PWGLF: install required macro

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@dcolell I think this is what you wanted to do. You can find additional information on the `install` command from CMake at [this location](https://cmake.org/cmake/help/v3.0/command/install.html). Can you triple-check if this works for you before approving?

**Comment by dcolell** [comment]
@dberzano It should be fine. Approved. Thank you.

**Comment by bdoenigu** [comment]
+test

**Comment by bdoenigu** [comment]
+1

**Pull request merged**
