### PR TITLE
Finer binning for dE/dx vs. p histos

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by fprino** [comment]
+1

**Comment by fprino** [comment]
Hi @ktf,
this PR seems stuck in running the tests.
Can you please check?
Best regards, Francesco

**Comment by ktf** [comment]
Tests seems to be running fine. Investigating.

**Comment by fprino** [comment]
Thank you @ktf for solving the issue.
Cheers, Francesco

**Comment by ktf** [comment]
What seems to have happened is that the troubles Github went through yesterday left your PR in some funny state which was not reporting as "testable".

**Pull request merged**
