### PR TITLE
Adding new code for R2 and P2

### PR DESCRIPTION
**Pull request by sbaidyan**

### CODE REVIEW

**Comment by aohlson** [comment]
Hi Baidyanath, 
Since the CMakeLists and LinkDef files depend on each other, they will not compile if they are changed in separate pull requests.  Please add the edited CMakeLists and LinkDef files to _this_ pull request (#15831), and close your other two pull requests (#15835 and #15836).  
Thanks, 
Alice

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
Hi Baidyanath, 
It looks like you updated the pull request, very good.  However, the cmake file and linkdef files need to be the ones in the directory PWGCF/Correlations/DPhi/.  Somehow in this pull request modifies those files in the base directory.  Sorry for the confusion.  
Cheers, 
Alice

**Comment by sbaidyan** [comment]
> Hi Baidyanath,
> It looks like you updated the pull request, very good. However, the cmake file and linkdef files need to be the ones in the directory PWGCF/Correlations/DPhi/. Somehow in this pull request modifies those files in the base directory. Sorry for the confusion.
> Cheers,
> Alice

Hi Alice,

Thank you for the information. Can you please suggest what things to be done from my side?

Regards,
Baidyanath

**Comment by aohlson** [comment]
Hi Baidyanath, 
As you can see from the "Files changed" tab, above, your committed CMake and LinkDef files appear as new files in the base directory (the diff indicates large amounts of new text in green and removed text in red, but it should only show one or two lines changed).  You could modify this pull request as you did before to fix this, but it may also be simpler and more straightforward to just close this pull request and open a new one which includes your edits to the following files: 
PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2.cxx 
PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2.h
PWGCF/Correlations/macros/dptdptcorrelations/AddTaskR2P2.C
PWGCF/Correlations/DPhi/CMakeLists.txt
PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h

Hope this helps, 
Alice

**Comment by sbaidyan** [comment]
> Hi Baidyanath,
> As you can see from the "Files changed" tab, above, your committed CMake and LinkDef files appear as new files in the base directory (the diff indicates large amounts of new text in green and removed text in red, but it should only show one or two lines changed). You could modify this pull request as you did before to fix this, but it may also be simpler and more straightforward to just close this pull request and open a new one which includes your edits to the following files:
> PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2.cxx
> PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2.h
> PWGCF/Correlations/macros/dptdptcorrelations/AddTaskR2P2.C
> PWGCF/Correlations/DPhi/CMakeLists.txt
> PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
> 
> Hope this helps,
> Alice

Hi Alice,

  Thanks for your quick reply and nice suggestion. I will follow this.

Regards,
Baidyanath

**Pull request closed without merging**
