### PR TITLE
New version of AliAnalysisTaskMinijet using AliDirList instead of TList.

### PR DESCRIPTION
**Pull request by mgheata**
This branch clones AliAnalysisTaskMinijet, using AliDirList instead of TList for the list of outputs. This is temporary in order to compare the use of memory in merging for the two approaches.

### CODE REVIEW

**Comment by vpacik** [comment]
+1

**Comment by naghmehmohammadi** [comment]
+1

**Comment by akubera** [comment]
I had issues with memory usage during merging. I ended up with writing a new class: [AliFemtoResultStorage](https://github.com/alisw/AliPhysics/blob/master/PWGCF/FEMTOSCOPY/AliFemto/AliFemtoResultStorage.h) and an analysis task [AliAnalysisFemtoNu](https://github.com/alisw/AliPhysics/blob/master/PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemtoNu.h) to go along with that.

I had to adopt the conventions of the AliFemto framework, but it may serve as some inspiration.

**Comment by mgheata** [comment]
Hi,
Indeed looks like AliFemtoResultStorage has part of AliDirList functionality allowing to write the content to a folder. In addition, AliDirList can read content from the folder in a lazy way (just read object names and classes, the actual reading in memory being done upon object access. It also provides TList/TObjArray accessors to make easier manipulation as a collection. 
It appears that AliPhysics is not build against AliRoot master that contains this class, I am trying to test this new utility.

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
+1

**Pull request merged**
