### PR TITLE
New commit to add ntuples task to PWGGA

### PR DESCRIPTION
**Pull request by pdhankhe**
Berkeley group ntuplizer

### CODE REVIEW

**Comment by pdhankhe** [comment]
> [fd9f786](https://github.com/alisw/AliPhysics/commit/fd9f786f84cca3f1e1ae1c80644565813be117aa): approval required: 1 of @ktf (Giulio Eulisse), @pzhristov (Peter Hristov), @davidrohr (David Rohr)
> 
> _Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/16362) and comment at the bottom of the page.**_

Can you please approve the test run?

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
ok, for testing, but this is a lot of additional code

**Comment by ktf** [comment]
also there is a 4MB root file in it. Is it really needed?

**Comment by pdhankhe** [comment]
> also there is a 4MB root file in it. Is it really needed?

Yes it is needed for detector calibration but if it creates problem I can try to modify the task.

**Comment by ktf** [comment]
yes, please. I guess you need to use the OADB for stuff like that, no?

**Comment by pdhankhe** [comment]
The required changes are made. Can you please launch the test run again?

**Comment by pzhristov** [comment]
+test

**Comment by FriederikeBock** [comment]
+1

**Comment by FriederikeBock** [comment]
+test

**Comment by FriederikeBock** [comment]
@pzhristov could you approve for testing, I can't.

**Comment by ktf** [comment]
+test

**Comment by FriederikeBock** [comment]
@pdhankhe it seems to me many of the files in this commit are actually not necessary in aliphysics and are configuration files which you would need for local running/testing. Would you mind reducing the commit to the files which you would really need to be part of aliphysics package/documentation.

**Comment by pdhankhe** [comment]
> @pdhankhe it seems to me many of the files in this commit are actually not necessary in aliphysics and are configuration files which you would need for local running/testing. Would you mind reducing the commit to the files which you would really need to be part of aliphysics package/documentation.

@FriederikeBock I have removed the unnecessary files earlier from the commit. Because of time constraint I was not able to make it concise. I will remove the dependencies as it progresses on the train.

**Comment by pdhankhe** [comment]
> [df22c15](https://github.com/alisw/AliPhysics/commit/df22c15d7dd3103f70b3c19f8460e3f7208a3784): approval required: 1 of @ktf (Giulio Eulisse), @pzhristov (Peter Hristov), @davidrohr (David Rohr)
> 
> _Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/16362) and comment at the bottom of the page.**_

Can you please launch the test again?

**Comment by ktf** [comment]
+test

**Comment by pdhankhe** [comment]
> [47a407c](https://github.com/alisw/AliPhysics/commit/47a407caa5d23620035f31a21e2e4b27168b1ce0): approval required: 1 of @ktf (Giulio Eulisse), @pzhristov (Peter Hristov), @davidrohr (David Rohr)
> 
> _Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/16362) and comment at the bottom of the page.**_
@ktf @pzhristov @davidrohr 
Can you please approve the test run?

**Comment by pzhristov** [comment]
+test

**Comment by ktf** [comment]
The errors seem legit, can you have a look?

**Comment by FriederikeBock** [comment]
@pdhankhe any progress on this?

**Comment by pdhankhe** [comment]
@FriederikeBock We are actively looking into this issue but still haven't figured out the root cause. I hope to update this thread soon.

**Comment by FriederikeBock** [comment]
Hi @ktf , could you have a look and maybe give them a hint where its failing, they are having a hard time figuring out what is happening as the local builds work. Could it be a version mismatch?
Regards,
Friederike

**Comment by ktf** [comment]
+test

**Comment by pdhankhe** [comment]
@ktf @pzhristov @davidrohr: Can you please approve the test run?

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
+test

**Comment by pzhristov** [comment]
+1

**Comment by mfasDa** [comment]
Does no longer compile under macOS Sonoma. Problem seems to be the cgal-4.9.h (why needed, could one please use the CGAL AliPhysics is linked against?).

```
CGAL/Uncertain.h:323:26: note: cast one or both operands to int to silence this warning
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:114:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type&, void > {
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:153:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type, Type > { 
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:162:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type, Type > {
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:170:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type, bool > {
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:178:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type, bool > {
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:223:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function<Type,Type,bool>{ 
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:259:21: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      : public std::binary_function< Type, Type,
               ~~~~~^~~~~~~~~~~~~~~
                    __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:281:21: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      : public std::binary_function< Type, Type,
               ~~~~~^~~~~~~~~~~~~~~
                    __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:374:21: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      : public std::binary_function< Type, Type,
               ~~~~~^~~~~~~~~~~~~~~
                    __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:392:21: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      : public std::binary_function< Type, Type,
               ~~~~~^~~~~~~~~~~~~~~
                    __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:410:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function<Type, Type, bool>{
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:450:21: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
      : public std::unary_function< Type, Type > { 
               ~~~~~^~~~~~~~~~~~~~
                    __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:458:21: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
      : public std::binary_function< Type, Type,
               ~~~~~^~~~~~~~~~~~~~~
                    __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:477:19: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
    : public std::unary_function< Type, Type > { 
             ~~~~~^~~~~~~~~~~~~~
                  __unary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:489:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function< Type, Type, bool > { 
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:525:22: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
        :public std::binary_function<Type,Type&,bool>
                ~~~~~^~~~~~~~~~~~~~~
                     __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:582:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function< Type, Type, 
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:595:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function< Type, Type,
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/binary_function.h:49:1: note: '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
^
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/AliAnalysisTaskNTGJ.cxx:73:
In file included from /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGGA/NtuplizerTask/GJNtuples/jet.h:39:
In file included from <built-in>:1:
In file included from CGAL/Exact_predicates_exact_constructions_kernel.h:28:
In file included from CGAL/Simple_cartesian.h:28:
In file included from CGAL/Cartesian/Cartesian_base.h:28:
In file included from CGAL/basic.h:44:
In file included from CGAL/number_type_basic.h:44:
CGAL/Algebraic_structure_traits.h:608:19: error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
    : public std::binary_function< Type, Type&,
             ~~~~~^~~~~~~~~~~~~~~
                  __binary_function

```

**Pull request merged**
