### PR TITLE
Update on AliAnalysisTaskPHOSCluster

### PR DESCRIPTION
**Pull request by akraiker**
- Added variable fCellAmpFrac for saving cells amplitude fraction
- Updated initialisation values to -1 (instead of 0)
- Accept only clusters in module 1

### CODE REVIEW

**Comment by akraiker** [comment]
Can someone please approve my pull request?

Thankfully yours,
Alexej

**Comment by kharlov** [comment]
+1

**Comment by akraiker** [comment]
Can someone please add the second approvement.

Thankfulle yours,
Alexej

**Comment by peressounko** [comment]
+1

**Pull request closed without merging**
