### PR TITLE
changes for the NanoAOD production of the PWGJEEMCAL tasks

### PR DESCRIPTION
**Pull request by rhaake**
Hi all,

this pull request is a code change from Markus (Zimmermann) to allow my jet task (inheriting from the EMCalJet base task) to run on NanoAODs.

The work was done by Markus and his summer student Lucia, I am just supporting him from the EMCalJet/testing point-of-view and by spreading the word in the PWG.

This patch lays the ground also for other tasks inheriting from the EMCalJet base task to be in principle compatible to NanoAODs. More information on this will follow soon.

The changes in the underlying EMCalJet framework are just minor, so we foresee no problems.

### CODE REVIEW

**Comment by mfasDa** [comment]
Hi @rhaake, 

OK with me for the EMCAL Jet part. I would leave the approval process to @mazimm.

Cheers

Markus

**Comment by rhaake** [comment]
Hi @mfasDa,

thanks for the quick action! I think we need two approvals, right? In the alibuild comment I see "approval required: 1 of @mazimm; 1 of ...".
Maybe I am misinterpreting this, but I think @mazimm does not have sufficient rights.

Best
Ruediger

**Comment by mfasDa** [comment]
+test

Hi @rhaake,

I see. OK, I approve tests from the EMCAL side and leave the PR open to give others a chance to comment. If there are no objections by 3pm CET we will make sure one of us will approve it.
 
Cheers

Markus

**Comment by aiola** [comment]
Hi @rhaake ,
my only comment would be that the new class AliNanoAODArrayMaker should be documented using doxygen syntax.
Thanks,
Salvatore

**Comment by mazimm** [comment]
+1

**Comment by mazimm** [comment]
I am surprised that this was already merged because I should not have the commit rights for the PWGJE part. 
I am not an expert for doxygen but I'll try to add them in a separate commit.

**Comment by rhaake** [comment]
I pushed the documentation written by Markus Z in PR #2859.
It is already approved.

**Comment by aiola** [comment]
Thanks!

**Comment by raymondEhlers** [comment]
Hi All,

This PR seems to be causing a problem with ROOT 6 (at least on macOS). It seems to cause crashes on I/O, but unfortunately the stack trace is entirely useless. My guess is that there are some dependency or streaming problems. I'll look into it further, but I would also appreciate some help, as ROOT 6 is now recommended on macOS. Note that it doesn't show up with ROOT 5.

Best,
Raymond

**Comment by rhaake** [comment]
Hi Raymond,

yes, we are already aware of this problem and @mazimm is working on a solution.
Sorry for the inconvenience, we successfully tested on ROOT5 and unfortunately it passed the PR checks.

Best
Ruediger

**Comment by raymondEhlers** [comment]
Hi @rhaake ,

Thanks for the update - I know that it can be quite difficult to catch all of the ROOT 5 vs 6 difficulties. I look forward to a fix in the near future!

Best,
Raymond

**Pull request merged**
