### PR TITLE
Mask hander providing EMCAL trigger mask in various formats from OCDB

### PR DESCRIPTION
**Pull request by mfasDa**
Providing trigger mask from OCDB at L0 and L1
- as list of FastOR abs. ID
- as list of position in the EMCAL space

### CODE REVIEW

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
Stupid ROOT5!

**Comment by zhaomr13** [comment]
> Stupid ROOT5!

seems that I have the seem problem. I agree, stupid ROOT5!

**Comment by mfasDa** [comment]
+1

**Pull request merged**
