### PR TITLE
New Task for some change

### PR DESCRIPTION
**Pull request by MustafaNajiAnaam**
Some change for sys

### CODE REVIEW

**Comment by yzhouCERN** [comment]
+1

**Comment by shahor02** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @MustafaNajiAnaam ,

why are you committing in the base directory of AliPhysics? This should go to PWGCF, if i understand well (pinging also @yzhouCERN).

Chiara

**Comment by shahor02** [comment]
Indeed, my fault that did not check the directory before doing +1. @MustafaNajiAnaam, please tell to which directory these macros should go, will move them if this PR is merged.

**Comment by yzhouCERN** [comment]
I was also confused by the request that was sent to me (via a private email). I also noticed (after typed +1) that it was not to CF directory and clearly I have no +1 power here. 
I hope Mustafa can fix it.
Cheers,
You

**Comment by chiarazampolli** [comment]
If Mustafa tells where he needs the macros exactly, Ruben offered to take care (I could do it also, but with some delay).

Chiara

**Comment by MustafaNajiAnaam** [comment]
Hi All ,
Thank you so much ,its my mistake ,
So please move it to PWGCF Correlations  and  macros,
Regards,
Mustafa
________________________________

**Comment by shahor02** [comment]
@MustafaNajiAnaam done: https://github.com/alisw/AliPhysics/pull/16566

**Pull request merged**
