### PR TITLE
New hadron fit functions, PbPb 5TeV (mfaggin, 19-Jan-2018)

### PR DESCRIPTION
**Pull request by mfaggin**

### CODE REVIEW

**Comment by mfaggin** [comment]
+1

**Comment by sashingo** [comment]
Hi mfaggin,

I think you accidentally committed "alidist"
If so, could you revoke it ?

regards,
Shingo

**Comment by dberzano** [comment]
Yes I am closing it in order to prevent this from being accidentally committed.

**Comment by mfaggin** [comment]
Dear all,
it was the first time that I tried to commit on AliPhysics.
I followed the following procedure:
1) I went into  Alice/ali-master/AliPhysics and I did "git pull", then I went in my local folder  Alice/ali-master/AliPhysics/PWGHF/hfe/macros/config/PbPb and I copied there the two files that I wanted to commit;
2) I did "git add <files>"
3) then I did "git commit -m <comment>"
4) then "git pull <my_user>"
Finally, I request the pull from my forked version in the browser. I was forced to solve a couple of conflicts, solved through the web interface.
Is there something wrong in the procedure I did?

Thank you.

Mattia

**Comment by dberzano** [comment]
You did `git add` on too many files, and you (accidentally, I believe) cloned alidist inside AliPhysics. Hope this clarifies!

**Pull request closed without merging**
