### PR TITLE
Train macros for Elena pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C

### PR DESCRIPTION
**Pull request by KonstantinMikhaylov**
+test

### CODE REVIEW

**Comment by rbertens** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+test

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Pull request merged**
