### PR TITLE
Filling stability histograms

### PR DESCRIPTION
**Pull request by hdegen**
Added all of the stability histograms needed in the analysis. If any detected problem we can still check the TTrees.

### CODE REVIEW

**Comment by hdegen** [comment]
Dear all, can someone give a +1 or a +test, please? Is there any problem with my modifications?
Thanks in advance!

**Comment by aortizve** [comment]
+test

**Comment by aortizve** [comment]
+1

**Comment by mfasDa** [comment]
Does not compile under mac:

```
DEBUG:AliPhysics:AliPhysics:aliceo2: [299/592] Building CXX object PWGMM/Lumi/CMakeFiles/PWGMMLumi-object.dir/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx.o
DEBUG:AliPhysics:AliPhysics:aliceo2: FAILED: PWGMM/Lumi/CMakeFiles/PWGMMLumi-object.dir/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx.o 
DEBUG:AliPhysics:AliPhysics:aliceo2: /Library/Developer/CommandLineTools/usr/bin/c++  -DWITHALIEN -DWITHXML -D_MODULE_=\"PWGMMLumi\" -I/Users/markusfasel/alice/sw/osx_x86-64/AliRoot/aliceo2-1/include -I/Users/markusfasel/alice/sw/osx_x86-64/AliRoot/aliceo2-1/include/pythia -I/Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi -I/Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWG/Tools -I/Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/OADB -I/Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability -isystem /Users/markusfasel/alice/sw/osx_x86-64/AliEn-Runtime/v2-19-le-1/include -isystem /Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-20-02-alice7-3/include -fPIC -O2 -std=c++17 -Werror=mismatched-new-delete -Werror=delete-non-virtual-dtor -Wno-error=strict-aliasing -Wall -Wno-missing-braces -O2 -g -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -MD -MT PWGMM/Lumi/CMakeFiles/PWGMMLumi-object.dir/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx.o -MF PWGMM/Lumi/CMakeFiles/PWGMMLumi-object.dir/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx.o.d -o PWGMM/Lumi/CMakeFiles/PWGMMLumi-object.dir/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx.o -c /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:99:9: warning: address of array 'this->v0_H' will always evaluate to 'true' [-Wpointer-bool-conversion]
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (v0_H)                   { delete v0_H; }
DEBUG:AliPhysics:AliPhysics:aliceo2:     ~~  ^~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:99:27: error: cannot delete expression of type 'TH1D *[20]'
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (v0_H)                   { delete v0_H; }
DEBUG:AliPhysics:AliPhysics:aliceo2:                                   ^      ~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:100:9: warning: address of array 'this->t0_H' will always evaluate to 'true' [-Wpointer-bool-conversion]
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (t0_H)                   { delete t0_H; }
DEBUG:AliPhysics:AliPhysics:aliceo2:     ~~  ^~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:100:27: error: cannot delete expression of type 'TH1D *[20]'
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (t0_H)                   { delete t0_H; }
DEBUG:AliPhysics:AliPhysics:aliceo2:                                   ^      ~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:101:9: warning: address of array 'this->v0_Timing' will always evaluate to 'true' [-Wpointer-bool-conversion]
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (v0_Timing)         { delete v0_Timing; }
DEBUG:AliPhysics:AliPhysics:aliceo2:     ~~  ^~~~~~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:101:30: error: cannot delete expression of type 'TH2D *[20]'
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (v0_Timing)         { delete v0_Timing; }
DEBUG:AliPhysics:AliPhysics:aliceo2:                              ^      ~~~~~~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:102:9: warning: address of array 'this->t0_Timing' will always evaluate to 'true' [-Wpointer-bool-conversion]
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (t0_Timing)         { delete t0_Timing; }
DEBUG:AliPhysics:AliPhysics:aliceo2:     ~~  ^~~~~~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:102:30: error: cannot delete expression of type 'TH2D *[20]'
DEBUG:AliPhysics:AliPhysics:aliceo2:     if (t0_Timing)         { delete t0_Timing; }
DEBUG:AliPhysics:AliPhysics:aliceo2:                              ^      ~~~~~~~~~
DEBUG:AliPhysics:AliPhysics:aliceo2: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx:148:25: error: variable-sized object may not be initialized
DEBUG:AliPhysics:AliPhysics:aliceo2:         TString selectionCases[fNSelectionCases] = {
DEBUG:AliPhysics:AliPhysics:aliceo2:                                ^~~~~~~~~~~~~~~~
```

Could the experts please have a look? Thanks!

**Pull request merged**
