### PR TITLE
Optionally disable INEL>0 and always set run number

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by mpuccio** [comment]
@FlHerrmann this touches one line of your code that I updated with the latest syntax supported by AliEventCuts. Please check if it is fine with you!

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Dear @fprino , 
Maybe you could approve for the HF part of the changes?
Cheers,
Chiara

**Comment by fprino** [comment]
+1

**Pull request merged**
