### PR TITLE
Adding new weights

### PR DESCRIPTION
**Pull request by chiarazampolli**
- central: noP, noPCts
- semicentral: noP

note that we do not compile the noPCts version, but we have the weights.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Pinging @andreaalici for information.

**Comment by shahor02** [comment]
+1

**Comment by jezwilkinson** [comment]
Hello @chiarazampolli ,
on looking at this it seems it adds some "noPCts" files (e.g. LHC19c2a_TMVAClassification_BDT_12_25_noPCts.class.h) that are not included in the new version of the linkdef/CMakelist, is this intended?

**Comment by chiarazampolli** [comment]
Ciao @jezwilkinson , 

Yes, see comment in the PR. We prepared the files, but since compilation is long, and since today we discussed that the cosThetaStar should be included, for now we go like this. If we want to change, the files are there, we just need to enable them.

Cheers,

Chiara

**Pull request merged**
