### PR TITLE
XCode 9.1 fix

### PR DESCRIPTION
**Pull request by fibnumb**
use std::map instead of map

### CODE REVIEW

**Comment by miranov25** [comment]
Thank you. It was fixed 10 minutes ago. Just before your request.
See:
https://github.com/alisw/AliPhysics/pull/3160

**Comment by miranov25** [comment]
Hallo @fibnumb

Cold you close the pull requst (see comment above). I can not do it.

Marian

**Comment by fibnumb** [comment]
Done

**Comment by AndrewCastro** [comment]
Done.

Andrew Castro

**Pull request closed without merging**
