### PR TITLE
changed eta bin for v1

### PR DESCRIPTION
**Pull request by adubla**

### CODE REVIEW

**Comment by zconesa** [comment]
+test

**Comment by arossi81** [comment]
Ciao Andrea,
the diff is enormous but I think is mainly due to white spaces. Is it? Could you try to do "diff -b" between your version and the previous one and post it here?
Ciao
Andrea

**Comment by mpuccio** [comment]
Ciao Andrea,

try https://github.com/alisw/AliPhysics/pull/2369/files?w=1 , if you add w=1 at the end of the url you can see the diff without whitespaces.

Cheers,
Max

**Comment by adubla** [comment]
Hi all,

yes the difference is just that i change the binning in eta. So  all the rest is just of white space.
Thanks Max for the info about w=1
Ciao,
Andrea

**Comment by arossi81** [comment]
+1
Thanks Andrea for the confirmation and thanks Max for the info!

**Pull request merged**
