### PR TITLE
Update ConfigFemtoAnalysisSec.C

### PR DESCRIPTION
**Pull request by salehmoe**
update binning

### CODE REVIEW

**Comment by salehmoe** [comment]
Update binning to run on train

**Comment by rbertens** [comment]
+test
Hello femto enthusiasts - is there a reason why this pull request has been open for 6 days? 
thanks,
redmer

**Comment by rbertens** [comment]
Hi Github gurus ( @dberzano @ktf ),
I approved this pull request for testing (+test) and aliBuild commented with an error (see message above). However, I cannot access the log (404) and the pull request also shows 'all checks have passed' ... could you tell me what went wrong in this case?
thanks,
redmer
ps I also sent this message via mail earlier, but realize that for the record it's better to actually track this here, so sorry for the double message

**Comment by dberzano** [comment]
Hi, this is a glitch we plan to fix (it's in our checklist but everybody's on vacation these days including myself). What matters is the message saying that everything is OK, and the green ticks bringing to "All checks have passed". If you see that, you may proceed.

**Comment by rbertens** [comment]
+1
thanks for explanation. I've '+1'ed because the pull request seems a bit lonely, and the changed code is owned by the commmitter.

**Pull request merged**
