### PR TITLE
First push of AliMCSpectraWeights to AliPhysics

### PR DESCRIPTION
**Pull request by phuhnGithub**
Online re-weighting of mc particle species

### CODE REVIEW

**Comment by mkruegerGitHub** [comment]
+1

**Comment by phuhnGithub** [comment]
Can someone please approve?

**Comment by bdoenigu** [comment]
Hi!

Unfortunately, someone who has commit rights for PWG/Tools has to do it.

Cheers,
Benjamin

**Comment by pachmay** [comment]
+1

**Pull request closed without merging**
