### PR TITLE
PWGLF: Rearrangement of analysis code

### PR DESCRIPTION
**Pull request by BongHwi**
Basically, no changes on the files.

Only the file path is changed, and re-arranged.

### CODE REVIEW

**Comment by BongHwi** [comment]
Could you check this commit?

**Comment by mkruegerGitHub** [comment]
+1

**Comment by mkruegerGitHub** [comment]
+test

**Comment by BongHwi** [comment]
Sorry for missed testing in the local environment.
It works now.

**Comment by mkruegerGitHub** [comment]
+test

**Comment by mkruegerGitHub** [comment]
+1

**Pull request merged**
