### PR TITLE
Add config. files for Lego train

### PR DESCRIPTION
**Pull request by KonstantinMikhaylov**
+1

### CODE REVIEW

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+test

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by dberzano** [comment]
Looks the system unfroze, finally! Thanks for your patience!

**Pull request merged**
