### PR TITLE
first implementation of c-deuteron reconstruction

### PR DESCRIPTION
**Pull request by jaimenorman**
C-deuteron reconstruction from AOD tracks using the XiC->pKpi class

- Implement option in AliAnalysisTaskSEXicTopKpi to run c-deuteron analysis, with c-deuteron MC ID and matching, deuteron ID and invariant mass window change
- new cuts class for c-deuteron, AliRDHFCutsCdeuterontodKpi, inheriting from AliRDHFCutsXictopKpi. Contains first function for 3sigma PID, and modifications in IsSelected for deuteron ID and invariant mass window
- Add function in AliAODRecoDecayHF3Prong to calculate c-deuteron mass from 3 prong decay
- change inheritence of member variables in AliRDHFCutsXictopKpi to allow for inheritence

### CODE REVIEW

**Comment by arossi81** [comment]
+test

**Comment by jezwilkinson** [comment]
Hi @jaimenorman ,
I think you need to also include extra lines on the CMakeLists and the LinkDef in order to get the new RDHF cut class to compile into the library - in CMakeLists it would be `AliRDHFCutsCdeuterontodKpi.cxx` in with the rest of the `SRCS`, and in PWGHFvertexingHFLinkDef.h:
`#pragma link C++ class AliRHDFCutsCdeuterontodKpi+;`
Could you please add these to the commit?
Cheers,
--Jeremy

**Comment by jaimenorman** [comment]
> Hi @jaimenorman ,
> I think you need to also include extra lines on the CMakeLists and the LinkDef in order to get the new RDHF cut class to compile into the library - in CMakeLists it would be `AliRDHFCutsCdeuterontodKpi.cxx` in with the rest of the `SRCS`, and in PWGHFvertexingHFLinkDef.h:
> `#pragma link C++ class AliRHDFCutsCdeuterontodKpi+;`
> Could you please add these to the commit?
> Cheers,
> --Jeremy

Hi Jeremy, thanks for spotting, I added them now.

Jaime

**Comment by jezwilkinson** [comment]
+test

**Comment by jezwilkinson** [comment]
+1

**Pull request merged**
