### PR TITLE
PWGGA/GammaConv: Replaced SetRCut with SetMinPt cut

### PR DESCRIPTION
**Pull request by fjonasALICE**
- replaced SetRCut with SetMinPt cut in AliConversionMesonCuts & added it to control histos
- added two trees to have a look at what kind of events true signal occurs in
- changed DCA cut for omega analysis

### CODE REVIEW

**Comment by nschmidtALICE** [comment]
Please increase the ClassDef for the classes with new members.

**Comment by fjonasALICE** [comment]
please ignore the ExtractSignalBinning part in my first commit message!

**Comment by nschmidtALICE** [comment]
+test

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
