### PR TITLE
Centrality and EventPlane for Pi0Cands, PosSwap fixes

### PR DESCRIPTION
**Pull request by moliver813**
Makes Centrality Cut apply
Adds Event plane axis to pi0 candidate
Improves tracking of MC pi0s and etas in Pos Swap
Adds histograms to correct position swapping method

### CODE REVIEW

**Comment by e-masson** [comment]
+test

**Comment by e-masson** [comment]
+1

**Comment by moliver813** [comment]
It looks like there is some global build issue currently with root6. 
Conveniently I found a bug already that I'm about to submit a fix for.

**Comment by ktf** [comment]
+test

**Comment by efranzis** [comment]
+1

**Pull request merged**
