### PR TITLE
Fix env vars usage in MeanVertexPreprocessor

### PR DESCRIPTION
**Pull request by dberzano**
* Get non-AliEn specific variable from the environment (as agreed with the DPG)
* Exit with a fatal error if CPASSMODE is not set or does not have a correct val
* Fix wrong indentation and stray whitespaces
* Get rid of `Form` on strings with nothing to form

### CODE REVIEW

**Comment by dberzano** [comment]
Hi all, please check the code carefully before approving! @fprino @dcaffarr @chiarazampolli

**Comment by dberzano** [comment]
Trick: since I have fixed many whitespace errors, to get a diff ignoring those whitespaces (for a better understanding of what the new code does, please check [here](https://github.com/alisw/AliPhysics/pull/853/commits/3ca2bc2b290b73b2af631ca2dc42ec6ffbd5f370?w=1)).

**Comment by chiarazampolli** [comment]
Ciao Dario, all, 

So no AliFatal if the variable is not defined, or I simply don't see it from the diff?

Cheers,

Chiara

**Comment by dberzano** [comment]
`AliFatal` is triggered if the variable is not defined or it has an unsupported value:

```
if (whichpass && *whichpass == '0') {
  // ...
}
else if (whichpass && *whichpass == '1') {
  // ...
}
else {
  AliFatal(...);
}
```

`whichpass` evaluates to false if it's `NULL`, and to true if it's not `NULL`.

**Comment by dberzano** [comment]
@dcaffarr you can test it by temporarily switching your local code to this branch [as explained here](https://help.github.com/articles/checking-out-pull-requests-locally/):

```
git stash
git fetch origin pull/853/head:pr-853
git checkout pr-853
```

When you are done with the testing you can go back to your previous branch (I assume it's `master`):

```
git checkout master
git stash pop
```

**Comment by dberzano** [comment]
+test

**Comment by fprino** [comment]
@dcaffarr : did you run the tests you wanted to do with the modified code?

**Comment by dberzano** [comment]
+test

Note that I got rid of the `TString::Format` as I am not sure about their efficiency (they are safer for sure). `Form` should be "safe enough" for now. Keeping it for consistency with the rest (possibly changing all occurrences in AliPhysics in the future).

**Comment by dberzano** [comment]
FYI AliDPG was updated yesterday, see [here](https://github.com/alisw/AliDPG/commit/2f05a78114954102d52224d02a575c19d11aface).

**Comment by dcaffarr** [comment]
I have just run a test with all possible configurations and everything seems ok to me.  
So in my opinion we can proceed.

**Comment by dberzano** [comment]
+1 and thanks for your feedback!

**Pull request merged**
