### PR TITLE
add a fucntion to set mim. E/p and changed pi0/eta function for the sys. study

### PR DESCRIPTION
**Pull request by sashingo**

### CODE REVIEW

**Comment by sashingo** [comment]
+test

**Comment by sashingo** [comment]
+test

**Comment by dberzano** [comment]
Hi @sashingo, this is an error on our side. If you wait it will clear out automatically. Apologies for the inconvenience.

**Comment by sashingo** [comment]
Hi Dario,

thank you for the information.
I will wait.

regards,
Shingo

**Pull request merged**
