### PR TITLE
New Fired Triggers Added

### PR DESCRIPTION
**Pull request by hdegen**
It was added the EMCAL, MUON and DIMUON triggers to the analysis. The code was also cleaned so any other necessary modification in the future should be easier (to add/remove/modify selection cuts).

### CODE REVIEW

**Comment by hdegen** [comment]
Dear all,

Although many lines were modified, most of the changes were just to clean the code. The important part was that I also added some more triggers to study some dependencies, and those studies would be easier to add with a cleaner code. I tested these mods on grid several times and everything is supposed* to be fine.

Can someone please give a +test or +1?

Thank you very much!
Hermann

**Comment by valzacc** [comment]
+test

**Comment by valzacc** [comment]
+test

**Comment by valzacc** [comment]
+1

**Pull request merged**
