### PR TITLE
fixing harmless bug

### PR DESCRIPTION
**Pull request by arossi81**

### CODE REVIEW

**Comment by arossi81** [comment]
+1

**Comment by alindner14** [comment]
Hi @arossi81! I have the same problem with the root6 test and I have noticed it for other PRs. Do you know what can be done in this case?

**Comment by arossi81** [comment]
Hi @alindner14 ,
no, actually this problem has nothing to do with my modification and for me it was compiling with root6 locally. 
Cheers

**Comment by alindner14** [comment]
same in my case, I think that is a systematic problem in AliPhysics, since there are multiple PRs which fail the same test. I just want to know if the PR can be merged manually or something, since the failed test is unrelated to my changes. 
Cheers

**Pull request merged**
