### PR TITLE
Fix MC origin flag

### PR DESCRIPTION
**Pull request by hzanoli**
Dear all,

I have performed some changes in the code to fix a problem in the tagging of HF particles in MC. I also included some other improvements in the code readability.

Best
Henrique

### CODE REVIEW

**Comment by btrzecia** [comment]
+test

**Comment by hzanoli** [comment]
Sorry, I forgot to add the last changes to the commit, I will add them asap.

**Comment by btrzecia** [comment]
+test

**Comment by btrzecia** [comment]
+1

**Pull request merged**
