### PR TITLE
Update to get deltaPhi for Spherocity axis

### PR DESCRIPTION
**Pull request by mbjadhav**
Adding a 3D histogram to analyse deltaPhi between phi angle of spherocity axis and D-meson direction

### CODE REVIEW

**Comment by fprino** [comment]
Hi Manoj,

I had a look at the modified code.
There are two points which need to be modfied:
In the task when you compute
Double_t deltaPhiRef = (phiRef-phiCand);
you should then modify it to have it in the range from -pi to pi or equivalently from 0 to 2*pi to match the periodicity of the azimuthal angle.
The same range you should then use to bin the axis of the 3D histogram.

Cheers, Francesco

**Comment by mbjadhav** [comment]
Ciao Francesco, 

To get it in 0 to 2*pi, I can take the absolute of (phiRef-phiCand). But When I checked the distribution of deltaPhi locally, it shows three peaks (it is with very low statistics) at 0 (D0 along sphero axis), pi and -pi (D0 opposite to sphero axis). I emailed you the plot. In such a case we cut any one of the peak distributions? Won't it affect much?

Thank you.

**Comment by fprino** [comment]
Hi Manoj,

what you have to do to apply the periodicity in phi is something like:
if(deltaPhiRef<0) deltaPhiRef+=2*TMath::Pi();
if(deltaPhiRef>2*TMath::Pi()) deltaPhiRef-=2*TMath::Pi();

which is different from taking the absolute value.

Cheers, Francesco

**Comment by mbjadhav** [comment]
Ciao Francesco, 

I have updated the task to implement above suggestions. Thank you.

**Comment by fprino** [comment]
Hi Manoj,

there is still one minor change that is needed on the upper edge of the phi axis in the 2D histos.
What you have now as upper range 6.28 is a bit less than 2pi, so there will be unwanted overflows.
You should use 0. and 2*TMath::Pi() as the axis limits.

Cheers. Francesco

**Comment by mbjadhav** [comment]
Ciao Francesco, 

Yes, Sure. Updated it. 

Thank you.
Manoj

**Comment by fprino** [comment]
+1

**Comment by mbjadhav** [comment]
Thank you, Francesco!

**Pull request merged**
