### PR TITLE
Rework of Two and Four Pairing, implemented SupportHistograms for all Cutsettings, deleted a comment

### PR DESCRIPTION
**Pull request by feisenhu**
I reworked the two and four pairing of the EtaReconstruction Programm
Added Histograms 
Deleted a Comment that was pushed accidentally into AliDielectronMC.cxx

### CODE REVIEW

**Comment by miweberSMI** [comment]
Hi @feisenhu,

there are a few comment lines in AliDielectronMC.cxx (see diff) that are probably not intentional. Can you please check again?

Cheers,
Michael

**Comment by feisenhu** [comment]
Hey @miweberSMI 

Like written in the description (see above), the changes in the AliDielectronMC.cxx are ment to remove 2 commented lines that got pushed accidentally in one of the earlier pull request. 
The comments were intended just for personal help and should not be pushed.

Best regads
Florian

**Comment by miweberSMI** [comment]
Hi @feisenhu 

ah sure, you are right. Thanks for clarification...

Cheers,
Michael

**Comment by miweberSMI** [comment]
+1

**Pull request merged**
