### PR TITLE
Improvements in Dstar spectra task wrt faster run + usability for n-ptbins

### PR DESCRIPTION
**Pull request by amveen**
In this commit, the code is made usable with any amount of pt-bins in the cuts and fully responding to that. A change for the settings of the D0-mass window was needed to allow all possible pt-bin settings. 
Furthermore an optimization of the task is done in terms of replacing the time-consuming findhistogram method by a list of pointer pointing to the necessary histograms.

### CODE REVIEW

**Comment by arossi81** [comment]
+test
@amveen , can you increase the ClassDef in the .h?

**Comment by amveen** [comment]
Sure Andrea, now I did +1 the classdef, sorry I forgot to do it initially.

**Comment by arossi81** [comment]
+test

**Comment by ebruna** [comment]
+1

**Pull request merged**
