### PR TITLE
Adding task for D0->pi0piplpimi looking at MC truth

### PR DESCRIPTION
**Pull request by mfasDa**
- Absolute counts in acceptance
- Decay kinematics

### CODE REVIEW

**Comment by mfasDa** [comment]
@FriederikeBock @nschmidtALICE @dmuhlhei  This task is needed as a cross check that we see decays in the  corresponding channels at all in the HF sample. Purely running at particle level, no reconstruction used. At the same time it can also look at the decay kinematics to get some constraints on the daughter particles.

**Comment by mfasDa** [comment]
Sorry, was tested on mac. Needed a case sensitivity fix. @nschmidtALICE , can you please approve testing again?

**Comment by nschmidtALICE** [comment]
+test

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
