### PR TITLE
Update of class used in the DQ train for the low-mass dimuon analysis

### PR DESCRIPTION
**Pull request by bteyssie**
Adding information in the physics selection for the cross-section conversion

### CODE REVIEW

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
+test

**Comment by dberzano** [comment]
This build problem is unrelated to your commit, please be patient and it will be fixed automatically (see alisw/alidist#696). No need to +test (which is ignored).

**Comment by dberzano** [comment]
@bteyssie OK, the _current_ build problem _is_ related to your commit (the previous one wasn't), so you need to fix it.

**Comment by urasantonio** [comment]
+test

**Comment by dstocco** [comment]
+test

**Comment by dstocco** [comment]
+1

**Comment by aphecetche** [comment]
+1

**Pull request merged**
