### PR TITLE
change in cxx file

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
+test

**Comment by jgrosseo** [comment]
+1

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
@jgrosseo: I have fixed the permissions sync (there was a problem with the egroups) and eliminated all comments for clarity, so that you can start over. Details via email.

**Comment by jgrosseo** [comment]
+test

**Comment by jgrosseo** [comment]
+1

**Pull request merged**
