### PR TITLE
Add histogram for part. jet pt relative to pt-hard (pp-only)

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
@ktf PR checked unrelated to the PR - is there some problem with the build infrastructure?

**Comment by ktf** [comment]
Yes, I just sent a message to the mailing list, explaining the issue and apologizing. Everything should be back to normal.

**Comment by mfasDa** [comment]
@ktf Is it possible to restart the PR checker so that the PR can be merged before the tag today?

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
+1

**Pull request merged**
