### PR TITLE
implement MC part

### PR DESCRIPTION
**Pull request by jonghan7**
Implement MC part

### CODE REVIEW

**Comment by jonghan7** [comment]
Dear Collaborators,
I tried "Pull requests" two days ago but the modified version hasn't merged yet. I can find messages here as "Some checks haven't completed yet" and "No conflicts with the base branch". Could you please try test and approve it if there is no errors. Thanks in advance.

**Comment by sashingo** [comment]
+1

**Comment by pzhristov** [comment]
@jonghan7 Please increment the LinkDef.

**Comment by jonghan7** [comment]
> @jonghan7 Please increment the LinkDef.

I've already added the name of source code in the LinkDef (PWGHFhfeLinkDef.C). Let me know if I have to do further action. Thanks.

**Pull request merged**
