### PR TITLE
Revert moving to namespace EMCAL because of a problem with constants …

### PR DESCRIPTION
**Pull request by mfasDa**
…used in macros appearing in some cases under ROOT5

### CODE REVIEW

**Comment by mfasDa** [comment]
+test

**Comment by mfasDa** [comment]
@sashingo @gconesab  Could you both please do a "+test"?

**Comment by gconesab** [comment]
+test

**Comment by mfasDa** [comment]
Was reported by some users accessing track type constants in macros that constant name including the namespace was misinterpreted, leading to an error that the constant was not found. The error happens purely under ROOT5, and happens only under certain conditions as the case reported was reproducable but other macros do run normally without errors and use the proper constant value. 

As long as the reason is not understood the change will be reverted.

**Comment by mfasDa** [comment]
@sashingo @arossi81 @ginesmartinez @fcolamar @zconesa @rbailhac @ebruna @fprino 

Coud someone of the HF conveners please approve the HF part of the commit!

**Comment by zconesa** [comment]
+1

**Pull request merged**
