### PR TITLE
fix file PATH for the OADB access

### PR DESCRIPTION
**Pull request by mazimm**
fix access to the separate OADB repository

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by dberzano** [comment]
@mazimm do you have other changes you would like to merge? Do not forget to port them to the _current_ AliPhysics as this repository will be completely erased on the migration date!

**Comment by mazimm** [comment]
@dberzano I know, this is only to test if the large files are accessible on the trains. This is the only change.

**Comment by dberzano** [comment]
+1

**Pull request merged**
