### PR TITLE
 EP angle vs. q2 histos +  Fixed non static data members 

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Comment by arossi81** [comment]
+1

**Comment by shahor02** [comment]
+test

**Comment by shahor02** [comment]
+1

**Comment by raymondEhlers** [comment]
I think aliBuild didn't parse the +1 here - can you try it again? It would be good to get this issue finally resolved. Thanks!

**Comment by shahor02** [comment]
+1

**Pull request merged**
