### PR TITLE
PWGGA/GammaConv/..

### PR DESCRIPTION
**Pull request by AMechler**
AliCaloPhotonCuts.cxx
Added NonLin 21 for DCal LHC16k5a, LHC16k5b and LHC17e2
macros/AddTask_GammaCalo_pp.C
Changed Cutstrings for DCal NonLin to 21 (was 11)

### CODE REVIEW

**Comment by dmuhlhei** [comment]
Hi @AMechler, please fix your conflicts as indicated by the automatic message

**Comment by AMechler** [comment]
there was an commit while my rebase and this merge request im working on resolving the issue

**Comment by AMechler** [comment]
Merge conflict is solved

**Comment by dmuhlhei** [comment]
@AMechler please fix the logic, your added lines will never be executed.

**Comment by AMechler** [comment]
Thanks @dmuhlhei,
I'm glad you found that one!

I changed the logic, it should work like intended now.

**Comment by dmuhlhei** [comment]
+1

**Pull request merged**
