### PR TITLE
GammaConv: adding pT weights for Gamma in Material Histos; rework Add…

### PR DESCRIPTION
**Pull request by amaringarcia**
…Task_MaterialHistos_pp.C to run with root6

### CODE REVIEW

**Comment by amaringarcia** [comment]
as there are many changes, the merged is not necessary for today but it will be good to have it for tomorrow

**Comment by nschmidtALICE** [comment]
please increase the classdef of all modified headers

**Comment by nschmidtALICE** [comment]
+test

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
