### PR TITLE
By default extend the kstar range to 3 GeV/c

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by a-mathis** [comment]
+1

**Comment by a-mathis** [comment]
@ktf the PR was not re-tested since almost a day, is there a way to manually trigger the re-build?

**Comment by ktf** [comment]
@a-mathis just push something on the repository.
@TimoWilken this is still the DPMJET issue, correct?

**Comment by ktf** [comment]
+1

**Comment by ktf** [comment]
Trivial. Merging.

**Comment by TimoWilken** [comment]
@ktf, yes, it's the DPMJET issue. Previous builds of this PR succeeded.

**Comment by a-mathis** [comment]
@ktf @TimoWilken Thanks a lot!

**Pull request merged**
