### PR TITLE
histograms added for simulation

### PR DESCRIPTION
**Pull request by anmishra0**

### CODE REVIEW

**Comment by anmishra0** [comment]
Hello,

I am waiting for reply.

Aditya

**Comment by anmishra0** [comment]
Hello,

I have submitted  a commit request 2 days ago but haven't got any reply on it.
I would like to request you all please reply.


Aditya


________________________________
Dr. Aditya Nath Mishra
Post-Doctoral Fellow
Wigner Research Centre for Physics
H-1525 Budapest 114, POB. 49, Hungary
Ph: +91 97 1301 1592 (WhatsApp)
      +36 30 710 2745
aditya.nath.mishra@wigner.hu<mailto:aditya.nath.mishra@wigner.hu>
Aditya.Nath.Mishra@cern.ch<mailto:amishra@cern.ch>
_________________________________
________________________________

**Comment by valzacc** [comment]
+test

**Comment by valzacc** [comment]
+1

**Pull request merged**
