### PR TITLE
Including the k0p task

### PR DESCRIPTION
**Pull request by lramona**
Commit for M. Urioni

### CODE REVIEW

**Comment by lramona** [comment]
Can you please approve the commit? Thanks

**Comment by sartozza** [comment]
+1

**Comment by vvislavi** [comment]
+1

**Comment by vkucera** [comment]
Hi @lramona 
Looks like this PR produces this warning:
```
Warning in <TInterpreter::ReadRootmapFile>: class  AliReconstructedFirst found in libPWGCFK0pAnalysis  is already in libPWGCFKPAnalysis 
```

**Comment by mfasDa** [comment]
Hi @lramona 

After this PR there are two classes which are now present twice with the same name in different files: 

```
Warning in <TInterpreter::ReadRootmapFile>: class  AliReconstructedFirst found in libPWGCFK0pAnalysis  is already in libPWGCFKPAnalysis 
Warning in <TInterpreter::ReadRootmapFile>: class  AliReconstructedSecond found in libPWGCFK0pAnalysis  is already in libPWGCFKPAnalysis 
```

This confuses the ROOT autoloader which automatically loads classes based on their name and dependency chain in the rootmap file, and I am not sure this is what you want to have. Could you please rename the new class, or if it is a 1-to-1 copy of the existing class move it to a common library, in order to remove the warning? Thanks!

**Pull request merged**
