### PR TITLE
Add separate check for L1 phase shift enabled in RecalibrateCells

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
@gconesab @raymondEhlers Any problem with this? Up to now the check for L1 phase shift enabled was part of the check for the time calibration, so if the time calibration is switched off the phase shift correction cannot be applied separately.

**Comment by raymondEhlers** [comment]
Seems fine to me

**Comment by gconesab** [comment]
I am also fine with it
+1

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
@gconesab @raymondEhlers Thanks for your review!
@gconesab I think the `+1` must be in the first line, otherwise it is not recognised as approval. Adding comments in lines below, in addition to the `+1` seems to work

**Pull request merged**
