### PR TITLE
PWGEM:LMee: Adding new variables to TreeMaker

### PR DESCRIPTION
**Pull request by jjungIKF**

### CODE REVIEW

**Comment by dsekihat** [comment]
+1

**Comment by TimoWilken** [comment]
Hi, for some reason, this PR causes the `load_library_PWGDQdielectron` and `load_library_PWGDQreducedTree` tests to take forever. They only time out after 10 hours. This happens on two different CI machines, but I can't immediately see a reason for it from the proposed changes, though I'm a bit puzzled by the added duplicate lines here:

https://github.com/alisw/AliPhysics/pull/22364/files#diff-8d7bffc4c95aaedbf5f05fa9825b413cc4345a2e1b91cef1e4c440c4518bff94R176-R177

Have you tried to compile and test this locally?

**Comment by jjungIKF** [comment]
Hi Timo,
sorry I did not see that you commented on this before I closed this pull request.
Unfortunately, I can no longer open the link, Can you tell me again which lines you are referring to?
I tested the commit locally and everything compiled without issues.
I opened a new request with some code updates but the issue remains.

**Comment by jjungIKF** [comment]
> Hi, for some reason, this PR causes the `load_library_PWGDQdielectron` and `load_library_PWGDQreducedTree` tests to take forever. They only time out after 10 hours. This happens on two different CI machines, but I can't immediately see a reason for it from the proposed changes, though I'm a bit puzzled by the added duplicate lines here:
> 
> https://github.com/alisw/AliPhysics/pull/22364/files#diff-8d7bffc4c95aaedbf5f05fa9825b413cc4345a2e1b91cef1e4c440c4518bff94R176-R177
> 
> Have you tried to compile and test this locally?

Hi Timo,
sorry I did not see that you commented on this before I closed this pull request.
Unfortunately, I can no longer open the link, Can you tell me again which lines you are referring to?
I tested the commit locally and everything compiled without issues.
I opened a new request with some code updates but the issue remains.

**Pull request closed without merging**
