### PR TITLE
AliEventCuts:: corrected run range for run1 pp 8TeV

### PR DESCRIPTION
**Pull request by mkruegerGitHub**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
This corresponds to PHYSICS runs, with data migrated, correct @mkruegerGitHub ?
I am approving as checking in the logbook it seems fine. Before, almost all 12i was excluded, if I am not wrong.

Chiara

**Comment by chiarazampolli** [comment]
+1

**Comment by mkruegerGitHub** [comment]
Hello Chiara,
the runs I specified now are corresponding to the first one in LHC12a and the last LHC12i available in our file system.
The run range in the version before did not include LHC12i because I accidentaly took the first instead of the last run in this period.
Thanks for approving.
Cheers,
  Mario

**Comment by chiarazampolli** [comment]
Thanks @mkruegerGitHub for explaining!

File system --> alien, right? So my query to the logbook was correct.

**Comment by mkruegerGitHub** [comment]
Yes

**Pull request merged**
