### PR TITLE
PWGGA/GammaConv: Fixing small memory leaks

### PR DESCRIPTION
**Pull request by mfasDa**
AliVCluster pointer handled by std::unique_ptr. In addition
remove background handlers and not just the array containing
them in the destructor.

### CODE REVIEW

**Comment by dmuhlhei** [comment]
I'm fine with these changes, @nschmidtALICE or @FriederikeBock could you please have a look as well?

**Comment by nschmidtALICE** [comment]
+test

**Comment by nschmidtALICE** [comment]
Also looks okay from my side. I'll first test and then approve it.

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
