### PR TITLE
added isoenergy to correlation histo.

### PR DESCRIPTION
**Pull request by sashingo**

### CODE REVIEW

**Comment by sashingo** [comment]
+1

**Comment by shahor02** [comment]
+1

**Comment by shahor02** [comment]
@sashingo `+1` of only those in the `approval required:..` message will work...

**Comment by ktf** [comment]
+test

**Comment by sashingo** [comment]
Dear Ruben,
thank you for the approval.
Indeed I's in the approval required at least until yesterday.

https://github.com/alisw/AliPhysics/pull/18050#issuecomment-872257240

And I'm not sure the reason for I'm not in the approval required in this commit.

**Pull request merged**
