### PR TITLE
test for workflow

### PR DESCRIPTION
**Pull request by mawulff**

### CODE REVIEW

**Comment by vpacik** [comment]
Hi @mawulff,
Given the 'test' content of the commits, I guess it would be better not to merge this upstream.
Could you please close this pull request?
Best, Vojtech

**Comment by mawulff** [comment]
Dear Vojtech,

This commit was a mere and trivial comment, just to demonstrate to a new student in ALICE the git workflow, i.e. how the newly developed code is propagated in practice from the local AliRoot, to the new daily tag, after which it is available for the analysis on Grid.

Therefore, just for educational purposes, please could you approve this trivial pull request?

We will revert this trivial change in the next pull request, when we will also commit a lot of new and non-trivial code.

Thanks a lot for your time!
 
Ante

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
Dear @mawulff,

Ok, I approved the commit for the pedagogical purpose. However, please note that any commit (testing or not) will be propagated upstream for anybody. Also, most of the workflow featrues can be mimicked and tested using personal repository/forks.

PS: There are some root6 issues will pull request, at the moment. 
Best, Vojtech

**Pull request merged**
