### PR TITLE
Fix AliTriggerAnalysis: TPC HV dip detection

### PR DESCRIPTION
**Pull request by dmuhlhei**
clean version of PR #6898

### CODE REVIEW

**Comment by chiarazampolli** [comment]
I would like @wiechula to confirm that it is fine.

Chiara

**Comment by dmuhlhei** [comment]
Yes, of course. Thanks a lot

**Comment by wiechula** [comment]
Yes, this is fine for me. However, we should still understand why this could have an effect.
I don't understand it to be honest.

**Comment by chiarazampolli** [comment]
Ok, I am giving a +1 then, while you follow it up.

Chiara

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
