### PR TITLE
Updated cut-variation systematics for RAA

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Comment by zconesa** [comment]
Ciao @fgrosa, the diff file is showing plenty of differences in the commit, basically the full file. They mostly look like empty spaces here and there, but it becomes bit difficult to check what really changed. Would it be possible to get rid of those?

**Comment by fgrosa** [comment]
Ciao @zconesa, you are right. However I have no idea how to remove these differences, since I did not remove/add any empty space. Do you have any suggestion how to get rid of them? 
In any case I can tell you the lines that I really modified: line 6867 (in the method InitDplustoKpipi2015PbPb010) and line 6923 (in the method InitDplustoKpipi2015PbPb3050). These were the small changes to the systematic uncertainties that I presented at the D2H meeting the 24 November 2017.

**Comment by mpuccio** [comment]
Hi @fgrosa @zconesa, in Github you can ignore whitespace changes by appending ?w=1 to the webpage url you are looking at. For instance, in the case of this pr you can check [https://github.com/alisw/AliPhysics/pull/3436/files?w=1](https://github.com/alisw/AliPhysics/pull/3436/files?w=1) .

**Comment by fgrosa** [comment]
Hi @mpuccio, thanks a lot for the suggestion!

**Comment by zconesa** [comment]
+1

**Pull request merged**
