### PR TITLE
Update EMCal, EMCal-Jet run macros for ROOT 6

### PR DESCRIPTION
**Pull request by raymondEhlers**
Tested that all run on ROOT 6, but additional testing on ROOT 5 would be
helpful.

@aiola , @mfasDa, @jdmulligan  - I received a request to update these for ROOT 6, so I gave it a quick shot. Seems to work fine on ROOT 6, but testing on ROOT 5 or general comments are welcome. I updated the trigger QA run macro because I ran across it, but I could remove the changes if desired

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+test (Won't be meaningful, but doing it now anyway so merging will go faster)

**Comment by adriansev** [comment]
Wouldn't be easier to add Create{AOD,ESD}Chain utilities in a general lib? (maybe even in ALIROOT in AliAnalysisManager.h as static methods as they are general functions to create chains to be used with StartAnalysis method of AliAnalysisManager)?

**Comment by raymondEhlers** [comment]
Sure, it would be better, but I was trying to make the most minimal changes possible. At the first glance, I think the two functions could possible be (mostly) combined together by just adding a few variables. Unfortunately, I don't have the time to push through and test such a change, so I propose this as the next best option. But I would certainly support such a change if someone else wanted to take the initiative

**Comment by mfasDa** [comment]
Hi @raymondEhlers,

I see no obvious problems for ROOT5 in the changes, and I can definitely confirm that the ifdef __CLING__ guards will execute properly the ROOT6-specific code under cling and ifndef __CLING__ will properly execute the ROOT5-specific code under cint (other direction with __CINT__ is not the case) - this part I have tested.

While I agree that it is the right way to go away from macros in favor of compiled code also for helpers like chain creators I think it is not urgent. I think the change could be merged.

Cheers

Markus

**Comment by raymondEhlers** [comment]
+1 Thanks to everyone for the comments!

**Pull request merged**
