### PR TITLE
PWGGA/GammaConv: iso analysis additional histos & debug output

### PR DESCRIPTION
**Pull request by fjonasALICE**

### CODE REVIEW

**Comment by nschmidtALICE** [comment]
+1

**Comment by fjonasALICE** [comment]
@ktf tagging you for easy reference to broken pull requests

**Comment by ktf** [comment]
Thanks. I will look into it later today.

**Comment by fjonasALICE** [comment]
Thanks a lot! As far as I can see the same error already occurs for pull requests about 4 days ago

**Pull request merged**
