### PR TITLE
Output files will contain the fitType in the name, added Aleph as function

### PR DESCRIPTION
**Pull request by MartinSchmidtTuebingen**

### CODE REVIEW

**Comment by efranzis** [comment]
+test

**Comment by fprino** [comment]
+test

**Comment by fprino** [comment]
Hi,

to me this pull request looks OK. @wiechula, @miranov25 can you please confirm as TPC experts that we can merge it?

Cheers, Francesco

**Comment by dberzano** [comment]
Closing due to lack of feedback. Reopen if appropriate.

**Pull request closed without merging**
