### PR TITLE
updating CMakeList.txt & PWGGAEMCALTasksLinkDef.h to include AliAnaly…

### PR DESCRIPTION
**Pull request by miguelignacio**
updating CMakeList.txt & PWGGAEMCALTasksLinkDef.h to include AliAnalysisTaskEMCALPi0GammaCorr; update AddTask function name.

### CODE REVIEW

**Comment by efranzis** [comment]
+test

**Comment by dlodato** [comment]
+1

**Comment by gconesab** [comment]
Hello,

I have just done a pull request of master, compiled on mac and get this

[100%] Building CXX object
PWGGA/EMCALTasks/CMakeFiles/PWGGAEMCALTasks-object.dir/AliAnalysisTaskEMCALPi0GammaCorr.cxx.o
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:463:1:
warning: control may reach end of non-void function [-Wreturn-type]
}
^
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:558:1:
warning: control reaches end of non-void function [-Wreturn-type]
}
^
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:653:34:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
              cluster->GetM02(), cluster->GetNTracksMatched(),
cluster->GetNExMax()
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:653:34:
note: insert an explicit cast to silence this issue
              cluster->GetM02(), cluster->GetNTracksMatched(),
cluster->GetNExMax()
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                 static_cast<double>(        )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:653:64:
error: non-constant-expression cannot be narrowed from type 'UChar_t'
      (aka 'unsigned char') to 'double' in initializer list
[-Wc++11-narrowing]
              cluster->GetM02(), cluster->GetNTracksMatched(),
cluster->GetNExMax()

 ^~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:653:64:
note: insert an explicit cast to silence this issue
              cluster->GetM02(), cluster->GetNTracksMatched(),
cluster->GetNExMax()

 ^~~~~~~~~~~~~~~~~~~~

 static_cast<double>()
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:74:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...

 ^~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:74:
note: insert an explicit cast to silence this issue
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...

 ^~~~~~~~~~~~~~~~~~~~~~~~~

 static_cast<double>(     )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:101:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...

                        ^~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:101:
note: insert an explicit cast to silence this issue
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...

                        ^~~~~~~~~~~~~~~~~~~~~~~~

                        static_cast<double>(    )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:127:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...


^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:127:
note: insert an explicit cast to silence this issue
                          cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub-...


^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

                                                  static_cast<double>(
        )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:162:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
  ...cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub->GetNTracksMatched(),


^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:707:162:
note: insert an explicit cast to silence this issue
  ...cluster_lead->GetM02(), cluster_sub->GetM02(),
cluster_lead->GetNCells(), cluster_sub->GetNCells(),
cluster_lead->GetNTracksMatched(), cluster_sub->GetNTracksMatched(),


^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


static_cast<double>(            )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:708:27:
error: non-constant-expression cannot be narrowed from type 'UChar_t'
      (aka 'unsigned char') to 'double' in initializer list
[-Wc++11-narrowing]
                          cluster_lead->GetNExMax(),
cluster_sub->GetNExMax()};
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:708:27:
note: insert an explicit cast to silence this issue
                          cluster_lead->GetNExMax(),
cluster_sub->GetNExMax()};
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                          static_cast<double>(     )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:708:54:
error: non-constant-expression cannot be narrowed from type 'UChar_t'
      (aka 'unsigned char') to 'double' in initializer list
[-Wc++11-narrowing]
                          cluster_lead->GetNExMax(),
cluster_sub->GetNExMax()};

 ^~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:708:54:
note: insert an explicit cast to silence this issue
                          cluster_lead->GetNExMax(),
cluster_sub->GetNExMax()};

 ^~~~~~~~~~~~~~~~~~~~~~~~
                                                     static_cast<double>(
 )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:102:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
    double entries[10] = {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(),
ph.Phi(), cluster->GetM02(), cluster->GetNCells(),
cluster->GetNTracksMatched(), cluster->GetNExMax()...

                         ^~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:102:
note: insert an explicit cast to silence this issue
    double entries[10] = {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(),
ph.Phi(), cluster->GetM02(), cluster->GetNCells(),
cluster->GetNTracksMatched(), cluster->GetNExMax()...

                         ^~~~~~~~~~~~~~~~~~~~

                         static_cast<double>()
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:124:
error: non-constant-expression cannot be narrowed from type 'Int_t' (aka
'int') to
      'double' in initializer list [-Wc++11-narrowing]
    double entries[10] = {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(),
ph.Phi(), cluster->GetM02(), cluster->GetNCells(),
cluster->GetNTracksMatched(), cluster->GetNExMax()...

                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:124:
note: insert an explicit cast to silence this issue
    double entries[10] = {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(),
ph.Phi(), cluster->GetM02(), cluster->GetNCells(),
cluster->GetNTracksMatched(), cluster->GetNExMax()...

                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

                                               static_cast<double>(        )
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:154:
error: non-constant-expression cannot be narrowed from type 'UChar_t'
      (aka 'unsigned char') to 'double' in initializer list
[-Wc++11-narrowing]
  ...= {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(), ph.Phi(),
cluster->GetM02(), cluster->GetNCells(), cluster->GetNTracksMatched(),
cluster->GetNExMax()};


 ^~~~~~~~~~~~~~~~~~~~
/AliceSoft/aliphysics/master/src/PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx:719:154:
note: insert an explicit cast to silence this issue
  ...= {fCent, fVertex[2], ph.E(), ph.Pt(), ph.Eta(), ph.Phi(),
cluster->GetM02(), cluster->GetNCells(), cluster->GetNTracksMatched(),
cluster->GetNExMax()};


 ^~~~~~~~~~~~~~~~~~~~


 static_cast<double>()
2 warnings and 11 errors generated.
make[2]: ***
[PWGGA/EMCALTasks/CMakeFiles/PWGGAEMCALTasks-object.dir/AliAnalysisTaskEMCALPi0GammaCorr.cxx.o]
Error 1
make[1]: *** [PWGGA/EMCALTasks/CMakeFiles/PWGGAEMCALTasks-object.dir/all]
Error 2
make: *** [all] Error 2

Miguel, can you have a look?

Thanks ... Gustavo

2017-06-14 12:00 GMT+02:00 ALICE Builder <notifications@github.com>:

**Comment by gconesab** [comment]
And let me do few suggestions

The main problem is filling a double array with ints or chars, you should
cast them.

Some coding violations: do not use "_" in variable names

Replace all abs by TMath::Abs

It is preferred the use of the Root definitions Int_t, Double_t, Float_t,
instead of int, double, float.

Please add a description of the class in the .h, preferably in doxygen
style (remove the $Id$, this works only for CVS not GIT), see Dario's pages.

In case you cannot reproduce, I managed to make it compilable, let me know
and I will commit my changes.

Cheers  ... Gustavo


2017-06-14 12:33 GMT+02:00 gconesab <notifications@github.com>:

**Comment by miguelignacio** [comment]
Hi @gconesab,

I did check whether it compiled before I commited the changes. I copied below that I got. 
That being said, I would be more than willing to change these things that are causing problem, but given that you already did, I would ask you to commit the changes. Thank you very much!

PS: My late response to this is because I am in CET-9. 
cheers,
Miguel


> => Build of AliPhysics successfully completed on `84VFRC2'.
>     Your software installation is at:
> 
>      /root/sw/ubuntu1404_x86-64
> 
>    You can use this package by loading the environment:
> 
>      alienv enter AliPhysics/latest-alice
> 
> ==> Build directory for devel package AliRoot:
>     /root/sw/BUILD/AliRoot-latest-alice/AliRoot
> 
> ==> Build directory for devel package AliPhysics:
>     /root/sw/BUILD/AliPhysics-latest-alice/AliPhysics
> root@84VFRC2:~/alice#

**Comment by mfasDa** [comment]
Hi @miguelignacio,

I have observed the errors as well. These are c++11 narrowing errors (mismatch in precision for initializer lists objects), typically raised only by the clang compiler under macOS (for which they were not detected before). The issue with the abs is in the way you use it that once the namespace is missing the c-version is used, which is for integer values, which - in this case - ends up in a c++11 narrowing. Using abs without anything is dangerous, as you might truncate in certain cases without noticing. Better use std::abs or TMath::Abs.

As being blocked by this I went through your code and fixed all the c++11 narrowing errors. I could open a pull request for this.

Best Regards

Markus

**Comment by miguelignacio** [comment]
Hi @mfasDa ,
I see, OK. Could you please submit the fixes? thank you!
cheers,
Miguel

**Pull request merged**
