### PR TITLE
improved trigger patch handling in MC

### PR DESCRIPTION
**Pull request by ReneChristianSchach**
Trigger patch rejection doesn't affect MCtruth anymore.
I also fixed compiler warnings.

### CODE REVIEW

**Comment by dlodato** [comment]
+test

**Comment by e-masson** [comment]
Hi @ReneChristianSchach, thanks for making some cleaning in the unused variables. One question: why did you rearranged some histogram declarations in the `.h`? To match it to their order in the `.cxx`?

Best,
Erwann

**Comment by ReneChristianSchach** [comment]
Hi @e-masson, some of the compiler warnings were about the wrong order of initialization of these histograms, that's why I changed it.

Regards,
Rene

**Comment by e-masson** [comment]
Hi @ReneChristianSchach, ok, I did not mention that the last time I compiled. Thanks again so!

Best,
Erwann

**Comment by ReneChristianSchach** [comment]
Hi @e-masson , the -Wall flag was added to AliPhysics a few weeks ago, prior to that the compiler didn't print those warnings.

Regards,
Rene

**Comment by e-masson** [comment]
+test

**Comment by dlodato** [comment]
+1

**Pull request merged**
