### PR TITLE
MUON QA: revert changes since v5-09-08

### PR DESCRIPTION
**Pull request by dberzano**
A problem was encountered during the release validation.

Commits reverted:

* Order file list with increasing run number
* Improve protection for division by 0
* Allow to delay initialisation
* Zoom pad on double click

### CODE REVIEW

**Comment by dberzano** [comment]
+1 @pzhristov @dstocco fyi

**Comment by dberzano** [comment]
See [ALIROOT-7321](https://alice.its.cern.ch/jira/browse/ALIROOT-7321).

**Comment by dstocco** [comment]
Hi,
can the merging be stopped? The correct commit to revert is:
68030c906df6cb3e4dbccf50afa4073b6740c874
Cheers,
Diego

**Comment by dberzano** [comment]
+1 Hello @dstocco, I have updated the PR according to your suggestion. For the record: any merge can be stopped by just updating the PR with new commits before the actual merging occurs.

**Comment by dstocco** [comment]
Cool! Good to know!
Thanks!
Ciao,
Diego

**Pull request merged**
