### PR TITLE
Changes to include new photon analysis

### PR DESCRIPTION
**Pull request by csergilo**
New direct photon analysis, in progress

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by dmuhlhei** [comment]
Hi Carolina,
I wonder what you plan to do with this new task. We already have all possible helper classes/main tasks implemented which are needed for direct photon analyses using PCM and related PCM-EMCal method. If you think something is missing, we can discuss - maybe in the next PCG meeting - and implement it for everybody.

Besides: you have quite some "cout" in your task, which we like to avoid in order to not produce big log-files.

For the moment, we will not approve this request.
Cheers
Daniel

**Comment by dberzano** [comment]
Hi @dmuhlhei do you want me to close it?

**Comment by FriederikeBock** [comment]
yes please

**Comment by dmuhlhei** [comment]
thanks

**Pull request closed without merging**
