### PR TITLE
Improve analysis code in order to better structure the input

### PR DESCRIPTION
**Pull request by MartinSchmidtTuebingen**

### CODE REVIEW

**Comment by raymondEhlers** [comment]
Is this supposed to be a draft? ie. not ready to be merged?

**Comment by MartinSchmidtTuebingen** [comment]
@raymondEhlers Yes. In principle, it is finished, but I want to test it locally.

**Comment by raymondEhlers** [comment]
Okay, then please ping me when it's ready

**Comment by raymondEhlers** [comment]
+1

**Pull request closed without merging**
