### PR TITLE
add option 'addPCMV0s' for ESD Filter

### PR DESCRIPTION
**Pull request by m-c-danisch**

### CODE REVIEW

**Comment by dmuhlhei** [comment]
Hi Meike, before furthing checking: please increment the classdef of V0ReaderV1

**Comment by amaringarcia** [comment]
Hi Meike, all,
can you check if the psi wait recalculation  is in the version of the AliV0Reader to be used?
we also need that.
Ana

**Comment by m-c-danisch** [comment]
@amaringarcia and I agree that this is clear now since the latest AliRoot/AliPhysics is going to be used for refiltering

**Comment by pzhristov** [comment]
+test

**Comment by dmuhlhei** [comment]
+1

**Pull request merged**
