### PR TITLE
Added task to create conversion maps

### PR DESCRIPTION
**Pull request by hmurakam**
- for bookkeeping 
- JIRA: PWGPP-527 ALIROOT-3736 - all plots are created using this task

### CODE REVIEW

**Comment by dmuhlhei** [comment]
+test

**Comment by hmurakam** [comment]
@ktf
Dear All,
I am tying to fix the error but log looks empty. 
At least, I could compile the task locally, and could submit jobs on the grid already. 
Could you tell me what should I do ? 

Cheers, Hikari

**Comment by nschmidtALICE** [comment]
@hmurakam the problem does not seem to be in your code. It appears as if the build test machine is having problems. This should be resolved after a bit.

**Comment by nschmidtALICE** [comment]
+1

**Comment by hmurakam** [comment]
I forgot to change CMakeLists. I will close this PR, and reopen later.

**Pull request closed without merging**
