### PR TITLE
Modifying Config file for pion-kaon femtoscopy

### PR DESCRIPTION
**Pull request by apandey609**

### CODE REVIEW

**Comment by naghmehmohammadi** [comment]
+1

**Comment by akubera** [comment]
Why did this remove my AliFemtoEventReaderAlt from the LinkDef?

**Comment by apandey609** [comment]
Dear Andrew,

I do not know.  Can you commit the updated version of Linkdef which contain your class too?  It will solve the problem.

Best regards,
Ashutosh


On 15-Apr-2019 2:29 AM, Andrew Kubera <notifications@github.com> wrote:

Why did this remove my AliFemtoEventReaderAlt from the LinkDef?

**Comment by apandey609** [comment]
Dear Andrew,

I do not know.  Can you commit the updated version of Linkdef which contain your class too?  It will solve the problem.

Best regards,
Ashutosh

Thanks and best regards,
Ashutosh Kumar Pandey,
IIT BOMBAY, India
Website: https://ashutoshkrpandey.com<https://ashutoshkrpandey.com/>
________________________________

**Comment by vpacik** [comment]
Hi @apandey609: when pushing a new changes, you should always pull all changes first by `git pull --rebase`. This is especially crucial when you modify general code affecting other people, such as CMakeList, LinkDefs, common classes used in more than just your own analysis code, etc. (when you pushing changes of your own code which no-one else changes over time, this might be to some extend omitted. Though this is not recommended unless you are 100% sure).

**Comment by apandey609** [comment]
Dear [X] Vojtech Pacik,

Thanks for suggestion. I think I had earlier modified the Linkdef file but didn't commit. Yesterday it is committed with config file, by mistake. I will take care in future.

Thanks and best regards,
Ashutosh Kumar Pandey,

________________________________

**Comment by apandey609** [comment]
> Hi @apandey609: when pushing a new changes, you should always pull all changes first by `git pull --rebase`. This is especially crucial when you modify general code affecting other people, such as CMakeList, LinkDefs, common classes used in more than just your own analysis code, etc. (when you pushing changes of your own code which no-one else changes over time, this might be to some extend omitted. Though this is not recommended unless you are 100% sure).

Dear Vojtech Pacik, 

Thanks for suggestion. I think I had earlier modified the Linkdef file but didn't commit. Yesterday it is committed with config file, by mistake. I will take care in future. 

Thanks and best regards, 
Ashutosh Kumar Pandey,

**Comment by akubera** [comment]
That's ok, I just wondered if it was breaking something and there was an unnamed reason for its removal.

**Comment by apandey609** [comment]
Thanks for understanding. It was my fault. I am sorry for that and will take care in future :)


________________________________

**Pull request merged**
