### PR TITLE
 change the location of JFlowBase, EP from data and EP resolutions

### PR DESCRIPTION
**Pull request by dongjokim**

### CODE REVIEW

**Comment by dongjokim** [comment]
Forgotten to be merged today? Any problem?

**Comment by akubera** [comment]
+1

**Comment by dongjokim** [comment]
it is strange, i was able to run and test went ok with the code even with my mac laptop.
Let me see if i can reproduce the error with the linux machine. If someone know the fix, let me know.

Regards,

DJ

**Comment by dongjokim** [comment]
Hi, again

I was able to reproduce the problem in the other machine, module dependences are solved now.
It looks all OK to me, can you test it again and merge if it is ok asap

Cheers,
DJ

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
+1

**Pull request merged**
