### PR TITLE
Fleshed out documentation generation a bit more.

### PR DESCRIPTION
**Pull request by cholmcc**
- Create tag file
- Use AliROOT tag file
- Added some more sources and excludes
- Install tag file for use by others
- Added custom stylesheet to make the look and feel
  more ALICE like (according to charter) - see as
  an example

     http://alice-rivet.cern.ch

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @cholmcc, please factor out the addition of `PWGLF` documentation from all the rest.

**Comment by cholmcc** [comment]
Hi Dario, 

Not sure what you mean by your comment?  The only PWGLF stuff is inclusion (and exclusion) of some inputs - relatively small thing.  Do you mean you want this is a separate patch?  That seems like an awful lot of work for barely no change.  

Yours,

Christian

**Comment by dberzano** [comment]
Hi @cholmcc, we care about including your doc, not refactoring its style. If you care about your doc, please make a separate PR with only the list of files to be considered by Doxygen. I am closing this one as changing the doc's style was by no means discussed anywhere.

**Comment by cholmcc** [comment]
Other than it makes the thing look far better and also conform to the "corporate identity" - I don't see why not?

**Comment by dberzano** [comment]
Your PR changed lots of small things (_e.g._ the Doxygen compilation options) other than the style. It also adds a new stylesheet with a font outside our servers (can you guarantee it will be there in 10 years?)

Such changes need testing, we just don't have time for that now I am afraid.

**Comment by cholmcc** [comment]
As for the font - yes.  It is provided by Google so it is probably more stable than anything ALICE will ever set up (vis-a-vis the past years changes to build system, repository, not to mention web-pages, etc.). 

The other changes to the options is to help people get their documentation right.  E.g., warn if a parameter isn't defined or some parameter is wrongly documented. 

More so, it allows us to link the AliPhysics documentation to the AliROOT documentation so that we may jump from one to the other seamlessly - a very _very_ useful thing.  

I don't know if you use some CI to build the docs - but for my little project at 

  https://gitlab.com/cholmcc/GraphSysErr 

I use the Gitlab CI to build the doxygen documentation. In my CI script I pull the `ROOT.tag` file from 
  
  https://root.cern.ch/doc/master/ROOT.tag

so that the documentation of that project is linked to the ROOT documentation.  Similar could be done for both AliROOT and AliPhysics - which would really help the users. 

Christian

**Pull request closed without merging**
