### PR TITLE
PWG/ doxygen additions for NanoAOD code

### PR DESCRIPTION
**Pull request by mikesas**

### CODE REVIEW

**Comment by bdoenigu** [comment]
+1

**Comment by mikesas** [comment]
@bdoenigu , Thanks for the +1 earlier, but due to a build error of ROOT on that day the merge did not happen - could you perhaps +1 again? Thanks a lot. Mike

**Comment by bdoenigu** [comment]
+1

**Comment by mfasDa** [comment]
+1 (for EMCAL part)

**Comment by nschmidtALICE** [comment]
+1 (for GammaConv part)

**Pull request merged**
