### PR TITLE
including AliAnalysisTask_JPsi_EMCal on CMakeLists.txt

### PR DESCRIPTION
**Pull request by crisjahnke**

### CODE REVIEW

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+test

**Comment by miweberSMI** [comment]
Hi @dberzano, @ktf,

I don't understand why the test is failing, the log seems to be empty?

Thanks and cheers,
Michael

**Comment by miweberSMI** [comment]
+test

**Comment by ktf** [comment]
+test

**Comment by miweberSMI** [comment]
+1

**Pull request merged**
