### PR TITLE
move TestCPV from protected to public

### PR DESCRIPTION
**Pull request by dsekihat**
This modification allows to use TestCPV function from external codes.
This will simplify to compute distance between a cluster and a track in mixed event.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello,

Why did you change the ClassDef? Is it needed in this case?

Chiara

**Comment by kharlov** [comment]
+1

**Comment by dsekihat** [comment]
Thank you for your comments.
I changed ClassDef 9->8.

**Comment by peressounko** [comment]
+1

**Pull request merged**
