### PR TITLE
removed old stuff + addition of selectable cut on momentum

### PR DESCRIPTION
**Pull request by iravasen**
Old pieces of code removed since used only for internal checks. New cut on momentum to explore improvements in the Xe-Xe analysis

### CODE REVIEW

**Comment by njacazio** [comment]
+1

**Comment by iravasen** [comment]
Dear @ktf, I cannot see the log of root6 build. I can compile the code with root6 on my machine and hence it's not clear to me why the check on root6 is failing.

**Comment by njacazio** [comment]
+1

**Comment by ktf** [comment]
The issue comes from an upstream repository, hosted at CERN, whose availability flip/flops. I will now move it to github, hoping for better reliability.

**Comment by iravasen** [comment]
Thanks a lot, any action from my side needed?

**Comment by ktf** [comment]
+1

**Comment by iravasen** [comment]
Hello @ktf, probably your last modification didn't work because I see the PR still stuck :-(

**Pull request merged**
