### PR TITLE
a test for github

### PR DESCRIPTION
**Pull request by arossi81**

### CODE REVIEW

**Comment by arossi81** [comment]
+1

**Comment by arossi81** [comment]
+test

**Comment by ktf** [comment]
@dberzano i think @arossi spotted a bug...

**Comment by dberzano** [comment]
It's @arossi81 ;-)

I am looking into it.

**Comment by arossi81** [comment]
Thanks! I have not reported in the JIRA ticket since yesterday night was too late and I am not sure whether this is a bug or my mistake. My understanding is that the problem could be originated by the fact that I did a pull request on a code that had still to be merged. However, it seems that the two approval processes were somehow put together, which is not clear that this is the expected feature (but I admit I could be completely misinterpreting it).
Andrea

**Comment by dberzano** [comment]
It's a bug on our side, you did all fine, I am checking it.

**Comment by dberzano** [comment]
OK @arossi81 the fixed checker now spots such a case and warns you of the mistake you've made. Thanks again for triggering this unknown problem!

**Comment by arossi81** [comment]
Hi @dberzano , thanks for the fix! This was anyhow a test, so I will close now the pull request.

**Comment by jgrosseo** [comment]
Well done @arossi81 :-)

**Pull request closed without merging**
