### PR TITLE
Fix macOS compilation

### PR DESCRIPTION
**Pull request by raymondEhlers**
I still have a problem with "PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx", which I noted in the #2851

### CODE REVIEW

**Comment by mazimm** [comment]
I committed another fix suggested by @mfasDa. You can see it here. It will be merged soon. 

https://github.com/alisw/AliPhysics/pull/2863

**Comment by mazimm** [comment]
+test the other fix failed the last validation, so we can use this one. I cannot test this locally because I use only ROOT 5.

**Comment by mazimm** [comment]
+1

**Comment by raymondEhlers** [comment]
Thanks for the quick fixes! These combined with deleting my AliPhysics build directory and starting from scratch seemed to resolve the problems that I was experiencing.

**Pull request merged**
