### PR TITLE
Change AliAnalysisTaskRawJetWithEP.cxx to add Q2 recentering histogra…

### PR DESCRIPTION
**Pull request by 11kumaoka**
…ms. And modify some mis assign variables.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
You didn't merge successfully - this won't compile. You can look at your proposed changes here: https://github.com/alisw/AliPhysics/pull/21655/files

**Comment by 11kumaoka** [comment]
Thank you for telling me that. I understood the reason. Using "git rebase" added redundant lines.

**Comment by raymondEhlers** [comment]
+1

**Comment by raymondEhlers** [comment]
+1

**Pull request closed without merging**
