### PR TITLE
EMCal Embedding Framework

### PR DESCRIPTION
**Pull request by raymondEhlers**
Commits the first version of the new EMCal Embedding Framework. Extensive testing has been performed to ensure that all changes are transparent to all users! Further details can be found at [ALPHY-53](https://alice.its.cern.ch/jira/browse/ALPHY-53).

### CODE REVIEW

**Comment by raymondEhlers** [comment]
cc @aiola

**Comment by dberzano** [comment]
+test

@raymondEhlers for the record this PR asks for the admins approval because you've changed more than 10 files

**Comment by dberzano** [comment]
Alright, it seems our pull requests checker has prevented some error from being merged! Please fix.

**Comment by raymondEhlers** [comment]
Hi Dario,

Thanks for the explanation of needing further approval for more than 10 files. Would it possible for the system to note the reason in such a case? Initially, I was quite concerned that it was triggered because I somehow modified additional files beyond those I intended (or made some other mistake).

This error is a bit curious, as I don't see the warnings (effc++) at all with clang. However, I think I see what needs to be done, so I've tried to resolve it and pushed to my branch. Can you please run the test again to check?

Best,
Raymond

**Comment by dberzano** [comment]
+test

Il 24/Mar/2017 14:29, "ALICE Builder" <notifications@github.com> ha scritto:

**Comment by dberzano** [comment]
@raymondEhlers I agree that a notification would be useful in such a case, will do.

**Comment by raymondEhlers** [comment]
Thanks Dario!

Humm, I seem to be caught on another error that I'm again not seeing with clang. I guess I'll try to set it up on a linux system so I can see the errors from gcc. It's a bit frustrating that the compiler warnings and errors are so different

**Comment by dberzano** [comment]
Haha that's why we have implemented the PR checks! :-)

**Comment by raymondEhlers** [comment]
Okay, I successfully compiled on gcc, so let's try one more time!

**Comment by ktf** [comment]
+test

**Comment by dberzano** [comment]
+1

**Pull request merged**
