### PR TITLE
Add weight for systematic study of MC pt shape

### PR DESCRIPTION
**Pull request by zhujh126**
Add weight for systematic study of MC pt shape

### CODE REVIEW

**Comment by fprino** [comment]
+1

**Comment by gluparel** [comment]
Hello  @davidrohr, @jgrosseo, @shahor02, @qgp,
I see that there is no people from HF that can give the +1 to my commit?
How is this possible? 

Could you please give the +1 after approval of the PWG conveners @adubla or PAG coordinators @cterrevo @fgrosa ? Or one of the persons that usually approve the HF requests?

Many thanks!
Grazia

**Comment by davidrohr** [comment]
@ktf : Something seems to be wrong with the permissions I assume?

**Comment by davidrohr** [comment]
+test

**Comment by gluparel** [comment]
Sorry I commented in the wrong pull request: my request is this one https://github.com/alisw/AliPhysics/pull/14123 but it has the same problem. Could you @davidrohr, @jgrosseo, @shahor02, @qgp start the test?
Thanks!

In addition: could you please let me know who we have to contact to fix permissions? all the PWGHF seems to have this problems.

Grazia

**Comment by cterrevo** [comment]
Thanks @davidrohr, could you also give +1? 
thanks, 
Cristina

**Comment by qgp** [comment]
+1

**Pull request merged**
