### PR TITLE
Separate correlation calculator(Generic framework) from AliAnalysisTaskNonLinearFlow

### PR DESCRIPTION
**Pull request by zhaomr13**
Separate correlation calculator(Generic framework) from AliAnalysisTaskNonLinearFlow, so that it can be reused in many code and maintained together.

### CODE REVIEW

**Comment by aohlson** [comment]
+test

**Comment by yzhouCERN** [comment]
+test

**Comment by yzhouCERN** [comment]
+1

**Comment by yzhouCERN** [comment]
+1

**Pull request merged**
