### PR TITLE
adding the AddTask as a static member of the shapes task to run on sa…

### PR DESCRIPTION
**Pull request by lcunquei**
…lvatores on-the-fly powheg framework

### CODE REVIEW

**Comment by lcunquei** [comment]
+test

**Comment by lcunquei** [comment]
+test

**Comment by mfasDa** [comment]
Hi @lcunquei,

where is your implementation? You only committed a function definition, like this you create an undefined symbol.

Cheers

Markus

**Comment by lcunquei** [comment]
Hi @mfasDa 
:-)  I forgot to add the implementation, thanks

**Comment by lcunquei** [comment]
+test

**Comment by lcunquei** [comment]
+1

**Pull request merged**
