### PR TITLE
Update analysis task

### PR DESCRIPTION
**Pull request by eumaka**

### CODE REVIEW

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
+1

**Comment by eumaka** [comment]
@vpacik thanks so much for approving the PR. Have you any idea what is holding the completion of the checks after I fixed the previous errors?

**Comment by vpacik** [comment]
@eumaka Hi, new changes have pass 'release' compilation so it seems fine (not crushing it). 
ROOT6 is still going, sometimes it takes longer which I guess is due to high number of checks going on (and perhaps depends on the changes, but not sure how exactly if so). Just have to wait a bit I guess.

**Pull request merged**
