### PR TITLE
Add possibility to zoom crowded pads

### PR DESCRIPTION
**Pull request by dstocco**

### CODE REVIEW

**Comment by dstocco** [comment]
+test

**Comment by dstocco** [comment]
Hi @dberzano ,
there is something strange with the building of this commit. I tested that it compiles locally before asking for the pull request. I have just re-tested it as a cross-check, and it still compiles locally (on Mac).
I tried to access the logs, but I get error 404. Is there a way to access the full logs? (or of re-forcing another test?)

Thanks in advance,
best regards,
Diego

**Comment by dberzano** [comment]
Hi @dstocco, in spite of what the [status page](https://status.github.com/) says, GitHub is effectively behaving badly. Ignore the error, it's due to GitHub, and it will clear out automatically at some point.

**Comment by dstocco** [comment]
HI @dberzano ,
ok, thanks for the info: I'll wait!
Ciao,
Diego

**Pull request merged**
