### PR TITLE
Change AliVEvent::EOfflineTriggerTypes to ULong64 

### PR DESCRIPTION
**Pull request by fgrosa**
Modification that allows the selection of more trigger masks at the same time (i.e. kINT7 | kCentral)

### CODE REVIEW

**Comment by afestant** [comment]
+1

**Comment by jezwilkinson** [comment]
Hi @dberzano ,  the test seems to be failing with this odd " fatal error: AliNanoAODTrackMapping.h: No such file or directory" error that was reported on the operations list yesterday, although tests on other PRs seem to have been working. Is there any chance that this can be worked around so that this commit can still make it onto today's tag?
Thanks,
--Jeremy

**Comment by ktf** [comment]
It should eventually catch up with the changes in AliRoot.

**Comment by jgrosseo** [comment]
Are we sure the field in the aod has 64 bit?

**Comment by fgrosa** [comment]
Yes it should be 64 but. It is defined as a ULongt64_t also in the other HF code (see e.g. https://github.com/alisw/AliPhysics/blob/339bb675bd92127c1777306c10c4f0e1b9000752/PWGHF/vertexingHF/AliRDHFCuts.h#L439)

**Pull request merged**
