### PR TITLE
PWGCF: Updates & fixes to femto CutAttr structs

### PR DESCRIPTION
**Pull request by akubera**
Fixes documentation and average-separation calculation

### CODE REVIEW

**Comment by akubera** [comment]
@alibuild review

**Comment by akubera** [comment]
well that's too bad

**Comment by akubera** [comment]
why is it building ROOT? Does it not used cached docker images?

**Comment by akubera** [comment]
+1

**Comment by dberzano** [comment]
@akubera fyi it uses cached builds (and builds happen in Docker containers, but this is unrelated: we don't have anything like "cached Docker images"), but something has to populate the cache. I had to empty the caches for several reasons and it happened that it was up to this PR to rebuild it (for all the others). The failure on ROOT was obviously temporary and not your fault. Your PR is going to be merged soon and the daily is about to start.

**Comment by akubera** [comment]
Ah, I see, thanks.

**Pull request merged**
