### PR TITLE
Fixed axis ranges 

### PR DESCRIPTION
**Pull request by haandrew**
Apologies for secondary commit. Modified axis ranges of Lund diagrams.

### CODE REVIEW

**Comment by mfasDa** [comment]
Hi @haandrew,

Could you please squash the two commits into 1?

Thanks!

Cheers

Markus

**Comment by haandrew** [comment]
Hi @mfasDa ,

Sorry yep I didn't drop the other commits when I squashed. Should be sorted now! 

Many thanks!

**Comment by haandrew** [comment]
Hi @mfasDa can this be approve now please?

**Comment by mfasDa** [comment]
Hi @haandrew,

there is still the merge commit which needs to be removed - have a look at the commits!

Cheers

Markus

**Comment by haandrew** [comment]
Hi @mfasDa, I think this is because there were conflicts when I squashed the commits. I don't know if I can remove this merge?

**Pull request closed without merging**
