### PR TITLE
[PWGUD/UPC]: Add task for four prong analysis

### PR DESCRIPTION
**Pull request by bdrum**
Hi

I would like to use lego trains for my analysis, so I've prepared my tasks for it.

### CODE REVIEW

**Comment by mbroz84** [comment]
Hi Boris, please add you task to the PWGUDupc library. This concerns files  CMakeLists.txt and PWGUDupcLinkDef.h in UPC folder. Check in there how is it done for other tasks.

**Comment by bdrum** [comment]
Hi, Michal, sorry about that, I used cmake and cpp relatively long time ago and completely forgot about that...

Unfortunately I can't build AliPhysics, because of 

~~~bash
Error: 29/home/bdrum/apps/alice/sw/ubuntu1804_x86-64/ROOT/v6-20-02-alice3-1/bin/rootcint: compilation failure (/mnt/d/GoogleDrive/Job/cern/Alice/analysis/dev/testbld/PWGCF/Correlations/JCORRAN/Pro/G__PWGCFCorrelationsJCORRANPro39c22e4c3a_dictUmbrella.h)
: field 'fCollisionSystem' will be initialized after field 'fClassifierValueIsCached' [-Wreorder-ctor]PWGCF/Correlations/JCORRAN/Pro/CMakeFiles/PWGCFCorrelationsJCORRANPro-object.dir/build.make:101: recipe for target 'PWGCF/Correlations/JCORRAN/Pro/libPWGCFCorrelationsJCORRANPro.rootmap' failed
make[2]: *** [PWGCF/Correlations/JCORRAN/Pro/libPWGCFCorrelationsJCORRANPro.rootmap] Error 1

CMakeFiles/Makefile2:5676: recipe for target 'PWGCF/Correlations/JCORRAN/Pro/CMakeFiles/PWGCFCorrelationsJCORRANPro-object.dir/all' failed
warning    fCollisionSystem(collisionSystem),make[1]: *** [PWGCF/Correlations/JCORRAN/Pro/CMakeFiles/PWGCFCorrelationsJCORRANPro-object.dir/all] Error 2
:
make[1]: *** Waiting for unfinished jobs....
~~~

I hope the reason in some of my environments settings and in testing machine it will be fine, if not I suppose we will see it and in this case I will investigate this.

Thanks!

**Comment by mbroz84** [comment]
+1

**Comment by mbroz84** [comment]
+1

**Pull request merged**
