### PR TITLE
Update AliAnalysisTaskPIDBFDptDpt.cxx

### PR DESCRIPTION
**Pull request by panjinjin**
added multiplicity selection

### CODE REVIEW

**Comment by ktf** [comment]
+test

**Comment by rbertens** [comment]
Hi Jinjin,

Your pull request cannot be processed, because the code does not compile. I think you have made independent pull requests for both your .cxx and .h file. Instead, you have to make a pull request for both files *together* (the .cxx doesn't compile without the .h, and vice versa). So:

cd ~/alice/AliPhysics
git add AliAnalysisTaskPIDBFDptDpt.h
git add AliAnalysisTaskPIDBFDptDpt.cxx
git commit
git push <your-github-username>

and then make the pull request. 

Hope it helps,
Redmer

**Comment by panjinjin** [comment]
Hi, @rbertens ! Thank you very much for the information! Yeah, I should have make #232 #233 #234 a single pull request. However, I haven't figure it out how to do that using this graphical interface. Could you please tell me how to do it? Thank you very much!

**Comment by rbertens** [comment]
Hi @panjinjin ,
@dberzano explained in a comment on one of your other pull requests ( #234 ) how to do this. Please write if you get stuck!

**Pull request closed without merging**
