### PR TITLE
Some methods to work without top. selections added

### PR DESCRIPTION
**Pull request by mfaggin**
- method to switch off the topological selections added
 - method to switch off als othe PID selection after filtering added
 - method to reject events without at least one identified proton, one identified kaon and one identified pion added, to spare CPU time

### CODE REVIEW

**Comment by mfaggin** [comment]
@arossi81 here the updates we were thinking about. Please have a look at them.

**Comment by arossi81** [comment]
Hi @mfaggin ,
for the rejection of the event in case no tracks is identified as a proton (or pi or K), you should do the OR rather than the AND.
Cheers,
Andrea

**Comment by mfaggin** [comment]
Hi @arossi81,
thanks for spotting it. Now it should be ok.
Best regards.
Mattia

**Comment by fgrosa** [comment]
+1

**Pull request merged**
