### PR TITLE
add code for syst study of PID and track efficiency

### PR DESCRIPTION
**Pull request by gluparel**

### CODE REVIEW

**Comment by gluparel** [comment]
Modify analysis task in order to study systematic errors

**Comment by gluparel** [comment]
Hello @davidrohr, @jgrosseo, @shahor02, @qgp,
could you please start the test for this request?
Thanks
Grazia

**Comment by davidrohr** [comment]
+test

**Comment by gluparel** [comment]
Hello @davidrohr,
could you please also give +1?
Many thanks!
Grazia

**Comment by davidrohr** [comment]
+1

**Pull request merged**
