### PR TITLE
Add New task to plot raw jet pt spectrums

### PR DESCRIPTION
**Pull request by 11kumaoka**
I want to add a new task to plot raw jet pT spectrum into AliPhysics/PWGJE/EMCALJetTasks/UserTasks/ .
@jdmuligan

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+1 Looks good! Thanks for updating it (You'll probably need to add you task to the LinkDef, but I'll just commit for now)

**Comment by mfasDa** [comment]
Sorry, why do we need yet another task to plot a raw spectrum? There are plenty of tasks already in AliPhysics. No need for yet another one ...

**Comment by 11kumaoka** [comment]
Thank you for giving me a comment.
1. I want to plot them for each 10% centrality.
The existing task has only the centrality divided by 0-10, 10-30, 30-50, 50-.
2. For making smaller the output file, I need only the raw jet spectrum.

**Comment by mfasDa** [comment]
For the purpose you could also use my task PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum and run one task per centrality percentile. The additional QA histograms you will have to tolerate but they don't make the output extremely big.

**Comment by raymondEhlers** [comment]
Note that you can also pass a fixed width centrality binning with methods in AliAnalysisTaskEmcal (although I can't say how well it's maintained):

```c++
task->SetCentRange(0, 100);
task->SetCentNBins(10);
```

**Comment by 11kumaoka** [comment]
Mr. Markus, Mr. Raymond, 
Thank you so much for telling me the way to plot the raw jet pT spectrum by each centrality.
On the other hand, I want pT subtracted rho (background pT).
Therefore, for the time being, I will close this PR, and again I am going to PR that I add the information of pT into 
 AliAnalysisTaskEmcalJetEnergySpectrum.

**Pull request closed without merging**
