### PR TITLE
JetPerformance: allow to use jettagger for geometrical matching

### PR DESCRIPTION
**Pull request by jdmulligan**
(without mc fraction requirement)

Update to my user task.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+1 I'm sure that you already know this, but just as a reminder, I don't think we've sorted out the grid issues when embedding (although Jamie's trains have been successful so far, so maybe it's okay?)

**Comment by jdmulligan** [comment]
Hi @raymondEhlers,

Yea, I'm going to run a since train to try it again -- this time the configuration will be a bit different, since I won't use MC fraction matching. The whole reason I make this change is that I realized the response maker actually doesn't apply the jet container cuts when doing the matching...which can create some problems, particularly when using embedding.

**Comment by raymondEhlers** [comment]
Ah, yeah, that's right. I guess this means it did the matching without the leading track bias, right?

**Comment by jdmulligan** [comment]
Yea -- I noticed some small changes in the efficiency after changing the minPt thresholds on the jet finders, which led me to dig back into this...the design is pretty confusing, the ResponseMaker AddTask takes all this container information like the leading track bias, but doesn't actually use it for the matching...

**Comment by raymondEhlers** [comment]
That's a good catch, and not an ideal design for the response maker. I guess we should just recommend the tagger if we can get it working consistently with embedding. In any case, I guess I'll need to re-run my RM too, so I'll eagerly await the results of your tests!

**Pull request merged**
