### PR TITLE
Possibility to convert Run1/2 AOD to AO2D (second attempt)

### PR DESCRIPTION
**Pull request by pzhristov**

### CODE REVIEW

**Comment by pzhristov** [comment]
+test

**Comment by pzhristov** [comment]
@ktf @TimoWilken Apparently we still do not use the latest AliRoot tag on the CI.

**Comment by TimoWilken** [comment]
That's odd. According to https://github.com/alisw/alidist/blob/master/aliroot.sh, we already use AliRoot's master branch in CI. Which tag is the fix in?

**Comment by pzhristov** [comment]
@TimoWilken It should work with v5-09-57d-01

**Comment by pzhristov** [comment]
It seems the two builds use different AliRoot: build/AliPhysics/root6 stays with an old tag, while build/AliPhysics/release uses the master or v5-09-57d-01.

**Comment by pzhristov** [comment]
+test

**Comment by pzhristov** [comment]
+1

**Comment by pzhristov** [comment]
+1

**Pull request merged**
