### PR TITLE
My new feature

### PR DESCRIPTION
**Pull request by panjinjin**
pull request

### CODE REVIEW

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
Hi  @panjinjin 
I tested your patch, but compilation fails with a missing header. Probably you need to add OADB as an include folder in the CMakeLists ? (but that's just a suggestion after a very quick look)

**Comment by aohlson** [comment]
Hi @panjinjin 
Is there a reason that you switched from using AliMultSelection to AliPPVsMultUtils?  In principle AliMultSelection should contain the functionality of AliPPVsMultUtils, and AliMultSelection is already included/loaded in the PWGCFCorrelationsDPhi, so I'm curious if there's something missing from AliMultSelection which caused you to change to the older AliPPVsMultUtils.

**Comment by dberzano** [comment]
@panjinjin maybe make the PR title concise&descriptive :-)

**Pull request closed without merging**
