### PR TITLE
PWGHF: Fix HFSimpleVertices

### PR DESCRIPTION
**Pull request by vkucera**
- Fix binning, acceptance cut, Lc MC
- Fix info messages
- Fix compilation errors
- Format with `clang-format`

### CODE REVIEW

**Comment by vkucera** [comment]
> @vkucera Dear Vit, thanks a lot for the update, could you please update the ClassDef (+1) as well? Thanks a lot!

Done

**Comment by xinyepeng** [comment]
+1

**Comment by vkucera** [comment]
> +1

Thanks @xinyepeng . Why is the check still reporting a missing review though?

**Comment by lvermunt** [comment]
+1

**Pull request merged**
