### PR TITLE
Add support for LHC20k1

### PR DESCRIPTION
**Pull request by mfasDa**
LHC20k1: Herwig, pp 13 TeV, 20 pt-hard bins,
anchored to LHC17h-r, configiured as HepMC
pt-hard dataset

### CODE REVIEW

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
@ktf The build fails but the logs are empty. Any chance to figure out what is going on (and get this merged into today's tag)?

**Comment by ktf** [comment]
@TimoWilken could you check if this is DPMJET having troubles? Also could you check build/AliPhysics/root6?

**Comment by TimoWilken** [comment]
@ktf: Yes, the build/AliPhysics/release error is DPMJET.

build/AliPhysics/root6 has started now, the PR was probably just submitted while the worker was at in a long queue.

**Pull request merged**
