### PR TITLE
PWGGA: Change of PHOS Tender

### PR DESCRIPTION
**Pull request by jluehder**
Triggered BC map of PHOS grp has different main directory name in .root file

### CODE REVIEW

**Comment by dmuhlhei** [comment]
+1

**Comment by peressounko** [comment]
Goal of commit not clear. No physics case to put trigger bad map into readout bad map. To be clarified

**Comment by chiarazampolli** [comment]
Hello @peressounko ,

So we don't approve for now?

Chiara

**Comment by peressounko** [comment]
Hi @chiarazampolli , 
we will chat with Jens then decide. I will approve it necessary. Dmitri

**Pull request closed without merging**
