### PR TITLE
Dalitz total change from ESD to AOD

### PR DESCRIPTION
**Pull request by eddoming**
Dear AliPhysics team,
on the next commit, I add a few extra class, to make a switch between AOD and ESD, and add 4 new functions on the Framework of Friederick, to fully work on the Dalitz way.
Best Regards
Edgar

### CODE REVIEW

**Comment by dberzano** [comment]
+test - sorry for approving tests only; I need to test a change in the PR checks 😄

**Comment by eddoming** [comment]
Dear AliPhysics experts,
I checking and checking, the error that reports for aa227cf, and in the full log is compiled fine, the only thing I believe it can be bad, is the extra line... Everything is ok?

**Comment by nschmidtALICE** [comment]
I am still checking all your changes. As you can see on the PR, "All checks have passed". This means that the compilation error above was not concerning your changes.
Once I have gone through all your changes and additions, i will approve or give feedback here.

**Comment by eddoming** [comment]
Dear Dario and Nico,
A savage error has emerged on the build of root6, for the classes I believe, there is any idea of what could happen, or just errors pf the build?
Regards
Edgar

**Comment by nschmidtALICE** [comment]
+1

**Comment by mfasDa** [comment]
Hi @eddoming, Hi @nschmidtALICE,

The commit creates a compiler error under macOS due to the usage of Werror:

/Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx:1916:18: error: delete called on non-final ‘AliDalitzAODESDMC’ that has virtual
     functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
if (posDaughter) delete posDaughter;
                ^
/Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx:1917:18: error: delete called on non-final ‘AliDalitzAODESDMC’ that has virtual
     functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
if (negDaughter) delete negDaughter;
                ^
/Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx:1918:13: error: delete called on non-final ‘AliDalitzAODESDMC’ that has virtual
     functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
if (Photon) delete Photon;
           ^

Could you please have a look? I assume the constructor in AliDalitzAODESDMC needs to be declared as virtual.

Cheers

Markus

**Pull request merged**
