### PR TITLE
reduce memory to add pt bin for TPC-FMD correlations

### PR DESCRIPTION
**Pull request by ysekiguc**

### CODE REVIEW

**Comment by aohlson** [comment]
+1

**Comment by ysekiguc** [comment]
I forgot to add the header file at the last push. Could you test again?

**Comment by aohlson** [comment]
+1

**Comment by ysekiguc** [comment]
Hi, 

I tried to check the error but nothing is in the log file.
How can I see the error?

Best Regards,
Yuko

**Pull request merged**
