### PR TITLE
added a histo go check overlap of tagged jets

### PR DESCRIPTION
**Pull request by sashingo**

### CODE REVIEW

**Comment by fcolamar** [comment]
Hi Shingo, since you modified the member list of AliAnalysisHFjetTagHFE class, can you also update the ClassDef version number?

**Comment by sashingo** [comment]
Hi Fabio,

I'm not familiar with the number of the ClassDef.
Don you know what is the number for the update ?

regards,
Shingo

**Comment by fcolamar** [comment]
Hi Shingo, it's enough that you update L263 from
ClassDef(AliAnalysisHFjetTagHFE, 7)
to
ClassDef(AliAnalysisHFjetTagHFE, 8)
This has to be done every time a new data member is added to a class
Fabio

**Comment by sashingo** [comment]
Hi Fabio, 

ok, thank you for the information.
Since the local compile was ok and it’s run on Grid, I thought it’s ok.
I will fix and commit again.

regards,
Shingo

**Comment by fcolamar** [comment]
+1

**Pull request merged**
