### PR TITLE
Deep declustering added (iterative Soft Drop)

### PR DESCRIPTION
**Pull request by klapidus**
The Iterative Soft Drop algorithm added to the user task AliAnalysisTaskSoftDrop. New histograms added as well.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+test

**Comment by raymondEhlers** [comment]
+1

**Comment by mfasDa** [comment]
Hi @klapidus , Hi @raymondEhlers 

this pull request breaks compilation under ROOT6. Please, when using classes from the standard library (like std::vector) always put the namespace in front.

Thanks!

Cheers

Markus

**Comment by raymondEhlers** [comment]
Hi @mfasDa ,

Thanks, this a good reminder - I've had to fix this exact issue with a number of other PRs over the last few weeks (but clearly it's easy to miss). Given that ROOT 6 is now recommended on OS X, I think this really points to the need for a ROOT 6 based PR checker.

Best,
Raymond

**Pull request merged**
