### PR TITLE
Modify default protection for AOD-deltaAOD mismatch: switch off TProcessID

### PR DESCRIPTION
**Pull request by fprino**

### CODE REVIEW

**Comment by fprino** [comment]
Dear @ktf, @pzhristov, @davidrohr 

can you please give me a +1 for this PR?
It seems that I cannot approve it, even if I normally have the rights for the PWGHF directory.

Thanks!

Cheers, Francesco

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Maybe it has too many files?

**Comment by ktf** [comment]
+1

**Pull request merged**
