### PR TITLE
PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx small edit to track container name handling.

### PR DESCRIPTION
**Pull request by aschmier**
PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx small edit to track container name handling.

### CODE REVIEW

**Comment by mfasDa** [comment]
This commit allows to use also non-default track containers as input input containers in the jet finder. The behavior for default containers is not affected, but track containers from helper (i.e. selection) tasks can be used as well. The change makes the jet container more flexible and I see no reason not to merge the PR.

**Comment by mfasDa** [comment]
+test

**Comment by raymondEhlers** [comment]
For our future selves, this could cause an issue if the user creates a non-standard track collection name (for example, with filter tracks) that contains "tracks", but is not intended to have the track selection applied (note that apply the track selection twice (ie. once when doing the filtering, and then once later in the jet finder) won't be a problem)

**Comment by aschmier** [comment]
This new commit allows to use also non-default track containers as input containers in the RhoPerpCone and RhoSparse tasks. The behavior for default containers is not affected, but track containers from helper (i.e. selection) tasks can be used as well. The change makes the rho tasks more flexible

**Pull request closed without merging**
