### PR TITLE
AliMCSpectraWeights

### PR DESCRIPTION
**Pull request by phuhnGithub**
First push of class AliMCSpectraWeights to correct for wrong particle composition in MC generators on the fly while running MC trains

### CODE REVIEW

**Comment by mkruegerGitHub** [comment]
+test

**Comment by wiechula** [comment]
+test

**Comment by wiechula** [comment]
+test

**Comment by phuhnGithub** [comment]
Can anyone of the last list please approve my commit?
Thank you very much!

**Pull request closed without merging**
