### PR TITLE
First version of aod skim task for emcal

### PR DESCRIPTION
**Pull request by loizides**
First working version of aod skim task able to run data and MC

### CODE REVIEW

**Comment by loizides** [comment]
+1

**Comment by loizides** [comment]
+test

**Comment by gconesab** [comment]
What is the purpose of this task that is not present  or that could be added to the existing tasks doing AOD/ESD filtering?

**Comment by mfasDa** [comment]
Some more comments:
- Please when opening pull requests squash related commits into one in order to not unnecessarily blow up the history
- Please avoid if(1) within code as this might on some newer platforms raise a warning about a statement with no effect and since EMCAL libraries are build with Werror consequently end in compiler errors. For the purpose obvious from the code just putting code into curled brackets is sufficient for limiting scoping.
Minor:
- LICENSE disclaimer missing (BSD-license)
- ClassDef/ClassImp should be surrounded by /// \cond CLASSIMP and /// \endcond since EMCAL libraries are enabled in doxygen and missing guards result in error messages (which however not stop the doxygen build)

**Pull request merged**
