### PR TITLE
Update of FlavourJetTasks PicoV0 package

### PR DESCRIPTION
**Pull request by xcheung**
- Using features in new EmcalJet framework
- Apply C++11 style in CXX files
- Optimization of data structure
- Improved add task macros

### CODE REVIEW

**Comment by aiola** [comment]
+test
Hello @xcheung, I am not familiar with this part of the code so for the moment I only approved the test. It looks like you did significant changes. From the commit message I gather that nothing changed from the perspective of the analysis but rather it is an update to switch to C++11 and the EMCal jet framework. I assume that you informed the other authors of this code and they have agreed with the changes?
A suggestion for the future: it is better to split the modification into several smaller commits (in a single PR if they are connected). This makes the job easier for the reviewers. Thanks!

**Comment by xcheung** [comment]
Hi @aiola, thanks! Yes the update includes only using C++11 and using new Emcal jet features. I am the only author for the updated code. In additional, I will follow the guid that to split a large commit into several parts for the others can review the changes easily in the future.

**Comment by xcheung** [comment]
@aiola  Hi again. Could you please nicely approve my pull request, if the code was passed the test. Thanks in advance.

**Comment by aiola** [comment]
+1

**Comment by matplo** [comment]
+1

**Comment by matplo** [comment]
Sorry for an extra +1 ;-) I did not see it was merged already...

**Pull request merged**
