### PR TITLE
PWGGA/GammaConv    Creating Task to pair Cluster from different Calorimeters

### PR DESCRIPTION
**Pull request by AMechler**

### CODE REVIEW

**Comment by dmuhlhei** [comment]
+test

**Comment by dmuhlhei** [comment]
There are 2 warnings in the compilation, could you please fix them?

**Comment by AMechler** [comment]
Had to force push the fix, i think because i had another pull request in the meantime.

**Comment by nschmidtALICE** [comment]
+test

**Comment by AMechler** [comment]
Sorry thats not the correct version

**Comment by AMechler** [comment]
OK let my check if i am totally confused or i got the right version now.
Sorry for that Nico

**Comment by nschmidtALICE** [comment]
+test

**Comment by AMechler** [comment]
ok seams to be the right one now

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
