### PR TITLE
add new Task to analyze K+K- in UPC

### PR DESCRIPTION
**Pull request by nacerh**
new task to be run on LEGO train system

### CODE REVIEW

**Comment by mbroz84** [comment]
+1

**Comment by mbroz84** [comment]
Dear Nacer, can you please add the task to the library i.e to the PWGUDupcLinkDef.h and CMakeLists.txt files. This is needed in order to run it on LEGO train.

**Comment by nacerh** [comment]
Hi Michal,

Thank you for the input. I added my task to the Aliphysics, let me know if anything is missing.
So I guess I will need to wait until 2 other collaborators checks before I could submit add a wagon on the grid , is that right ?

Thanks,
Nacer

**Comment by mbroz84** [comment]
Hi Nacer, there is no need for other people to check. Once the other PR is merged it is ready.

**Pull request merged**
