### PR TITLE
Use new trigger clusters in cluster task + namespace + warnings

### PR DESCRIPTION
**Pull request by mfasDa**
- Use common trigger cluster definition from
  AliEmcalTriggerSelectionHelper in cluster task
- Move all classes previously in namespace
  EMCalTriggerPtAnalysis and EmcalTriggerJets
  to PWGJE::EMCALJetTasks
- Fix warnings in classes moved, indicated by
  clang

### CODE REVIEW

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
I should have commit rights to all folders, why can't approve this commit myself? @ktf

**Comment by davidrohr** [comment]
+test

**Comment by davidrohr** [comment]
Started the CI. This seems large, it changes >160 files. So I don't feel qualified to just merge it.

**Comment by mfasDa** [comment]
@davidrohr Thanks! Could you please restart the CI.

The > 160 files is connected with a change of the namespace (from EmcalTriggerJets and EMCalTriggerPtAnalysis to PWGJE::EMCALJetTasks), development was only done in one class (AliAnalysisTaskEmcalClustersRef).

**Comment by davidrohr** [comment]
+test

**Comment by ktf** [comment]
What was the reason for a change this large in AliPhysics?

**Comment by mfasDa** [comment]
@ktf As written above: Merging classes from different namespaces into a single namespace. Only one class has a change of logic, which made access of something in a different namespace.

Changing the namespace must be done in sync for all classes in the old namespace.

These are all my classes, there must be the the possibility to refactor code.

**Comment by ktf** [comment]
Yes, of course, the code is yours. Given the branch is called  `hotfix-clustertask`, I changing the namespace was part of the "hotfix" or just a "rider".

**Comment by ktf** [comment]
Anyways, the code seems to genuinely not compile after your change.

**Comment by ktf** [comment]
+1

**Comment by mfasDa** [comment]
@ktf Thanks for merging! The "hotfix" was indeed part of the "clustertask" and the driver of the commit (moving from some internal prototype copy to a combined helper class used already in several of my tasks, which has features that I need and I wanted to avoid code duplication). As the classes are in different namespaces I felt now is the time to combine the namespaces into a single one.

**Pull request merged**
