### PR TITLE
PWGDQ: Updates for calorimeter cluster handling in dielectron and reducedTree frameworks

### PR DESCRIPTION
**Pull request by laltenka**
- introduced calorimeter cluster cut classes to dielectron and reducedTree frameworks
- added possibility to select on cluster-track matches in  dielectron/core/AliDielectronTrackCuts
- added possibility to select on calorimeter clusters in AliAnalysisTaskReducedTreeMaker
- updated AliReducedAnalysisSingleTrack with calorimeter cluster selection and histograms

### CODE REVIEW

**Comment by iarsene** [comment]
Hi Lucas,
I just started looking over the modified files and I will start listing here my comments.
Cheers, Ionut

**Comment by iarsene** [comment]
For the AliDielectronClusterCuts class, we should also have geters for all the data members.

**Comment by iarsene** [comment]
For AliDielectronTrackCuts I suggest to also add getters for the calo related data members.

**Comment by iarsene** [comment]
In the tree maker, in the function IsCaloClusterSelected(), you apply multiple filters and store the individual decisions in an array of bool, but this does not seem to be used when you decide which cluster to write in the tree. You write all clusters which fulfill at least one of the conditions, so this is an OR between all the filter the user configures in the AddTask. Is this intended like that?

**Comment by iarsene** [comment]
In the jpsi2ee analysis class, you changed the range where the calo related variables are reset. I guess this is an update due to the fact that you added more variables. I think you could had just added those new variables in the VarManager in a different order so that these changes are not needed. Or, even better, we should probably have an extra variable in the VarManager which is called something like kNEMCALvars. This variable would never be used, but we should make sure that all of the calo related vars are defined before this one, such that we do not need to make this kind of updates in the future (or forget to do them).

**Comment by iarsene** [comment]
In AliReducedEventInfo::GetCaloClusterFromID() function you iterate over the list of clusters to find the one with a given ID. I do not know how often you will call this function, but you should improve performance if you use a TIterator to parse the clusters in the TClonesArray.
In addition, if this is going to be really heavy CPU wise, you might want to make a (cluster ID, cluster pointer) map outside of the track loop so that you can go faster between track->clusterID->cluster.

**Comment by laltenka** [comment]
> In the tree maker, in the function IsCaloClusterSelected(), you apply multiple filters and store the individual decisions in an array of bool, but this does not seem to be used when you decide which cluster to write in the tree. You write all clusters which fulfill at least one of the conditions, so this is an OR between all the filter the user configures in the AddTask. Is this intended like that?

Yes, this is intended that way. It's set up just like the track selection in IsTrackSelected(), where the individual filter decisions are also stored but not used at the moment.

**Comment by laltenka** [comment]
> In the jpsi2ee analysis class, you changed the range where the calo related variables are reset. I guess this is an update due to the fact that you added more variables. I think you could had just added those new variables in the VarManager in a different order so that these changes are not needed. Or, even better, we should probably have an extra variable in the VarManager which is called something like kNEMCALvars. This variable would never be used, but we should make sure that all of the calo related vars are defined before this one, such that we do not need to make this kind of updates in the future (or forget to do them).

The variable you refer to in the jpsi task is a "track" quantity and not a calorimeter one since it's only filled after the track matching. I agree that I could have added a flag but in this case, it would not have been kNEMCALvars but one that refers to the track variables. We could implement such a thing but for now I'll leave it be.

**Comment by laltenka** [comment]
> For the AliDielectronClusterCuts class, we should also have geters for all the data members.

> For AliDielectronTrackCuts I suggest to also add getters for the calo related data members.

I added getters.

**Comment by laltenka** [comment]
> In AliReducedEventInfo::GetCaloClusterFromID() function you iterate over the list of clusters to find the one with a given ID. I do not know how often you will call this function, but you should improve performance if you use a TIterator to parse the clusters in the TClonesArray.
> In addition, if this is going to be really heavy CPU wise, you might want to make a (cluster ID, cluster pointer) map outside of the track loop so that you can go faster between track->clusterID->cluster.

I will not touch this on this PR but will try to implement a more efficient method on the next one.

**Comment by iarsene** [comment]
+1

**Pull request merged**
