### PR TITLE
Update of the PS for the LMRdimuon analysis for the Fnorm factor

### PR DESCRIPTION
**Pull request by bteyssie**

### CODE REVIEW

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
@bteyssie I guess you might have to revise the way you test your changes locally...

**Comment by bteyssie** [comment]
@aphecetche yes sorry, for this small modification I have forgotten to test the compilation. I have test for this new fix.

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
+1

**Pull request merged**
