### PR TITLE
new Parameters for 16q MinBias data

### PR DESCRIPTION
**Pull request by jluehder**
I added new Parameters for 16q MB; charge dependency is included in these

### CODE REVIEW

**Comment by jluehder** [comment]
The request is open for 24 days now. Could someone of you approve this, please?

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Dear @jluehder, 
I have approved your pull request. As I understand you worked on this with Yvonne, I guess you verified with her the content of the file - I cannot judge it.

Regards,

Chiara

**Comment by jluehder** [comment]
Hello,
Yes, i worked on this with Yvonne and  I verified the file. Thank you.
Best Regards Jens

Am 17. November 2017 16:05:06 MEZ schrieb chiarazampolli <notifications@github.com>:
>Dear @jluehder, 
>I have approved your pull request. As I understand you worked on this
>with Yvonne, I guess you verified with her the content of the file - I
>cannot judge it.
>
>Regards,
>
>Chiara
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/alisw/AliPhysics/pull/3010#issuecomment-345268083

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
