### PR TITLE
Remove FATAL condition in case ALIEN is not set

### PR DESCRIPTION
**Pull request by mfasDa**
FATAL condition makes it impossible to compile AliPhysics
with the o2 defaults which deactivate alien. Configuration
of ALIEN should be handled by the build recipe.

### CODE REVIEW

**Comment by mfasDa** [comment]
@ktf @Atlantic777 Please review! The FATAL_ERROR condition makes it impossible to compile AliPhysics with o2 defaults as alien is not built in this case. It will also make compilation without Alien in general impossible, where building without alien might be a desirable feature on certain systems without outgoing network support. The FATAL is also not really needed as the alien settings are handled in any case by the build recipes, and for the release or root6 defaults the AliEn-Legacy-ROOT plugin is built in any case.

**Comment by sawenzel** [comment]
I agree. I think it is beneficial to be able to compile AliPhysics together with O2.

**Comment by mfasDa** [comment]
Any update on this issue?

**Comment by sawenzel** [comment]
+test

**Comment by sawenzel** [comment]
@mfasDa : The git diff shows many changes lines not related to this PR. Could you just change the one particular line?

**Comment by mfasDa** [comment]
@sawenzel I also fixed the code indentation in order to make the cmake file more readable. I would still prefer to fix this as well, but I could try to split the change to two separate commits, handled in the same pull request - is this fine with you?

**Comment by sawenzel** [comment]
Ok, if you wish.

**Comment by sawenzel** [comment]
+test

**Comment by mfasDa** [comment]
@sawenzel, OK, I extracted the code indentation in the ALIEN if-block into a separate commit. The original one (https://github.com/alisw/AliPhysics/pull/10584/commits/2c6ebae8d9b1fc62840e44546db68a0810b608ec) now only contains the FATAL condition blocking builds without ALIEN (i.e. using the o2 defaults).

**Comment by sawenzel** [comment]
Merging this (there is no opposing argument and it seems to be a useful change).

**Comment by sawenzel** [comment]
+1

**Pull request merged**
