### PR TITLE
PWG/Cocktail: added pp params for 2.76TeV & 900 GeV

### PR DESCRIPTION
**Pull request by FriederikeBock**

### CODE REVIEW

**Comment by nschmidtALICE** [comment]
+1

**Comment by aaniin** [comment]
Hello @FriederikeBock , @nschmidtALICE ,

With 11MB, this is a rather large file. I thought we have the policy to use the OADB. See http://alisw.github.io/git-advanced/ How to use large data files for analysis
@dberzano Can you remind us of the policy here?

Cheers,
Hans

**Comment by FriederikeBock** [comment]
Hi @aaniin ,
sorry for this I didn't realize that this file was so big now, but I am also not entirely sure how to fix this now. I could only decrease the size for the next iteration. @dberzano  any suggestions?
Regards,
Friederike

**Comment by dberzano** [comment]
Hello @aaniin, see section "How to use large data files for analysis" on the very page you have linked tells you how to deal with such large files. It might be good practice to follow what the guide says for large files, but @FriederikeBock did not violate any policy: our limit (20 MB per PR) is enforced, so the PR would have been rejected automatically in case it went against the rules.

If you want to play nice with the repository size, please make a PR that removes this file, and copy it under the following directory on lxplus:

```
/eos/experiment/alice/analysis-data/PWG
```

You will need to create the directory structure. Note that every user in egroup `alice-svn-pwg` will be able to store files there, so if you are not in that egroup you might want to ask the admins to be added.

**Pull request merged**
