### PR TITLE
Reduction of tree size & implementation of multiplicity in Lc->pK0 TMVA task

### PR DESCRIPTION
**Pull request by jezwilkinson**
Removal of some redundant variables from Lc2V0bachelorTMVA analysis task. Also adds multiplicity determination/correction with Ntrk10 estimator to the task (methods ported from AliAnalysisTaskSEDvsMultiplicity).

### CODE REVIEW

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+1

**Comment by dberzano** [comment]
Ignore the error. Temporary problem.

**Comment by ebruna** [comment]
+1

**Pull request merged**
