### PR TITLE
new test to check approval rights for HF conveners

### PR DESCRIPTION
**Pull request by ycorrales**

### CODE REVIEW

**Comment by dberzano** [comment]
test me

**Comment by dberzano** [comment]
@arossi81 you should comment the _pull request_, not the _commit_. The automatic checker is not seeing your comment because of this.

**Comment by ebruna** [comment]
+1

**Comment by arossi81** [comment]
Thanks @dberzano , though I do not know how I managed to comment on the comment, trying to figure it out

**Comment by dberzano** [comment]
You're the perfect beta tester 👍

**Comment by arossi81** [comment]
... like a monkey! :D

**Comment by ycorrales** [comment]
Actually, it will be a often mistake, approver will go to the commit page to check the diff patch  and automatically will comment in it. That's why a period of test is need it.

**Pull request merged**
