### PR TITLE
Merge hltdev into master (AliPhysics part)

### PR DESCRIPTION
**Pull request by davidrohr**
This patch requres the new AliRoot, so I suggest we move it into master the moment we create the new AliRoot tag.

### CODE REVIEW

**Comment by shahor02** [comment]
+test
Test only to not break daily tag

**Comment by dberzano** [comment]
For the record: I have changed the PR tests for AliPhysics to build against the latest AliRoot tag (and not master, as we did before). This PR is expected to fail as the corresponding changes in AliRoot are not yet in v5-09-20. We will merge it manually.

**Comment by dberzano** [comment]
(Note that it's pointless to approve tests or merge, since as pointed out already they will fail as they use the AliRoot tag, not master.)

**Comment by dberzano** [comment]
In order not to break current daily tags, this branch has been temporarily merged to `rc/v5-09-21-01` and its tip has been tagged as `v5-09-21-01-rc1`. Build and validation include the changes from this PR. When validation appears OK, this PR will be merged.

**Comment by mkrzewic** [comment]
I have a first candidate for the fix discussed in ALIROOT-7626, after verification i'll push here. Fix also depends on alisw/AliRoot #524

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
Note that AliRoot has been tagged to v5-09-21. AliPhysics hasn't been tagged yet, but tests now use v5-09-21 as a base, so this PR should turn green and be merged automatically as a consequence. As soon as this is done, AliPhysics v5-09-21-01 will be tagged too.

Thanks for your work!

**Pull request merged**
