### PR TITLE
Xic0 semileptonic updates

### PR DESCRIPTION
**Pull request by Chongk**
Minor updates for systematic error check

### CODE REVIEW

**Comment by fgrosa** [comment]
Hi @Chongk! Are the changes in `PWGMM/Lumi` intended? From your description I assumed this PR was about Xic0 systematic uncertainties.

**Comment by Chongk** [comment]
Oops...! Yes, Fabrizio. This is for Xic0 analysis at PWGHF. Thank you for your attention.
(Sorry for PWGMM people!)

**Comment by fgrosa** [comment]
+1

**Comment by fgrosa** [comment]
> Oops...! Yes, Fabrizio. This is for Xic0 analysis at PWGHF. Thank you for your attention. (Sorry for PWGMM people!)
> 
>     * Update:
>       Sorry again. Now I remember I pushed some updates for PGWMM/Lumi group a while ago.
>       I have been forgotten about it completely... It seems all the updates are now being pushed together.
> 
> 
> The updates are in fact two:
> 
>     1. PWGMM/Lumi - vdM analysis
> 
>     2. PWGHF - Xic0 semileptonic
> 
> 
> Is it possible I can request to merge all these updates simultaneously? I believe both updates won't cause any problem.

Hi @Chongk thanks for the clarification! I am approving the part regarding the D2H analysis.

**Comment by valzacc** [comment]
+test

**Comment by valzacc** [comment]
+1

**Pull request merged**
