### PR TITLE
Incorporated unfolded two-particle correlations

### PR DESCRIPTION
**Pull request by victor-gonzalez**
Two-particle number and transverse momentum correlations based in unfolded (eta1, eta2, phi1, phi2) data collection. Adapted to ESD and AOD format and automatically configured according to data taking period. Fully doxygen documented.

### CODE REVIEW

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
+1

**Comment by AudreyFrancisco** [comment]
Hi @victor-gonzalez, this commit prevents the compilation on my system (macOs Sierra 10.12.6). The test hangs at the last step and reverting the commit solves the issue. Could you please investigate it ?

**Comment by dberzano** [comment]
@AudreyFrancisco @dcaffarr are you using Xcode 9 with ROOT 5? I am asking as this is not supported anymore. You should use ROOT 6 builds instead. The culprit might not be this commit.

**Comment by dcaffarr** [comment]
No @dberzano, I am using Xcode 7.3 and Root 5, MacOSX 10.11.4

**Comment by dberzano** [comment]
Thanks for clarifying. Then something has to be done by the authors of this pull request.

**Comment by AudreyFrancisco** [comment]
Hi @dberzano same for me, Xcode 8.0, root 5 and MaxOSX 10.12.6 (Sierra)

**Comment by victor-gonzalez** [comment]
Hi, I produced several times AliPhysics with this commit without any single warning but I don't have any Mac around just Ubuntu 16.04. It is there a possibility to force even more the warning/error level of the compiler? Whatever the mistake I made, I don't have any clue for addressing it.

**Comment by rbertens** [comment]
Hi @dberzano , @dcaffarr , @AudreyFrancisco , @victor-gonzalez ,
Since I approved this PR I'm also following the thread. I cannot reproduce this issue, but the error is also not clear to me: is it correct that ctest hangs when loading this library? E.g. that
``gSystem->Load("libPWGCFCorrelationsDPhi")``
would hang indefinitely? 
Thanks,
Redmer

**Comment by dcaffarr** [comment]
Hi @rbertens, 
yes. this is what I get when i run the build with debug option. It seems it hangs at the last test, the 92nd. I don't know how to check with library is tested last. 
Below the print out. I tried few times and waited for even more than 30 mins and it was still hanging... 

DEBUG:AliPhysics:0: 89/92 Test #16: load_library_PWGGlauber ....................   Passed    0.53 sec
DEBUG:AliPhysics:0:       Start 81: load_library_PWGPPevcharQn
DEBUG:AliPhysics:0:       Start 46: load_library_PWGCFflowBW
DEBUG:AliPhysics:0: 90/92 Test #81: load_library_PWGPPevcharQn .................   Passed    0.41 sec
DEBUG:AliPhysics:0: 91/92 Test #46: load_library_PWGCFflowBW ...................   Passed    0.41 sec

**Comment by victor-gonzalez** [comment]
Hi @rbertens @dcaffarr 
I've produced with right now master because two days ago there were only 91 libraries tested. Production was OK, there were 92 libraries tested and it seems library `PWGCFCorrelationsDPhi`is tested in 29th place

`DEBUG:AliPhysics:ali-master:       Start 29: load_library_PWGCFCorrelationsDPhi`
`DEBUG:AliPhysics:ali-master:  6/92 Test #29: load_library_PWGCFCorrelationsDPhi .........   Passed    1.51 sec`

**Comment by AudreyFrancisco** [comment]
Hi @rbertens. The system hangs when compiling just as @dcaffarr but I cannot reproduce the issue when loading this library only since I cannot build if when the commit is included. The last test where it hangs is not the corresponding library. 
@dberzano I intend to upgrade to highSierra and root6 by the end of the week so it might solve the issue for me.

**Comment by dberzano** [comment]
@AudreyFrancisco I am not saying that upgrading to ROOT 6 solves the issue. The problem is that all our systems run High Sierra + Xcode 9 + ROOT 6 so... we don't have the requirements to reproduce your issue. I am trying to have a look at `PWGCFCorrelationsDPhi` to see if something rings some bell...

**Pull request merged**
