### PR TITLE
Fix integer abs -> TMath::Abs AliCentralitySelectionTask

### PR DESCRIPTION
**Pull request by aaniin**
Code is good as is, but generates warning.

@atoia what do you think?

### CODE REVIEW

**Comment by aaniin** [comment]
Dear  @atoia (Alberica Toia), @ekryshen (Evgeny Kryshen), @victor-gonzalez (Victor Gonzalez), @chiarazampolli (Chiara Zampolli), @zconesa (Zaida Conesa Del Valle), @ddobrigk (David Dobrigkeit Chinellato), @akalweit (Alexander Philipp Kalweit)

Can you give a +1 here?! The code change is trivial and it's been three weeks. 

Cheers,
Hans

**Comment by atoia** [comment]
agree, +1

**Comment by aaniin** [comment]
Hi @atoia ,

Thanks for your review! For github to recognize it, the +1 has to be the first word, I think. If anybody has a good how to github.. ..I'm also mostly clueless and just guess.

Cheers,
Hans

**Comment by atoia** [comment]
+1

**Pull request merged**
