### PR TITLE
Add the event variables in the tree

### PR DESCRIPTION
**Pull request by JaeYoonCHO**
I add some event variables in the tree for off-line tree analysis.
In the AddTask, I add the HMSPD trigger.

### CODE REVIEW

**Comment by xinyepeng** [comment]
@JaeYoonCHO Hi, JaeYoon, thanks for the implement! Before approving it, As the commit is adding new data members to the task, the "ClassDef" number at the bottom of "AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h" should be incremented. Besides I'm wondering if you can add a function to control switching on or off the event property tree, in case people will only focus on MB analysis.

**Comment by JaeYoonCHO** [comment]
Hi, @xinyepeng , Thank you for the comment! 
I'm fixing the "ClassDef" and adding the option to switch off the writing the HM event tree now.
I will push it again soon.
Thank you again :)

**Comment by xinyepeng** [comment]
+test

**Comment by xinyepeng** [comment]
+1

**Pull request merged**
