### PR TITLE
Fix file name in order to have a uniform file name scheme

### PR DESCRIPTION
**Pull request by aiola**

### CODE REVIEW

**Comment by aiola** [comment]
Hello @fcolamar,
this is a trivial change which is needed for my automatic scripts. If you have nothing against it, could you approve it?
Thanks,
Salvatore

**Comment by fprino** [comment]
+1 (I saw that Fabio didn't answer, so I had a look at the modification and I approve it)

**Comment by fprino** [comment]
I hope this is fine for HFCJ....

**Comment by aiola** [comment]
Hi @dberzano,
this error seems unrelated to my commit. Could you please have a look?
Thanks,
Salvatore

**Pull request merged**
