### PR TITLE
Add histograms for efficiency

### PR DESCRIPTION
**Pull request by JaeYoonCHO**
The histograms for efficiency calculations were added.

### CODE REVIEW

**Comment by lvermunt** [comment]
+1

**Comment by lvermunt** [comment]
Hi @JaeYoonCHO, I have no idea why this crashes. Seems fully unrelated to your PR. Maybe you (and perhaps @fcatalan92) can also have a look? If you also have no idea, we can ping the experts

**Comment by fcatalan92** [comment]
Hi @lvermunt @JaeYoonCHO, there are no errors in the build log, only warnings. It could be that the build stopped for some spurious reason. Now it is running again, so let's see what happens.
@JaeYoonCHO Did you check that these changes compile on your PC?

**Comment by JaeYoonCHO** [comment]
Hello, @fcatalan92 and @lvermunt ,
Now I can see my PR was merged into master!
Thank you for checking this crash.

**Pull request merged**
