### PR TITLE
Add New task to plot raw jet pt spectrums

### PR DESCRIPTION
**Pull request by 11kumaoka**
I want to add the new task to plot raw jet pt spectrums into AliPhysics/PWJE/EMCALJetTasks/UserTasks.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
@jdmulligan Are you okay with the changes?

**Comment by jdmulligan** [comment]
Yes fine from my side, thanks

**Comment by raymondEhlers** [comment]
Okay, thanks James!

@11kumaoka, you need to add you new task to the LinkDef. Please also remove the `README.md` file you keep trying to commit

**Comment by raymondEhlers** [comment]
+test

**Comment by 11kumaoka** [comment]
I am sorry, it is my mistake.

**Comment by raymondEhlers** [comment]
@11kumaoka no problem. You don't have to close this PR - you can just update it

**Comment by 11kumaoka** [comment]
I'm sorry again.
I would like to report my condition.
1. Three months ago, I pull-request (120604d).
But I understood I did not need it and I intended to cancel the pull-request.
However, the pull-request is existing.
2. I accidentally deleted my account which did the pull-request three months ago.
So now I can not delete the pull-request.

If the pull-request has a bad-effect, could you delete it?

**Comment by raymondEhlers** [comment]
@11kumaoka , I encourage you to read up on how pull requests (PR) work. If a PR is closed and not merged, then nothing has changed in our alisw/AliPhysics repository. I suspect that you have unrelated or old commits on the branch that you're using to open this pull request, which is why things like your `README.md` changes continue to show up.

So you probably need to cleanup your branch, although I can't see where it's coming from (perhaps due to your accidental account deletion). Your overall goal of adding a task is just fine, and it's okay that you're learning, but I can't help you  debug it remotely - I think you'll have to consult with your local git expert to sort out what's going on here

**Pull request closed without merging**
