### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by eumaka**

### CODE REVIEW

**Comment by akubera** [comment]
+test

**Comment by aohlson** [comment]
Hi @eumaka 
The compilation fails because of the line #include "AliLightV0vertexer".  If absolutely necessary, we could add a link the PWGLF/Strangeness directory of AliPhysics, in order for the include file to be found.  However, I don't see that AliLightV0vertexer is used anywhere in your class.  If it's not necessary, could you remove the include statement?  I notice there seem to be many unnecessary includes, in fact.  Could you try reducing them?  
Thanks!

**Comment by akubera** [comment]
+test

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+1

**Pull request merged**
