### PR TITLE
New case for Lc --> K0s+p with TMVA (A. Alici)

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Pinging @andreaalici , as he is the author.

**Comment by afestant** [comment]
+test

**Comment by afestant** [comment]
Hi @andreaalici, @chiarazampolli,
I have added yesterday a "case 11" in order to apply nsigma cuts with TPC and/or TOF for the bachelor calling the method MakeRawPID of AliAODPidHF. I guess we need to solve the conflicts by changing the case number.
Thanks, Andrea

**Comment by chiarazampolli** [comment]
Done, I did not know you were working on this, and since I had updated aliphysics yesterday afternoon, I did not think of updating it again - my fault, one should always do it, sorry.

**Comment by afestant** [comment]
No problem, I did add the new case yesterday in order to add the possibility to apply the PID selections that are implemented in AliAODPidHF::MatchTPCTOF method configuring them through the cut object.

**Comment by afestant** [comment]
+1

**Comment by chiarazampolli** [comment]
We need another change in your part now. I am commit it, please, check if the inizialition is fine with you.

**Comment by afestant** [comment]
Fine with me, thanks.

**Comment by afestant** [comment]
+1

**Pull request merged**
