### PR TITLE
Improvements for the Sigma0 MC handling

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by a-mathis** [comment]
+1

**Comment by a-mathis** [comment]
@ktf I should have pull request rights to these repositories, could you take a look why this doesn't work? Thanks!

**Comment by ktf** [comment]
+1
I can look at it tomorrow. Please ping me again.

**Comment by a-mathis** [comment]
@ktf thanks a lot! Would be great if the reason for this weird behavior could be found

**Pull request merged**
