### PR TITLE
Add jet angular correlations task

### PR DESCRIPTION
**Pull request by ljoergen**

### CODE REVIEW

**Comment by ljoergen** [comment]
Third time's the charm. Hopefully fastjet/PseudoJet.hh will be found now that it's in the source file, not the header.

**Comment by bdoenigu** [comment]
+1

**Comment by bdoenigu** [comment]
+1

**Comment by ljoergen** [comment]
alibuild keeps complaining various FastJet files can't be found while checking but the task runs both on the Grid and locally, and the error isn't even in my own code but in FJ_includes.h, which _I_ didn't write. How can that be?

**Pull request closed without merging**
