### PR TITLE
3 commits

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
+1

**Comment by ktf** [comment]
+test

**Comment by gconesab** [comment]
Hi, these 3 commits are for PWGPP/EMCAL and PWGGA/CaloTrackCorrelations where I should have commit permission, is this not the case?

**Comment by dberzano** [comment]
+1 (I am approving this for now.)

Hi @gconesab you do have permissions on `PWGGA/GammaConv` (the egroup is `alice-git-pcg-approvers`). We do not at the moment have specific permissions for `PWGPP/EMCAL`, but we have broad `PWGPP` permissions to `alice-svn-pwgpp`.

At the offline week we have asked all the PWGs to refactor their permissions. Can you point us to an egroup for EMCAL that should have permissions in `PWGPP/EMCAL`? Can you also tell us what other directories should be writable by the same egroup?

**Comment by gconesab** [comment]
Hi @dberzano, 

I was waiting for the final recommendation to create e-groups for commits. Right now there is none specific for EMCal. Also, we discussed on Friday EMCal meeting to have one e-group per sub-directory (there are several scattered over AliPhysics) since not all directories are fully EMCal devoted and can have several scopes. As soon as the guidance is published I will proceed creating e-groups (although I have missed it since I forgot to connect to offline week).

By the way, in principle, I should not have permissions on PWGG/GammaConv although I would not be against if the developers of PCG think I should.

Regards ... Gustavo

**Comment by dberzano** [comment]
Hi, thanks for the clarification - for `PWGGA/GammaConv` please contact @FriederikeBock and ask to be removed then!

**Comment by FriederikeBock** [comment]
Hi Dario, I don't understand why Gustavo would have rights in that directory, currently its only me and @dmuhlhei who are on that e-group. Regards Friederike

**Comment by dberzano** [comment]
OK my mistake, sorry - it was just an assumption. I have checked and you are of course rights :-)

**Pull request merged**
