### PR TITLE
Move track selection to namespace PWG::EMCAL

### PR DESCRIPTION
**Pull request by mfasDa**
Move track selection and dowscale factors to namespace
PWG::EMCAL. No functional change, just move to namespace
and adaptions in classes utilizing the track selection

### CODE REVIEW

**Comment by mfasDa** [comment]
+test

Could someone from the gamma approvers please give formal approval?

**Comment by gconesab** [comment]
+1

**Comment by mfasDa** [comment]
+test

**Comment by mfasDa** [comment]
@gconesab could you please do +1 again?

**Comment by gconesab** [comment]
+1

**Comment by e-masson** [comment]
Hi @mfasDa,

My train tests with today's tag (vAN-20180214-1) are failing due to the following error:
`Error: Symbol kTPCOnlyTracks is not defined in current scope  /tmp/AddTaskEMCALPhotonIsolation.CjHSnSV:265:`.

I see that you propagated the namespace change (`AliEmcalTrackSelection` -> `PWG::EMCAL::AliEmcalTrackSelection`) in the classes/headers, but not in the related `AddTask` files: could this explain the error I get?

Thanks, best regards,
Erwann

**Comment by mfasDa** [comment]
Hi @e-masson ,

yes, either the macros or (if used in the wagon customization) the wagon configurations are responsible. Those need to be adapted by the owners.

Cheers

Markus

**Comment by e-masson** [comment]
Hi @mfasDa,

Thank you. Did you send an e-mail to the concerned people about that? I may have missed it...

Best,
Erwann

**Comment by mfasDa** [comment]
Certainly not!

**Comment by e-masson** [comment]
By "the concerned people" I meant of course through an EMCal list, not each person one by one :).

Anyway, this is now adapted in my AddTask, thanks for your help!

Best,
Erwann

**Pull request merged**
