### PR TITLE
PWGGA: remove ! in //!

### PR DESCRIPTION
**Pull request by jluehder**
Change //! to //

### CODE REVIEW

**Comment by kharlov** [comment]
Hi Jens, why do you change? Do you want to add these data members to the streamer to write to the root file for AnalysisManager? If these variables are transient and used only during analysis, their streamer is not needed.
Yuri

**Comment by dmuhlhei** [comment]
Hi Yuri, yes these members should be streamed in general - we think we made a mistake here because the task is not working as expected on the grid

**Comment by kharlov** [comment]
Usually I avoid writing unnecessary variables of analysis task to analysis manager. For this, all data members should be properly initialized in all constructors, including default ctor. Anyway, if you prefer writing them to a root file, I approve.
+1

**Comment by kharlov** [comment]
+1

**Pull request merged**
