### PR TITLE
Make task flexible for pp, pPb and PbPb

### PR DESCRIPTION
**Pull request by deepathoms**
Task is prepared to be able to run on pp, pPb and PbPb datasets

### CODE REVIEW

**Comment by ktf** [comment]
+test

**Comment by dberzano** [comment]
@deepathoms please ignore the error message, it's spurious and we are fixing it. What matters is that all checks have passed.

**Comment by deepathoms** [comment]
@dberzano Thank you. So there is no issue with the commit. I guess I will just have to be patient for it to be merged to AliPhysics.

**Comment by dberzano** [comment]
...yes, in fact one of the persons mentioned above should approve your merge.

**Comment by ebruna** [comment]
+1

**Pull request merged**
