### PR TITLE
New weights for training of central events (done with A. Alici)

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Pinging @andreaalici  for information.

**Comment by fprino** [comment]
+1

**Comment by chiarazampolli** [comment]
Dear @afestant , @jezwilkinson , @fprino , @cterrevo ,

Sorry to bother, I had forgotten two new files, so the tests failed. Could you re-approve the PR? 

Thanks!!

Chiara

**Comment by fprino** [comment]
+1

**Pull request merged**
