### PR TITLE
 Add angle between sum and difference of momentum vectors of the two …

### PR DESCRIPTION
**Pull request by sebaleh**
…dielectron legs

### CODE REVIEW

**Comment by aaroncapon** [comment]
+1

**Comment by miweberSMI** [comment]
Hi @sebaleh 

i think you need to add the new varoable also in the var manager cxx file (otherwise the namings/titles get confused).

Cheers,
Michael

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+1

**Pull request merged**
