### PR TITLE
Enable double V0 finder vertexer for 3-body hypertriton reconstruction

### PR DESCRIPTION
**Pull request by fmazzasc**

### CODE REVIEW

**Comment by mpuccio** [comment]
+1

**Comment by mpuccio** [comment]
Hi @ktf @TimoWilken , are the builder stuck?

**Comment by TimoWilken** [comment]
Hi @mpuccio, sorry, they were. Should be fixed now, this PR is in the queue.

**Comment by mpuccio** [comment]
Thanks a lot @TimoWilken !

**Pull request merged**
