### PR TITLE
treeHF/JetTree: Implement separate flat trees for jets and constituents

### PR DESCRIPTION
**Pull request by jdmulligan**
After discussions with @ginnocen, re-organize a bit the jet tree structure. 

 @fgrosa @lvermunt

### CODE REVIEW

**Comment by fgrosa** [comment]
Hi @jdmulligan thanks a lot for implementing this! I would say that it is ok and can be merged.

**Comment by jdmulligan** [comment]
Hi approvers, please go ahead and +1 when you have a moment.

Thanks,
James

**Comment by afestant** [comment]
+test

**Comment by afestant** [comment]
+1

**Pull request merged**
