### PR TITLE
PWG/CALO: fix missing return value

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
+1

**Comment by dberzano** [comment]
@FriederikeBock can you approve?

**Comment by dberzano** [comment]
+test

**Comment by mfasDa** [comment]
@dberzano,@FriederikeBock I am running in the same issue. I would support the patch from Dario, would be good if this PR could be approved soon.

**Comment by FriederikeBock** [comment]
@dberzano yes we can fix it that way

**Comment by FriederikeBock** [comment]
+1

**Comment by dberzano** [comment]
+1

**Pull request merged**
