### PR TITLE
Fix EP angle issues, MC issues

### PR DESCRIPTION
**Pull request by moliver813**
Fixes errors in MC handling and in EP angle calculations
Adds histos monitoring tracks

### CODE REVIEW

**Comment by e-masson** [comment]
+test

**Comment by e-masson** [comment]
Hi @davidrohr, @gconesab, @jgrosseo, @efranzis, @qgp, @miguelignacio, @e-masson, @mauro-cosentino, @shahor02,

I see you have approval rights in this part of the AliPhysics repository but I am usually the only one to approve pull requests here. However I am leaving the collaboration and would like to be sure that someone will take care of the requests made here.
Alternatively, perhaps @moliver813 could be given approval rights, as he is the main committer without rights it seems :).

Thank you, best,
Erwann

**Comment by gconesab** [comment]
+1

**Comment by gconesab** [comment]
I have removed you and Eliane and I will add Michael for next commit.

Gustavo

On 5 Nov 2019, at 08:38, Erwann Masson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @davidrohr<https://github.com/davidrohr>, @gconesab<https://github.com/gconesab>, @jgrosseo<https://github.com/jgrosseo>, @efranzis<https://github.com/efranzis>, @qgp<https://github.com/qgp>, @miguelignacio<https://github.com/miguelignacio>, @e-masson<https://github.com/e-masson>, @mauro-cosentino<https://github.com/mauro-cosentino>, @shahor02<https://github.com/shahor02>,

I see you have approval rights in this part of the AliPhysics repository but I am usually the only one to approve pull requests here. However I am leaving the collaboration and would like to be sure that someone will take care of the requests made here.
Alternatively, perhaps @moliver813<https://github.com/moliver813> could be given approval rights, as he is the main committer without rights it seems :).

Thank you, best,
Erwann

**Pull request merged**
