### PR TITLE
new analysistask to study UE with spherocity

### PR DESCRIPTION
**Pull request by aortizve**
This task allows the study of particle production associated to the underlying event using cuts on spherocity and multiplicity. Spherocity is calculated using the class AliSpherocityUtils. The user has the option of cutting on spherocity percentiles, this has to be specified in AddTaskUeSpherocity.C. For the time being  only one root file for the period LHC15f (pass2) has been added to help in the extraction of the spherocity percentiles. New implementations will come soon.

### CODE REVIEW

**Comment by aortizve** [comment]
Hello Jochen
Thanks for your comments. The goal is to provide an unique code to make an event selection based on spherocity. The root file is helpful to define the different spherocity percentile classes. The idea is to produce a unique root file containing the required information to know the percentiles for each period. For the time being only information for LHC15f pass 2 is available.  In the coming updates, I will reduce the size of the root file (now it is 1 M). However, for the time being I would need its inclusion in  AliPhysics to run on the lego trains.

**Comment by qgp** [comment]
Hi Antonio,

yes, but whatever large file enters into git, remains forever, even if later you make it smaller.

To use it in the LEGO trains this is not necessary, there's a procedure exactly for cases like this, see the section on "How to use large data files for analysis" https://alisw.github.io/git-advanced/

Sorry, but I think we should use the occasion now to get this right from the beginning. Let me know if you need help.

Cheers,
   Jochen

**Comment by aortizve** [comment]
Hello Jochen
I see, could you please give me the permissions to create a new sub-directory inside:
/eos/experiment/alice/analysis-data/OADB/PWGMM
The directory should be UE, there I would put my root file.

The next step would be to modify few lines in my analysis task to open the root file:
TFile::Open(AliDataFile::GetFileNameOADB...

Would that be ok?

Cheers
Antonio

**Comment by qgp** [comment]
Hi Antonio,

> I see, could you please give me the permissions to create a new sub-directory inside:
/eos/experiment/alice/analysis-data/OADB/PWGMM

@dberzano: Could you give Antonio (incoming MM convener) the required permissions, please? I'm afraid I don't have the privileges to do so.

> The next step would be to modify few lines in my analysis task to open the root file:
TFile::Open(AliDataFile::GetFileNameOADB...

The files in the OADB sub-directory, can (and should) be used through the normal OADB interface (with the corresponding file structure for OADB entries). If you don't use the OADB features the correct path to the file would be `/eos/experiment/alice/analysis-data/PWGMM`. Then, you obtain the file name with `AliDataFile::GetFileName(...)`.

Cheers,
   Jochen

**Comment by aortizve** [comment]
Thanks Jochen, hope @dberzano could help us with this.
Regards

**Comment by dberzano** [comment]
Hi all, permissions are governed by the egroup `alice-svn-pwgmm`. We should add @aortizve there. But if we do that, he'll have permissions for committing under PWGMM as well.

* If this is acceptable, let's add @aortizve to `alice-svn-pwgmm`
* If this is not acceptable, then @qgp or @rbertens should upload the file on EOS on his behalf

**Comment by qgp** [comment]
Hi @dberzano, 

as designated PWG-MM convener it seems more than appropriate to give these rights to @aortizve - unless he objects ;-)

Cheers,
   Jochen

**Comment by dberzano** [comment]
It's done

**Comment by aortizve** [comment]
Thanks!

**Pull request closed without merging**
