### PR TITLE
Major updates for online particle composition correction

### PR DESCRIPTION
**Pull request by phuhnGithub**

### CODE REVIEW

**Comment by bdoenigu** [comment]
+1

**Comment by phuhnGithub** [comment]
removed ROOT5 compatibility because of C++11 features in header files

**Comment by bdoenigu** [comment]
+1

**Comment by bdoenigu** [comment]
+1

**Comment by valzacc** [comment]
+test

**Comment by bdoenigu** [comment]
+1

**Comment by valzacc** [comment]
+test

**Comment by mario-krueger** [comment]
+1

**Comment by valzacc** [comment]
+test

**Pull request closed without merging**
