### PR TITLE
Code aesthetics + correction in PtIsoTrackEtaBand()

### PR DESCRIPTION
**Pull request by e-masson**
General indentation and more clarity in code (blank lines, spaces, obsolete comments deleted).
One correction in PtIsoTrackEtaBand() where iTracksCone++; at line 2300 was formerly outside the else{} block.

### CODE REVIEW

**Comment by e-masson** [comment]
Hi @dlodato,
Unfortunately I did not find any Twiki page giving some general coding convention, at least concerning the tabulations and the position of the curly braces in a if/for/while case.
As those were written in various ways throughout the task, I found clearer to make them uniform by opening the curly brace and beginning a new line for the instructions: was that the good choice (instead of putting the opening curly brace below the "if")?
Concerning the tabulations there also were differences between parts of the code, probably due to different analysers, but the modifications I implemented in terms of tabulation mainly affect the initialisation of variables at the beginning of the constructors (which is not a big region).
Anyway, please could you give me a reference page (or your own recipes) about ALICE coding convention concerning these points (spacing, tabulations and if/for/while syntax)? In the patch you are asking for, do I have only to keep the comments cleaning/text corrections/PtIsoTrackEtaBand() fix?
Thanks and best,
Erwann

**Comment by dlodato** [comment]
Hi @e-masson , 

there's no such page about indentation (to my knowledge), only about the fact that data members
should start with fxxx or method should start with capitol letters...
 
We agreed among us on a the nowadays tabbing; then Lucile (i think) used to write 
if()
{
for her part of code, Marco and me used if(){  .
*If you want to uniform these, you are more than welcome.*
What I was referring to was more 

if(){ --> if () { (with a space before and after the parentheses ); or this (for example):
-  //________________________________________________________________________
 -AliAnalysisTaskEMCALPhotonIsolation::~AliAnalysisTaskEMCALPhotonIsolation(){
 -    // Destructor
 +//________________________________________________________________________
 +AliAnalysisTaskEMCALPhotonIsolation::~AliAnalysisTaskEMCALPhotonIsolation() {
 +  // Destructor  
In this case the space is put on purpose to better identify the start of a new method.

I am asking this because if someone else makes a change to the code and then indent it to check whether he/she forgot some bracket, the result will be a code with ALL lines changed by 1 space or 1 tabbing, and commits become impossible to read/understand and all the more reason it will be impossible to keep track of what is really important in the code changes (being it a fix to a bug or the addition of a new functionality) .
This situation will present again once a different user with a different indentation in his/her editor will make a further change to the code, and so on...

So if you could take out the cases I mentioned, the commit will be smaller and clearer...
(i had a look already to the actual bug fix and it was indeed needed, thanks!) 

Cheers, 
Davide

**Comment by e-masson** [comment]
Hi again @dlodato,
Thanks for your advice!
I lightened the modifications by reverting most of the indentation and spaces you talked about. Is it better to make a new commit/pull request or to send you a patch? I am not familiar with patches yet (I think I can create/apply one but this may be all...).
Best, Erwann

**Comment by e-masson** [comment]
Hi again @dlodato,
Here are two patches, each one corresponding to one commit:

1. 0001-Code-aesthetics-correction-in-PtIsoTrackEtaBand.patch: what I pushed this morning (the one with a lot of spaces!),
2. 0002-Removing-extra-spacing-from-the-previous-commit.patch: a new commit in order to revert most of these spaces (while keeping the standardisation of syntax and the correction of the little bug).

[PhotonIsolationCleaning_20170410.zip](https://github.com/alisw/AliPhysics/files/910103/PhotonIsolationCleaning_20170410.zip)

Please let me know if these patches are ok for you and when they will be applied.

Thanks and best,
Erwann

**Comment by dlodato** [comment]
Hi @e-masson,
mm..well you should be able to push a second commit to your fork that "reverts" some features of the previous one and then make a unique pull request with two commits..
can you do this? 
Cheers, 
Davide

**Comment by dlodato** [comment]
+1

**Comment by e-masson** [comment]
Here we are, I think this should work!

**Comment by e-masson** [comment]
Hi @dlodato,
I spoke too soon... I had a look at the check errors: could the removal of the curly braces associated to a given case (in the switch(fUEMethod) at line 3364) be the reason of them? Some other "switch" in the code have no curly braces but do not fail...
Thanks and best,
Erwann

**Comment by e-masson** [comment]
Hi everyone,
I finally corrected an issue introduced yesterday in my code cleaning: some curly braces were missing from AddParticleToUEMC(), they are now restored and AliPhysics compiles as desired.
Sorry for the inconvenience and thanks @dlodato for your help!
Best, Erwann

**Comment by dlodato** [comment]
+1

**Pull request merged**
