### PR TITLE
Run 3 converter: addition of OTF V0s

### PR DESCRIPTION
**Pull request by ddobrigk**
This commit (from @mhemmer-cern - super thanks!) adds a path for saving on-the-fly V0s in our converted AO2D. I'm marking this as draft for discussion and will still make a few minor changes (mccollisions version bump to 001, for instance) before marking ready for review.

### CODE REVIEW

**Comment by ddobrigk** [comment]
@mhemmer-cern when you get around to it, can you also write to this PR a message explaining the latest status of the data volume after all the reduction steps you took, since it's now much better? Thank you!!

**Comment by ddobrigk** [comment]
@mhemmer-cern sorry to insist, but this is just a ping for you to report here on the size reduction you did - after which imho this could also be merged for testing. Tagging also @maciacco . Thank you!!

**Comment by mhemmer-cern** [comment]
I will need to push a fix that I just saw when running on AOD MC.
The reduction we saw was from 20% to 6% in PbPb data, just by truncation and cutting.

**Comment by ddobrigk** [comment]
Hi @mhemmer-cern , can we confirm this to be ready to go ahead? It would be good if we could test it already. Thank you!

**Comment by mhemmer-cern** [comment]
@ddobrigk from my side (PCM photons) this should be ready to go. :)

**Comment by mpuccio** [comment]
+1

**Comment by jokonig** [comment]
+1

**Pull request merged**
