### PR TITLE
Possibility to convert Run1/2 AOD to AO2D

### PR DESCRIPTION
**Pull request by pzhristov**

### CODE REVIEW

**Comment by pzhristov** [comment]
@ktf @TimoWilken  It seems the build uses the latest AliRoot tag, but the needed changes from AliVEvent are only in the AliRoot master. Would it be possible to tag the AliRoot master and move the build system to it?

**Comment by pzhristov** [comment]
+test

**Comment by pzhristov** [comment]
+1

**Comment by pzhristov** [comment]
It indeed seems I overwrote the changes - will find them and add again.

**Comment by jgrosseo** [comment]
Draft is not enough for avoiding the merging. I closed it.

**Pull request closed without merging**
