### PR TITLE
updated pPb BDT pKpi systematics

### PR DESCRIPTION
**Pull request by jaimenorman**
Lc pPb BDT pKpi systematic uncertainty function updated with final values

### CODE REVIEW

**Comment by arossi81** [comment]
+test

**Comment by arossi81** [comment]
+1
p.s. is it correct that the MC pt shape uncertainty "oscillates" with pt (0,3,1,3)?

**Comment by jaimenorman** [comment]
Hi Andrea,

Thanks for the +1.
This is how the systematic uncertainty has been evaluated, reflecting in principle the extent to which the different pt shape changes the efficiency in each pt bin, which has been accepted. Does this sound ok?

Cheers,
Jaime
________________________________

**Comment by arossi81** [comment]
Hi Jaime,
if those are the right numbers it is ok, at least for the commit. Then, whether or not it is expectable to have this trend has to be discussed in D2H (you did it in the past, right?).
Cheers,
Andrea

**Comment by jaimenorman** [comment]
Hi Andrea,

Yes, it had been discussed in the D2H. The tighter BDT cut in 4-6 with respect to 6-8 GeV/c, and the wider pt bit 8-12 I think are the two reasons why this trend would be expected.

Cheers,
Jaime
________________________________

**Pull request merged**
