### PR TITLE
QnVectorCorrection framework adaptation to ROOT6

### PR DESCRIPTION
**Pull request by victor-gonzalez**

### CODE REVIEW

**Comment by victor-gonzalez** [comment]
Could any of you, with access rights, please approve this PR if so you consider?
Many thanks in advance!

**Comment by victor-gonzalez** [comment]
Dear @chiarazampolli it seems the +1 was not properly given because de PR did not get merged and it is still pending approval.
Could you please review it.
Thanks!!!

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Trying again, it seems it worked.
Let's see...

**Comment by victor-gonzalez** [comment]
Now yes!!!
Thanks!!!

**Pull request merged**
