### PR TITLE
Functionalities for Spline production

### PR DESCRIPTION
**Pull request by MartinSchmidtTuebingen**
Adding several funktionalities:
* Function for ALEPH in AliTPCcalibResidualPID
* Output of AliTPCcalibResidualPID will be adjusted in maxMultiplicity according to the collision system
* Adding Pile-Up rejection of events in AliTPCcalibResidualPID, TPCPIDEtaTree and TPCPIDEtaQA

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello Martin,

Can you change the title of the pull request? The current one is too generic.

Thanks!

Chiara

**Comment by MartinSchmidtTuebingen** [comment]
I hope it is ok now.

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Yes, thanks!
I "+test"-ed your PR, but probably @wiechula is the best person to approve. 
Chiara

**Comment by wiechula** [comment]
+1

**Comment by mfasDa** [comment]
Hi @MartinSchmidtTuebingen , Hi @wiechula ,

this PR is breaking compilation on macOS due to narrowing conversion:

DEBUG:AliPhysics:AliPhysics:ali-master: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGPP/TPC/AliTPCcalibResidualPID.cxx:490:65: error: non-constant-expression cannot be narrowed from type 'int' to 'Double_t' (aka 'double') in initializer list [-Wc++11-narrowing]
DEBUG:AliPhysics:AliPhysics:ali-master:   Double_t xmaxHistQA[kNdim] = {50., 2000,  3.5,  4.5,  10,  5, IsPbPb ? 20000 : 4000};
DEBUG:AliPhysics:AliPhysics:ali-master:                                                                 ^~~~~~~~~~~~~~~~~~~~~
DEBUG:AliPhysics:AliPhysics:ali-master: /Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGPP/TPC/AliTPCcalibResidualPID.cxx:490:65: note: insert an explicit cast to silence this issue
DEBUG:AliPhysics:AliPhysics:ali-master:   Double_t xmaxHistQA[kNdim] = {50., 2000,  3.5,  4.5,  10,  5, IsPbPb ? 20000 : 4000};
DEBUG:AliPhysics:AliPhysics:ali-master:                                                                 ^~~~~~~~~~~~~~~~~~~~~
DEBUG:AliPhysics:AliPhysics:ali-master:                                                                 static_cast<Double_t>( )

Could you please have a look?

Cheers

Markus

**Comment by wiechula** [comment]
Hi @MartinSchmidtTuebingen , can you add a "." after each integer number. This should solve the problem.
Cheers,
Jens

**Comment by MartinSchmidtTuebingen** [comment]
OK, I have committed the fix in a new pull request

**Pull request merged**
