### PR TITLE
Update of B0 to dstar pi code

### PR DESCRIPTION
**Pull request by lvandore**

### CODE REVIEW

**Comment by lvandore** [comment]
If someone is able to start the test and merge the code it would be much appreciated. @arossi81  @ginesmartinez @fcolamar @zconesa @rbailhac @ebruna @sashingo @fprino

**Comment by fprino** [comment]
+test

**Comment by fprino** [comment]
Dear @dberzano,
how should we interpret the message above " Error while checking build/AliPhysics/release ...".
From the outcome of the tests it seems that everything is OK, but before giving a +1 I prefer to be sure that the error above will not cause troubles.

Thanks!

Ciao, Francesco

**Comment by dberzano** [comment]
Just ignore it, all tests are green. That error was temporary.

**Comment by fprino** [comment]
+1
Thanks Dario for the confirmation

**Comment by lvandore** [comment]
Thanks Dario and Francesco

**Pull request merged**
