### PR TITLE
Check: Introducing eff amplification factor

### PR DESCRIPTION
**Pull request by SwatiSaha-1997**

### CODE REVIEW

**Comment by abilandz** [comment]
+1

**Comment by SwatiSaha-1997** [comment]
Dear @abilandz ,
The code was committed previously and this PR implements certain changes that are running locally. Still I am getting this error from alibuild. Could you please suggest me in this regard. Many thanks in advance.
Swati

**Comment by abilandz** [comment]
> Dear @abilandz , The code was committed previously and this PR implements certain changes that are running locally. Still I am getting this error from alibuild. Could you please suggest me in this regard. Many thanks in advance. Swati

Dear @SwatiSaha-1997, 

I don't think this error has to do anything with your code, I see that other pull requests are also failing for the same reason. 

Cheers,
Ante

**Comment by SwatiSaha-1997** [comment]
Dear Ante,
Thank you very much. So, I should wait for this to automatically merge.
Regards,
Swati

**Comment by SwatiSaha-1997** [comment]
> > Dear @abilandz , The code was committed previously and this PR implements certain changes that are running locally. Still I am getting this error from alibuild. Could you please suggest me in this regard. Many thanks in advance. Swati
> 
> Dear @SwatiSaha-1997,
> 
> I don't think this error has to do anything with your code, I see that other pull requests are also failing for the same reason.
> 
> Cheers, Ante

Dear Ante,
Thank you very much. So, I should wait for this to automatically merge.
Regards,
Swati

**Comment by mfasDa** [comment]
Please restart the CI - the incompatibilities should be fixed now.

**Comment by SwatiSaha-1997** [comment]
> Please restart the CI - the incompatibilities should be fixed now.

Dear @mfasDa ,
The checks are successfully done now, but it is not getting merged as it used to automatically do earlier. Could you please check and let me know if something more has to be done? Many thanks in advance.
Regards,
Swati

**Pull request merged**
