### PR TITLE
fast Glauber+NBD fitter for AliMultSelection

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
+test

**Comment by ddobrigk** [comment]
Hmmm, not quite sure what happened here, as I cannot access the logs...

**Comment by dberzano** [comment]
It should have nothing to do with your code and should in principle go away alone.

**Comment by ddobrigk** [comment]
@dberzano... this is taking a while. Is this normal? thanks!

**Comment by dberzano** [comment]
+test

**Comment by ddobrigk** [comment]
+test (okay, this is piling up other items... will wait for approved test and approve)

**Comment by ddobrigk** [comment]
+1

**Pull request merged**
