### PR TITLE
Fixed scope error in TPCCorr per Run

### PR DESCRIPTION
**Pull request by carstooon**
As @pdillens requested in https://github.com/alisw/AliPhysics/pull/867: The fix for line 1769

### CODE REVIEW

**Comment by dberzano** [comment]
Hi, can you please consider to rename the inner `histo` variable to something else to completely avoid confusion? The code you have committed works, but having a toplevel `histo` and a scope-level `tmpHisto` or similar would really be cleaner.

**Comment by carstooon** [comment]
Hi Dario,
I am not sure that I understand your comment.
Line 1755 creates an pointer to an (uninitialized) TH1 object called `histo`. Later in the code (1769/1778) `histo` gets initialized/assigned. This variable is later checked if it exists (1780). There is no new "scope-level `tmphisto`" which is used, just the old `histo`.
Do I oversee something?

Cheers
Carsten

**Comment by dberzano** [comment]
Hi @carstooon, ok you are right - I was in a rush and I thought you were doing exactly the opposite of what you effectively did :-) Please ignore my comment. Cheers

d.

**Comment by dberzano** [comment]
+test

**Comment by pdillens** [comment]
+1

**Pull request merged**
