### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by bhohlweger**
Merely Aesthetic changes by formatting of the FemtoDream code in the PWGCF Folder according to the Google Coding Style

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @bhohlweger, I am not aware of any ALICE standard for formatting (we have clearly defined standards for O2).

In any case, before approving, please state clearly that the changes you have made are merely aesthetic 😃

**Comment by dberzano** [comment]
Also, before approving, please use a meaningful commit message. `Formatting` means all and nothing. Something like: `Format PWGCF code according to rules` would do, for instance.

**Comment by dberzano** [comment]
Can you change the commit? Since we merge (and not squash-merge), it's the commit message that matters.

```
git commit --amend -m 'Format PWGCF code according to rules'
git push -f
```

**Comment by bhohlweger** [comment]
@dberzano sorry, changed it and pushed it on my repo!

**Comment by dberzano** [comment]
+1

I won't bother you again this time but please read this:

> https://chris.beams.io/posts/git-commit/#seven-rules

In particular:

* Use imperative verbs to start the commit message (`Fix this`, `Add that`, etc.)
* Keep your commit message strictly shorter than 50 characters. Then leave a blank line and use the remaining space to add a description of your favourite length
* Please state, in the commit message, the scope of your changes (_e.g._ PWGCF)

I believe we should start advertising those rules, we never did 😄

**Comment by bhohlweger** [comment]
@dberzano hey thanks, that looks really helpful and I will look at it! Cheers

**Pull request merged**
