### PR TITLE
Update code for PID study with tagged samples of p/K/pi

### PR DESCRIPTION
**Pull request by fgrosa**
1) implement NsigmaTPC corrections vs eta 
2) replace std::array with std::vectors to keep compatibility with root5
3) update mactro to add possibility to project vs p and to select eta interval

### CODE REVIEW

**Comment by fprino** [comment]
+1

**Comment by fprino** [comment]
+1

**Comment by jezwilkinson** [comment]
+test

**Comment by jezwilkinson** [comment]
ah, it seems i have rights on the vertexingHF folder but not on the treeHF folder. Someone else will need to approve the test..

**Comment by afestant** [comment]
+test

**Comment by afestant** [comment]
+1

**Pull request merged**
