### PR TITLE
Addition of User task AliAnalysisTaskEmcalJetEnergyFlow

### PR DESCRIPTION
**Pull request by ChrisPliatskas**
With this PR, I want to add my analysis task named AliAnalysisTaskEmcalJetEnergyFlow within the directory of PWGJE/EMCALJetTasks/UserTasks.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+1

**Comment by mfasDa** [comment]
@ChrisPliatskas Your PR creates a compiler warning - seems to be first appearing under gcc-10 - concerning the usage of ":" as part of your multiple include protection which is normally reserved in c++.

```
2021-05-24@15:43:53:DEBUG:AliPhysics:AliPhysics:aliceo2: /software/markus/alice/sw/SOURCES/AliPhysics/aliceo2/0/PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h:1:13: warning: extra tokens at end of #ifndef directive
2021-05-24@15:43:53:DEBUG:AliPhysics:AliPhysics:aliceo2:     1 | #ifndef ALIA:ALYSISTASKEMCALJETENERGYFLOW_H
2021-05-24@15:43:53:DEBUG:AliPhysics:AliPhysics:aliceo2:       |             ^
```

Please have a look and fix (ideally replace ":" with "_"). Thanks!

**Comment by ChrisPliatskas** [comment]
@mfasDa thank you for the message. For some reason, "N" was substituted by ":" at that line and that caused the trouble (probably some typo). So should I make a new PR?

**Comment by mfasDa** [comment]
@ChrisPliatskas Thanks for your fast response! Yes, please open a new pull request.

**Pull request merged**
