### PR TITLE
Updates for the HF multi-trial class and the D-tagged jet raw yield uncertainty

### PR DESCRIPTION
**Pull request by aiola**
These PR contains a number of commits:

- Fix an issue with invalid memory access when the results of the mass fit are drawn in the canvas and the mass fitter is deleted
- Fix various potential (and actual) memory leaks
- Fix indentation

### CODE REVIEW

**Comment by arossi81** [comment]
+test

**Comment by arossi81** [comment]
Hi @aiola,
you should increase the ClassDef for AliDJetRawYieldUncertainty.
Concerning the modifications to the MultiTrial and MassFitter classes, your proposals looks reasonable to me. However, before committing the changes, could you ask someone from D2H to make an explicit test to cross check that he gets what expected? 
Ciao,
Andrea

**Comment by aiola** [comment]
Ciao @arossi81,
thanks for starting the test. Regarding AliDJetRawYieldUncertainty I think that it is not needed to increase the ClassDef version because the two fields that I added are transient (i.e. defined with //!<!).

For D2H: @fprino? Someone else?

Best,
Salvatore

**Comment by fprino** [comment]
I looked in the code modifications in the MassFitter and MultiTrial classes and in principle the functionalities should be the same.
Andrea, do you think one needs a test running it for some cases?

**Comment by arossi81** [comment]
Ciao Salvatore,
yes, I think you're right, it should not be needed to increase the ClassDef version for the addition of transient data members.
Francesco: well, for me also the changes are ok, I was proposing a test just to be sure that I did not overlook something because the diff was large, but it's not strictly needed. We can commit it.
Cheers,
Andrea

**Comment by arossi81** [comment]
+1

**Pull request merged**
