### PR TITLE
Splitting PWGGAGammaConv library. New library PWGGAGammaConvBase.

### PR DESCRIPTION
**Pull request by jgrosseo**
This avoids a circular dependencies for nano AODs.

### CODE REVIEW

**Comment by jgrosseo** [comment]
+1

**Comment by FriederikeBock** [comment]
this commit is ok for the conversions

**Comment by ktf** [comment]
You need to rebase..

**Comment by jgrosseo** [comment]
I did 10 minutes ago

**Comment by jgrosseo** [comment]
Rebased

**Comment by jgrosseo** [comment]
@ktf could you approve please? and let me know why more admin rights don't work...

**Comment by ktf** [comment]
+1

**Comment by jgrosseo** [comment]
@ktf OK next try. Could you approve once more, please?

**Comment by pzhristov** [comment]
+1

**Comment by jgrosseo** [comment]
@ktf @pzhristov The dependencies were spelled ALIPHYSICS_DECPENDENCIES instead of ALIPHYSICS_DEPENDENCIES in the CMakeList file. Actually it was always like that - no idea why it hits now.

**Comment by dmuhlhei** [comment]
Would it be possible to validate the commit locally before reiterating around here? This commit heavily touches our GammaConv folder and it seems we are experimenting around here... It must be guaranteed that no bug is introduced before this can go into the tag.

**Comment by jgrosseo** [comment]
@dmuhlhei  This was checked, it is just a library loading problem on ROOT6. @FriederikeBock also had a look.

**Comment by ktf** [comment]
+1

**Comment by jgrosseo** [comment]
+1

**Comment by jgrosseo** [comment]
@ktf I tried myself

**Comment by jgrosseo** [comment]
@ktf the loading should work as it does locally. Can it be related to the incremental build on the test infrastructure?

**Comment by ktf** [comment]
+1

**Comment by dberzano** [comment]
@jgrosseo I added you as admin to AliRoot only; now doing it for AliPhysics as well. I think you are right on the incremental build issue. Let me check it "manually".

**Comment by dberzano** [comment]
@jgrosseo OK I see the problem here; the PR changes > 50 files so approval automatically escalates to the infrastructure managers even though you are (and were) correctly in the list of approve-all persons. I'll fix this, it requires some development (for this one, let's have us admins react fast given we understand the urgency).

**Comment by jgrosseo** [comment]
@dberzano Thanks for looking into this, and thanks for checking it locally. In the end these just moves files, (and touches the CMakeList + LInkDef), but I guess one moved file counts as two files touched for git...

**Comment by ktf** [comment]
@dberzano could you remind me where the documentation for the approval infrastructure is?

**Comment by dberzano** [comment]
@jgrosseo indeed. Git does not have "move" actions, but it combines "delete" and "add", so they are counted twice.

**Comment by dberzano** [comment]
@ktf the C.I. configuration is here (protected of course): https://gitlab.cern.ch/ALICEDevOps/ali-marathon/blob/master/ci_conf/ (Michael is sorting this part of the doc out).

@jgrosseo I can perfectly reproduce the error locally, with a clean build directory... let me look into it.

**Comment by jgrosseo** [comment]
@dberzano 
The two libraries the test complained are:
 59/108 Test  #60: load_library_PWGGAGammaConvBase ...............***Failed    0.79 sec

Processing /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/build_AliPhysics_root6-1/test/load_library/LoadLib.C("libPWGGAGammaConvBase")...
cling::DynamicLibraryManager::loadLibrary(): /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/build_AliPhysics_root6-1/lib/libPWGGAGammaConvBase.so: undefined symbol: _ZTV16AliAnalysisUtils
(int) -1
--> This should be in OADB which is among the dependencies

        Start  63: load_library_PWGGAUtils
 60/108 Test  #59: load_library_PWGGAGammaConv ...................***Failed    1.45 sec

Processing /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/build_AliPhysics_root6-1/test/load_library/LoadLib.C("libPWGGAGammaConv")...
cling::DynamicLibraryManager::loadLibrary(): /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/build_AliPhysics_root6-1/lib/libPWGGAGammaConv.so: undefined symbol: _ZTV17AliDalitzAODESDMC
(int) -1
--> This should be in PWGGAGammaConvBase (the new library) and is among the dependencies

Could you go online in mattermost?

**Comment by ktf** [comment]
+1

**Comment by dberzano** [comment]
@ktf @jgrosseo Your latest commit does indeed fix the test concerning `AliAnalysisUtils`. You should just apply the same fix for the other class.

**Comment by ktf** [comment]
+1

**Comment by dberzano** [comment]
After iteratively applying inline -> sourcefile fixes, I am stuck at `undefined symbol: _ZTI22AliConversionMesonCuts`. This resolves to: `typeinfo for AliConversionMesonCuts`. I see no virtual function without proper implementation in that class, honestly... I really don't know how to proceed here.

**Comment by jgrosseo** [comment]
@dberzano thanks! Is that codebase somewhere so that I can continue with it?
As we suspect a root6 cling issue, shall we escalate it to root?

**Comment by ktf** [comment]
+1

**Comment by jgrosseo** [comment]
I finally solved it. The reason was the introduction of ALIPHYSICS_DEPENDENCIES which was not properly propagated into target_link_libraries in the CMakeList file.

Thanks @ktf for the quick approval

**Comment by pzhristov** [comment]
Thanks a lot!

**Comment by jgrosseo** [comment]
@FriederikeBock So finally it was solved. If you want to announce it on the respective lists go ahead. I believe it should be transparent as only files were moved.

**Pull request merged**
