### PR TITLE
Test

### PR DESCRIPTION
**Pull request by qgp**
Remove dielectrons

### CODE REVIEW

**Comment by qgp** [comment]
This (intentionally) also includes the commit which already is in PR #9, just for testing (as this is sure to happen ...)

**Comment by qgp** [comment]
Same question as for PR #9, anyway, here my +1

**Comment by dberzano** [comment]
Hello @qgp, I have changed the `+1` check in a way that it now has to be the first thing on the comment, to avoid potential confusion. Can you try again?

**Comment by dberzano** [comment]
I have just re-pushed, closing this.

**Pull request closed without merging**
