### PR TITLE
NanoAOD development

### PR DESCRIPTION
**Pull request by jgrosseo**
Needs synced AliRoot tag, see 
https://alice.its.cern.ch/jira/browse/ALIROOT-8244

### CODE REVIEW

**Comment by ktf** [comment]
+test

**Comment by jgrosseo** [comment]
@ktf This does not seem to build against v5-09-48 yet. The missing functions (e.g. SetT0SpreadIndex) are there:
https://github.com/alisw/AliRoot/blob/v5-09-48/STEER/AOD/AliNanoAODHeader.h

**Comment by ktf** [comment]
I think it's now being built with the correct version. Apparently CI uses slc7 rather than slc6 as the releases...

**Comment by jgrosseo** [comment]
+test

**Comment by jgrosseo** [comment]
+1

**Pull request merged**
