### PR TITLE
Di-hadron correlation analysis w.r.t event-plane

### PR DESCRIPTION
**Pull request by hyeonjoongkim**
Di-hadron correlation w.r.t event-plane analysis code.
CMakeLists and LinkHeader are modified.

### CODE REVIEW

**Comment by aohlson** [comment]
+test

**Comment by hyeonjoongkim** [comment]
Hi @aohlson , in my side the building works fine in both Mac and linux systems. Could you try building them once more?

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
Hi @hyeonjoongkim , 
I don't really understand the output log, since the tests seem to have run fine and the error messages don't appear to be related to your commit.  I've tried testing once more in case it was just a temporary glitch.

**Comment by hyeonjoongkim** [comment]
@aohlson Thank you! I was suspecting whether this is related to about last night's eos problem. The submission to grid didn't worked in this morning also.

**Comment by dberzano** [comment]
@aohlson the problem is not on your side, it's on ours. We are fixing it.

**Pull request merged**
