### PR TITLE
Changes in ThreePart code

### PR DESCRIPTION
**Pull request by pbatzing**
Incremental changes, forces warnings as errors in PWGCF/Correlations/ThreePart

### CODE REVIEW

**Comment by dberzano** [comment]
+test @pbatzing I am approving the testing only, but it's an already mentioned person that should finally approving the merge if they agree.

**Comment by qgp** [comment]
+1

**Comment by aiola** [comment]
It seems that this has broken compilation in macOS with clang 8.

[ 31%] Building CXX object PWGCF/Correlations/ThreePart/CMakeFiles/PWGCFCorrelationsThreePart.dir/AliAnalysisTaskBuildCorrTree.cxx.o
In file included from /Users/sa639/alice/sw/SOURCES/AliPhysics/root5/0/PWGCF/Correlations/ThreePart/AliAnalysisTaskBuildCorrTree.cxx:19:
/Users/sa639/alice/sw/osx_x86-64/AliRoot/root5-1/include/AliEventPoolManager.h:161:15: error: 'AliEventPool::Clear' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
  void        Clear();
              ^
/Users/sa639/alice/sw/osx_x86-64/ROOT/root5-1/include/TObject.h:108:24: note: hidden overloaded virtual function 'TObject::Clear' declared here: different number of parameters (1 vs 0)
   virtual void        Clear(Option_t * /*option*/ ="") { }
                       ^
In file included from /Users/sa639/alice/sw/SOURCES/AliPhysics/root5/0/PWGCF/Correlations/ThreePart/AliAnalysisTaskBuildCorrTree.cxx:24:
In file included from /Users/sa639/alice/sw/osx_x86-64/AliRoot/root5-1/include/AliAODInputHandler.h:14:
In file included from /Users/sa639/alice/sw/osx_x86-64/AliRoot/root5-1/include/AliAODEvent.h:32:
/Users/sa639/alice/sw/osx_x86-64/AliRoot/root5-1/include/AliAODCaloTrigger.h:43:35: error: variable 'j' used in loop condition not modified in loop body [-Werror,-Wfor-loop-analysis]
          if (i) {for (int j = 0; j < 2; i++) fL1DCALV0[j] = v[j];} else {for (int j = 0; j < 2; j++) fL1V0[j] = v[j];}
                                  ^
2 errors generated.
make[2]: *** [PWGCF/Correlations/ThreePart/CMakeFiles/PWGCFCorrelationsThreePart.dir/AliAnalysisTaskBuildCorrTree.cxx.o] Error 1
make[1]: *** [PWGCF/Correlations/ThreePart/CMakeFiles/PWGCFCorrelationsThreePart.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by adriansev** [comment]
if (i) {for (int j = 0; j < 2; i++)
                                    ^^^^ a big typo

**Comment by adriansev** [comment]
this typo i corrected in https://github.com/alisw/AliRoot/pull/89

**Comment by dberzano** [comment]
See #253.

**Pull request merged**
