### PR TITLE
Updating the analysis code for new analysis

### PR DESCRIPTION
**Pull request by suppathak**

### CODE REVIEW

**Comment by altsybee** [comment]
+1

**Comment by akubera** [comment]
+test

**Comment by aohlson** [comment]
+test

**Comment by suppathak** [comment]
The pull request was approved yesterday. All checks were passed. I was waiting for it to load into the master repository. 
But 17 hours ago, there was a error message, and all checks that were passed before, turned into failed. Therefore, I again made a new pull request.

**Comment by rbertens** [comment]
+1 @suppathak this PR was at first approved, but then not successfully tested. Afterwards, you have made additional commits, which have to be reviewed again then (so after a new commit, you need a new '+1' for the additional changes). Since testing went through, and to not slow down the work too much, i'll approve for now. Have a good weekend

**Pull request merged**
