### PR TITLE
Analysis task to select Xi and Omega candidates for flow analysis

### PR DESCRIPTION
**Pull request by yazhuCCNU**
Add code for Xi and Omega candidates flow analyisis

### CODE REVIEW

**Comment by akubera** [comment]
+test

**Comment by rbertens** [comment]
Hi @yazhuCCNU,

I have two comments for this PR: 

-> the FLOW/Base library is meant for code that only has ROOT dependencies (so that in principle the flow analysis algorithms can be used independent of AliRoot/AliPhysics). The better place for your task would be FLOW/Tasks, in which all AliRoot/AliPhysics dependencies are allowed;

->  if you want that your class is also compiled as part of the  PWGflowTasks library (now you add the code to the repository, but it will not be picked up by the compiler), you have to also add it to the compilation instructions in the relevant files (CMakeLists.txt and PWGflowTasksLinkDef.h , in the PWG/FLOW/Tasks folder)

Could you amend your PR so that the code will end up in the Tasks folder? 

Thanks,

Redmer

**Comment by yazhuCCNU** [comment]
Hi Redmer

Thank you for pointing out the mistake. I have change the path. and  modified  CMakeLists.txt and PWGflowTasksLinkDef.h 

Thanks,

Ya

**Comment by yazhuCCNU** [comment]
I don't If I should push request again?.I only do as following commond: git commit --amend

**Comment by rbertens** [comment]
+test

**Comment by rbertens** [comment]
@yazhuCCNU yes, you have to make a new request. That will then be merged with your open requests, and it can then be approved in one go.

**Comment by yazhuCCNU** [comment]
Thank you very much.

**Comment by rbertens** [comment]
Hi @yazhuCCNU ,
Will you still make the PR for the CMakeLists.txt ? 
Thanks,
Redmer

**Comment by yazhuCCNU** [comment]
Hi Redmer，

Yes, I will.


Cheers,

Ya

**Comment by rbertens** [comment]
+test

**Pull request closed without merging**
