### PR TITLE
new histo Et over M02 added

### PR DESCRIPTION
**Pull request by ReneChristianSchach**

### CODE REVIEW

**Comment by e-masson** [comment]
+test

**Comment by e-masson** [comment]
Hi @ReneChristianSchach, there were conflicts in your commit 03481b4. Did you manage to solve them? If so, I could approve the merging.
Best, Erwann

**Comment by ReneChristianSchach** [comment]
Yes, the problems were solved.

Regards,
Rene

**Comment by e-masson** [comment]
+1

**Pull request merged**
