### PR TITLE
Extend Run1 Pb-Pb cuts to LHC10h

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by cbourjau** [comment]
Thanks a lot for looking into this so quickly! May I suggest for the sake of API clarity to create a new method `SetupLHC10h` which just calles `SetupLHC11h` internally for now. This way, it is immediately clear what is going on and if dedicated cuts for either 10h or 11h become necessary in the future on can facilitate them without breaking user code. Just an idea. 
Cheers,
Christian

**Comment by fprino** [comment]
+1

**Comment by chiarazampolli** [comment]
Ciao @mpuccio ,

I think you forgot to change PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNntuple.cxx

Cheers,

Chiara

**Comment by chiarazampolli** [comment]
+1

**Pull request merged**
