### PR TITLE
Update ClassDef after yesterday PR

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @ddobrigk ,
this anyway should be done, now I check if indeed that was the issue!
Thanks!
Max

### CODE REVIEW

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
Yes, this looks like the issue indeed: the error message you got was indicative of a crazy data member content. Makes sense!

**Comment by ddobrigk** [comment]
(And of course I am very sorry that I forgot!!!)

**Comment by mpuccio** [comment]
No issue, if one uses a recent AliPhysics installation everything works correctly!

**Pull request merged**
