### PR TITLE
new task for hd analysis

### PR DESCRIPTION
**Pull request by loizides**

### CODE REVIEW

**Comment by efranzis** [comment]
+test

**Comment by loizides** [comment]
+test

**Comment by loizides** [comment]
@dberzano could you please have a look, seems not related to my task

**Comment by dberzano** [comment]
@loizides there was a major failure of the whole build infrastructure due to external causes. Yes, your error is clearly unrelated. Unfortunately I had to restart everything and it takes quite some time to complete. The error will recover automatically.

**Comment by efranzis** [comment]
+1

**Pull request merged**
