### PR TITLE
[EMCAL-143] [ALIROOT-7754] Move some macros and code from AliRoot to AliPhysics

### PR DESCRIPTION
**Pull request by gconesab**

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by gconesab** [comment]
+test

**Comment by gconesab** [comment]
@lcunquei or @dberzano 
can you approve the testing?

**Comment by dberzano** [comment]
+1

**Comment by gconesab** [comment]
Ummm, @dberzano 
are the checks done against master or v5-09-25?
If not master, can it be changed, maybe tagging v5-09-27?

**Comment by dberzano** [comment]
Automatic tests run against the latest tag, not master; let me merge it manually.

**Pull request merged**
