### PR TITLE
Update of class used in dimuon LMR analysis

### PR DESCRIPTION
**Pull request by bteyssie**
Update of LMR Analysis code for the normalization factor

### CODE REVIEW

**Comment by aphecetche** [comment]
+test

**Comment by aphecetche** [comment]
Hi,

What's the status here ? Are the test failing  because of that PR or because of the github issues of yesterday (June 5th,  21:10) ?

**Comment by dberzano** [comment]
Hi, if the system asks you to `+1` then the PR is fine for the system - this is why the red test is being ignored (it's optional). In any case we have disabled it from now on (until it turns green) to avoid confusion like in this case.

Note that our CI will never let you `+1` a truly failed PR. Even if you accidentally approve a PR whose tests fail, our system will ignore your approval.

**Comment by aphecetche** [comment]
+1

**Pull request merged**
