### PR TITLE
Use Qn = Qn/SumWgt for TPC EP, fix NUA,MC correction Paths

### PR DESCRIPTION
**Pull request by rihanphys**
Use Qn = Qn/SumWgt for TPC EP, fix NUA,MC correction Paths

### CODE REVIEW

**Comment by akubera** [comment]
+test

**Comment by rbertens** [comment]
+1

**Comment by rihanphys** [comment]
@rbertens  This error doen't seem to be coming from my AnalysisTask. Could you please confirm ?

**Comment by rbertens** [comment]
Hi @rihanphys , you are correct, see the discussion at #5064 , it should be taken care of soon.

**Comment by akubera** [comment]
+test

**Comment by dberzano** [comment]
This one was merged. If you have further modifications, open a new PR.

**Pull request merged**
