### PR TITLE
Flags for THnSparse creation and filling implemented

### PR DESCRIPTION
**Pull request by mfaggin**
When the ith flag is switched off, the ith THnSparse is neither created nor filled.
To guarantee backward compatibility, the default values for all these flags is kTRUE, namely the THnSparses are all created and filled

### CODE REVIEW

**Comment by chiarazampolli** [comment]
+test

**Comment by chiarazampolli** [comment]
Ciao @mfaggin , 

I thought that the THnSparse were already optional - or maybe some aspect of them was. I guess I am wrong... 

Cheers,

Chiara

**Comment by fprino** [comment]
+1

**Comment by mfaggin** [comment]
> Ciao @mfaggin ,
> 
> I thought that the THnSparse were already optional - or maybe some aspect of them was. I guess I am wrong...
> 
> Cheers,
> 
> Chiara

Hi @chiarazampolli ,
yes you are right, there were 4 or 5 THnSparses that were controlled by a single flag: when this is kTRUE, the sparses are created and filled.
What I did was to add a flag for all the THnSparses in the code, so that the user can decide exactly which THnSparses to create and fill.
I decided to do this because running on PbPb was giving huge merging problems, due to the huge THnSparses that sometimes were produced.
Anyway, I did the modification so that a backward compatibility is assured, then every user that used the task in the past can go on using it in the same way.

**Pull request merged**
