### PR TITLE
add pT histgram of jet constitutent

### PR DESCRIPTION
**Pull request by moeshita**

### CODE REVIEW

**Comment by sashingo** [comment]
+1

**Comment by ktf** [comment]
+test
@sashingo you are not among the people authorized to approve PRs, is that a mistake?

**Comment by sashingo** [comment]
@ktf HF converner added me as the authorized people last week.
Therefore I tried to approve.

**Comment by ktf** [comment]
As far as I can tell, only @btrzecia (Barbara Antonina Trzeciak) and @fcolamar (Fabio Colamaria) are authorised to approve the merge. Please have them comment with a plus one or have them ask for you to be added to the admins.

**Comment by ktf** [comment]
Ok, trying to see if this syncs correctly.

**Comment by ktf** [comment]
Mmm.... Maybe we need to a wait a bit more... :-( Merging this for now. Please open a test PR in a bit to check that you can actually +1 them.

**Pull request merged**
