### PR TITLE
Implemented comparison operator

### PR DESCRIPTION
**Pull request by rhaake**

### CODE REVIEW

**Comment by rhaake** [comment]
@mfasDa, what do you think?
I would like to use the operator for easily using std::sort.

**Comment by rhaake** [comment]
+test

**Comment by mfasDa** [comment]
Absolutely in favour of this. Not only this might be useful for std::sort but maybe also for other algorithms from the stl. Eventually an operator== should be added as well.

**Comment by rhaake** [comment]
+1

**Comment by rhaake** [comment]
+1

**Pull request merged**
