### PR TITLE
Bugs fixed

### PR DESCRIPTION
**Pull request by gskorodu**
1. Complementary classes (AliRunningCascadeEvent & AliRunningCascadeCandidate) are added to the PWGLFSTRANGENESSLinkDef.h
2. The Cascade z-component of DCA to the primary vertex is not saved any longer. Transverse component is enough.
3. TOF signal is stored as a float variable.
4. Cascade selection "clean up" (mass window) is added, this will reduce the output.

### CODE REVIEW

**Comment by gskorodu** [comment]
Dear @mlknichel, 
could you eventually comment with +test on my pull request?
Thanks in advance, 
Best regards, 
Georgijs

**Comment by BongHwi** [comment]
+test

**Comment by gskorodu** [comment]
Dear @BongHwi,
could you, please, merge these changes to the master?
Thank you for your help!
Cheers, 
Georgijs

**Comment by BongHwi** [comment]
+test

**Pull request merged**
