### PR TITLE
Update for Jet v2 analysis

### PR DESCRIPTION
**Pull request by SiyuTang**
Hi all,

Here is an update for jet v2 analysis, please check it. Thanks!

### CODE REVIEW

**Comment by SiyuTang** [comment]
Can someone help to approve the test for this commit? Thanks a lot!

**Comment by yzhouCERN** [comment]
+1

**Comment by yzhouCERN** [comment]
> Can someone help to approve the test for this commit? Thanks a lot!

Siyu, I help you to approve it here. But In general it's better to be approved by the Correlation experts, who are familiar with your work.
Cheers,
You

**Comment by SiyuTang** [comment]
> > Can someone help to approve the test for this commit? Thanks a lot!
> 
> Siyu, I help you to approve it here. But In general it's better to be approved by the Correlation experts, who are familiar with your work.
> Cheers,
> You

OK, thank you very much!  :)

**Pull request merged**
