### PR TITLE
Fix reordering AliMultSelectionTask

### PR DESCRIPTION
**Pull request by aaniin**
Fixed harmless reordering in ctor

Simply ordered the initialization of data members according to the class definition in the header. Also added the initialization of the fQuantiles array. 

Triggered by compiler warning:
```c++ 
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:100:114: warning: field 'fTrackCutsITSsa2010' will be initialized after field 'fUtils' [-Wreorder]
DEBUG:AliPhysics:0:     : AliAnalysisTaskSE(), fListHist(0), fTreeEvent(0),fESDtrackCuts(0), fTrackCuts(0), fTrackCutsGlobal2015(0), fTrackCutsITSsa2010(0), fUtils(0),
DEBUG:AliPhysics:0:                                                                                                                  ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:100:138: warning: field 'fUtils' will be initialized after field 'fkCalibration' [-Wreorder]
DEBUG:AliPhysics:0:     : AliAnalysisTaskSE(), fListHist(0), fTreeEvent(0),fESDtrackCuts(0), fTrackCuts(0), fTrackCutsGlobal2015(0), fTrackCutsITSsa2010(0), fUtils(0),
DEBUG:AliPhysics:0:                                                                                                                                          ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:128:7: warning: field 'fCurrentRun' will be initialized after field 'fMultiplicity_ADA' [-Wreorder]
DEBUG:AliPhysics:0:       fCurrentRun(-1),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:130:7: warning: field 'fMultiplicity_ADC' will be initialized after field 'fAmplitude_V0A' [-Wreorder]
DEBUG:AliPhysics:0:       fMultiplicity_ADC (0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:138:7: warning: field 'fAmplitude_OnlineV0C' will be initialized after field 'fAmplitude_V0A1' [-Wreorder]
DEBUG:AliPhysics:0:       fAmplitude_OnlineV0C(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:152:7: warning: field 'fnTracklets15' will be initialized after field 'fnSPDClusters0' [-Wreorder]
DEBUG:AliPhysics:0:       fnTracklets15(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:155:7: warning: field 'fnContributors' will be initialized after field 'fRefMultEta5' [-Wreorder]
DEBUG:AliPhysics:0:       fnContributors(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:169:7: warning: field 'fEvSel_HasGoodVertex2016' will be initialized after field 'fEvSel_VtxZ' [-Wreorder]
DEBUG:AliPhysics:0:       fEvSel_HasGoodVertex2016(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:237:119: warning: field 'fTrackCutsITSsa2010' will be initialized after field 'fUtils' [-Wreorder]
DEBUG:AliPhysics:0:     : AliAnalysisTaskSE(name), fListHist(0), fTreeEvent(0), fESDtrackCuts(0), fTrackCuts(0), fTrackCutsGlobal2015(0), fTrackCutsITSsa2010(0), fUtils(0),
DEBUG:AliPhysics:0:                                                                                                                       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:237:143: warning: field 'fUtils' will be initialized after field 'fkCalibration' [-Wreorder]
DEBUG:AliPhysics:0:     : AliAnalysisTaskSE(name), fListHist(0), fTreeEvent(0), fESDtrackCuts(0), fTrackCuts(0), fTrackCutsGlobal2015(0), fTrackCutsITSsa2010(0), fUtils(0),
DEBUG:AliPhysics:0:                                                                                                                                               ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:265:7: warning: field 'fCurrentRun' will be initialized after field 'fMultiplicity_ADA' [-Wreorder]
DEBUG:AliPhysics:0:       fCurrentRun(-1),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:267:7: warning: field 'fMultiplicity_ADC' will be initialized after field 'fAmplitude_V0A' [-Wreorder]
DEBUG:AliPhysics:0:       fMultiplicity_ADC (0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:275:7: warning: field 'fAmplitude_OnlineV0C' will be initialized after field 'fAmplitude_V0A1' [-Wreorder]
DEBUG:AliPhysics:0:       fAmplitude_OnlineV0C(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:289:7: warning: field 'fnTracklets15' will be initialized after field 'fnSPDClusters0' [-Wreorder]
DEBUG:AliPhysics:0:       fnTracklets15(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:292:7: warning: field 'fnContributors' will be initialized after field 'fRefMultEta5' [-Wreorder]
DEBUG:AliPhysics:0:       fnContributors(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:306:7: warning: field 'fEvSel_HasGoodVertex2016' will be initialized after field 'fEvSel_VtxZ' [-Wreorder]
DEBUG:AliPhysics:0:       fEvSel_HasGoodVertex2016(0),
DEBUG:AliPhysics:0:       ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx:352:7: warning: field 'fHistQASelected_NTracksGlobalVsCL1' will be initialized after field 'fHistQASelected_NTracksGlobalVsCL0' [-Wreorder]
DEBUG:AliPhysics:0:       fHistQASelected_NTracksGlobalVsCL1(0),
DEBUG:AliPhysics:0:       ^
```

### CODE REVIEW

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
Hi @aaniin , 

Thanks a lot for fixing these warnings! (and sorry that I missed them...) 

Cheers,
David

**Comment by aaniin** [comment]
@ddobrigk 

ooops, too fast. Sorry! Will you take this one? Log with -Wall is here:
http://www.physi.uni-heidelberg.de/~hbeck/AliPhysics-Wall-clang-Aug17.txt

Cheers!
Hans

**Comment by ddobrigk** [comment]
Hi Hans, 

Sure, no problem! I will take your changes and add the missing comma after 'fQuantiles{0.}' and do a pull request with all your changes from scratch. 

Thanks a lot! 
Cheers,
David

**Pull request closed without merging**
