### PR TITLE
A start of a dijet analysis AliJCDijet.

### PR DESCRIPTION
**Pull request by osaarima**
I have started a dijet analysis, where I reconstruct the jets using fastjet in the code.

### CODE REVIEW

**Comment by aohlson** [comment]
+test

**Comment by osaarima** [comment]
The test on my pc was succesfull, but the test on git failed on one occasion:
 1/99 Test #32: load_library_PWGCFCorrelationsJCORRANPro ......***Failed    0.94 sec

Processing /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/master-1/test/load_library/LoadLib.C("libPWGCFCorrelationsJCORRANPro")...
dlopen error: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/master-1/lib/libPWGCFCorrelationsJCORRANPro.so: undefined symbol: _ZTIN7fastjet25ClusterSequenceActiveAreaE
Load Error: Failed to load Dynamic link library /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/AliPhysics/master-1/lib/libPWGCFCorrelationsJCORRANPro.so
(Int_t)(-1)

Full log [here](https://ali-ci.cern.ch/repo/logs/alisw/AliPhysics/5605/dfc5e11abc550df8ae28d69065b578204ff51dd3/build_AliPhysics_release/fullLog.txt). It would seem that the problem is related to the linking of fastjet to my code. I checked the fastjet installation on my computer and on the output log of the test, there were some differences:

On my computer:
-- FastJet was compiled with CGAL
-- CGAL found in /home/osaarima/alice/sw/slc7_x86-64/cgal/v4.6.3-2
-- FastJet was compiled with GMP
-- GMP (static) found in /home/osaarima/alice/sw/slc7_x86-64/GMP/v6.0.0-1: not adding flags
-- FastJet was compiled witouth MPFR
-- FastJet options for ROOT dictionary generation: -I/home/osaarima/alice/sw/slc7_x86-64/fastjet/v3.2.1_1.024-alice3-1/include -rml libfastjetcontribfragile -rml libfastjetplugins -rml libsiscone_spherical -rml libsiscone -rml libfastjettools -rml libfastjet -rml libCGAL
-- FastJet 3.2.1 installation found: /home/osaarima/alice/sw/slc7_x86-64/fastjet/v3.2.1_1.024-alice3-1

In the git test:
-- FastJet was compiled with CGAL
-- CGAL found in /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/cgal/v4.6.3-3
-- FastJet was compiled with GMP
-- GMP (static) found in /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GMP/v6.0.0-1: not adding flags
-- FastJet was compiled witouth MPFR
-- FastJet options for ROOT dictionary generation:  -Doverride=
-- FastJet 3.2.1 installation found: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/fastjet/v3.2.1_1.024-alice3-2

Could the ROOT dictionary generation options be the main reason for this? Also the fastjet versions are a bit different, could there be a difference between versions alice3-1 and alice3-2 of fastjet?

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+1

**Pull request merged**
