### PR TITLE
Update ConfigFemtoAnalysis.C

### PR DESCRIPTION
**Pull request by prchakra**
Changing the z vertex cut, multiplicity bins and number of events to mix

### CODE REVIEW

**Comment by vpacik** [comment]
Hi @prchakra, isn't it duplicate to #11365?

**Comment by prchakra** [comment]
> Hi @prchakra, isn't it duplicate to #11365?

HI @vpacik, it's different from #11365. This one is for Pion-Kaon analysis but #11365 is for Pion-Proton analysis.

**Comment by vpacik** [comment]
+1

**Comment by vpacik** [comment]
@prchakra, sorry, my mistake, did not notice the change in full path.

**Pull request merged**
