### PR TITLE
Update my CME task for additional NUA+ Correction

### PR DESCRIPTION
**Pull request by rihanphys**
Update my CME task for additional NUA+ Correction

### CODE REVIEW

**Comment by yzhouCERN** [comment]
+test

**Comment by pchrista** [comment]
+1

**Comment by ktf** [comment]
Looks like there is something wrong indeed. Can anyone else but @pchrista do a +1?

**Comment by jgrosseo** [comment]
+1

**Comment by jgrosseo** [comment]
@ktf Strange...

**Pull request merged**
