### PR TITLE
Adapt to the latest treelite version

### PR DESCRIPTION
**Pull request by mpuccio**
This pr requires an AliRoot tag compiled with alisw/alidist#1957

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao @mpuccio , 
Should this fix the issue with the HF trains at some sites?
Chiara

**Comment by fcatalan92** [comment]
Ciao @chiarazampolli,
> Should this fix the issue with the HF trains at some sites?

probably yes. 
Treelite has been modified permitting to turn off OpenMP [dlmc/treelite/#135](https://github.com/dmlc/treelite/pull/135), which was our suspect for the library problems of HF trains. [alisw/alidist#1957](https://github.com/alisw/alidist/pull/1957) updates the treelite version used by ALICE and turn-off OpenMP. Finally, this PR adapt the current code to some unrelated changes than happened in treelite.

**Comment by chiarazampolli** [comment]
Thanks Max, I will give +1, but it will not be enough. @shahor02, can you approve?
Chiara

**Comment by chiarazampolli** [comment]
+1

**Comment by mpuccio** [comment]
Wait wait! Don't plus one now, we need alisw/alidist#1957 to be merged and a new tag of AliRoot

**Comment by chiarazampolli** [comment]
Ok, since there was no WIP, it looked ready to me.

**Comment by ktf** [comment]
+test

**Comment by mpuccio** [comment]
+1

**Pull request merged**
