### PR TITLE
Get centrality for Run2 pPb

### PR DESCRIPTION
**Pull request by hmurakam**
-added enum lhc16rst to AliConvEventCuts
-added lhc16qt to new framework (AliMultSelection) 
-now centrality histogram should be filled properly for those periods
-use V0M instead of V0A to get centrality (not consistent for Run1 pPb )
--might be better to use p-Pb -> V0A and Pb-p -> V0C ?, think later.

### CODE REVIEW

**Comment by dmuhlhei** [comment]
I think we should also update the classdef, could you please add that?

**Comment by hmurakam** [comment]
Hi Daniel, 
thank you for your comment. no it has changed.
Hikari

**Comment by FriederikeBock** [comment]
Could you also answer my question?
Regards,
Friederike

**Comment by hmurakam** [comment]
Hi Friederike,
thank you for your comments and sorry for my many commits. 
please let me know if there any problems. 
best regards, Hikari

**Comment by FriederikeBock** [comment]
+1 

Hi Hikari,
thanks for your contribution, having several commits is not a problem that what code review is for ;)
Regards,
Friederike

**Pull request merged**
