### PR TITLE
Update of the AliAnalysisMuMu framework

### PR DESCRIPTION
**Pull request by benjaminaudurier**
Implementation of the mixing event in AliAnalysisMuMu framework and fiew minor fixes.

### CODE REVIEW

**Comment by dstocco** [comment]
+test

**Comment by benjaminaudurier** [comment]
Add AliAnalysisMuMuTriggerResponse which was missing in the previous pull request

**Comment by dstocco** [comment]
+test

**Comment by benjaminaudurier** [comment]
Remove outdated method that was deleted in .cxx but not in the headers

**Comment by dberzano** [comment]
+test

**Comment by benjaminaudurier** [comment]
Remove outdated method that where note defined in the .cxx of AliAnalysisMuMuJpsiResults and

**Comment by dberzano** [comment]
+test

**Comment by aphecetche** [comment]
Hi Benjamin,

This is quite a giant pull request with all sorts of (possibly unrelated) things stuffed in (which, for one, makes it very difficult to review properly). For the record, I will approve it if you insist and have no time to split it into more manageable pieces, but I would _strongly_ advise against such requests in the future ... for your own good ;-)

**Comment by aphecetche** [comment]
+1

**Pull request merged**
