### PR TITLE
Allow CUSTOM_EXTERNAL build type

### PR DESCRIPTION
**Pull request by davidrohr**
AliPhysics version of this AliRoot PR: alisw/AliRoot#925

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by ktf** [comment]
+test

**Comment by davidrohr** [comment]
@pzhristov : This is the same change we did already for AliRoot. Are you OK with this?

**Comment by davidrohr** [comment]
Hi @shahor02: Could you also merge this.

**Comment by shahor02** [comment]
+1

**Pull request merged**
