### PR TITLE
Xic0SL tree update for decay mode separation

### PR DESCRIPTION
**Pull request by Chongk**
- Addressed pileup rejection in MC for pass2 migration
- Updated tree structure to properly separate each decay mode

### CODE REVIEW

**Comment by lvermunt** [comment]
Hi @Chongk, can you increment the ClassDef version? Then I approve.

**Comment by lvermunt** [comment]
+1

**Comment by Chongk** [comment]
Uh... I was about to ask how to merge another commit but it's already done.
Thanks, Luuk. :-)

**Comment by Chongk** [comment]
I'm sorry, Luuk. I hit "Close with comment" by mistake and this pull request was closed.
I reopened it by hitting it again, but I'm not sure if the previous test/merge statement is still valid.
If not, could you do it again? I'm sorry again.

**Pull request merged**
