### PR TITLE
Add new classes to facilitate event-by-event analysis

### PR DESCRIPTION
**Pull request by romainschotter**
Add new classes to facilitate event-by-event analysis in real and MC data : 
- 1 to contain event info (AliEventContainer and AliMCEventContainer),
- 1 to contain cascade info (AliCascadeContainer and AliMCCascadeContainer),
- 1 to contain V0 info (AliV0Container and AliMCV0Container),
- 1 to contain Track info (AliTrackInfoContainer and AliTrackInfoContainer),
- 1 to contain generated particle info (AliMCGenParticleContainer).

These classes have been implemented in the associated analysis tasks, namely AliAnalysisTaskStrangeCascadesTriggerAODRun2 and AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.

### CODE REVIEW

**Comment by romainschotter** [comment]
@lbarnby @alcaliva @dcolell @bianchil @bdoenigu @ddobrigk Can someone have a look at this PR ?

**Comment by ddobrigk** [comment]
Hi @romainschotter, this looks alright (but admittedly I did not do a super thorough review)! Just for completeness, though: I see the task you are modifying does not have a main developer clearly written at the top. Is that an analysis task you (mainly) developed? If not it would be good to find out who did and ask her/him to take a look, just for completeness.

**Comment by romainschotter** [comment]
Hi @ddobrigk, yes this analysis task is mainly -- if not exclusively -- developed by me. So even if something is wrong in my implementation, I guess this should bother anyone.
Should I be added as main developer ? If so, I admit that I don't know how to proceed...

**Comment by ddobrigk** [comment]
Hi @romainschotter, ah I see! Well, I would add a comment at the very top of the cxx file, maybe, just mentioning your name. Some may argue this is unnecessary (git always allows anyone to check, in principle) but my opinion in these matters is that it doesn't hurt to have this as a (meaningful!) comment in the code, too :-) 

In any case I think this is all fine then, and I will +1 in a moment :-D

**Comment by ddobrigk** [comment]
+1

**Pull request merged**
