### PR TITLE
Move YAML config class to PWG::Tools namespace

### PR DESCRIPTION
**Pull request by raymondEhlers**
Added to the namespace for safety

### CODE REVIEW

**Comment by mfasDa** [comment]
+1

**Comment by raymondEhlers** [comment]
@mfasDa - Any suggestions on how to resolve this? I tried to google around, but this seems to be a CINT problem, and I can't seem to fix it

**Comment by raymondEhlers** [comment]
Okay, I finally found the solution (resolved by moving operator<< back into the global namespace. see: https://stackoverflow.com/a/38801633) - it should be fixed now.

**Comment by aiola** [comment]
+1

**Pull request merged**
