### PR TITLE
Add HMPID to AO2D conversion

### PR DESCRIPTION
**Pull request by njacazio**
- Create dedicated table for HMPID in a separate tree

### CODE REVIEW

**Comment by njacazio** [comment]
@jgrosseo

**Comment by ktf** [comment]
Is this still relevant? If yes, could you clean up the conflicts?

**Comment by njacazio** [comment]
Sure, I will do it

**Comment by pzhristov** [comment]
+test

**Comment by pzhristov** [comment]
+1

**Pull request merged**
