### PR TITLE
Update AddTaskPIDBFDptDpt.C

### PR DESCRIPTION
**Pull request by panjinjin**
added multiplicity selection

### CODE REVIEW

**Comment by ktf** [comment]
+test

**Comment by dberzano** [comment]
Hi @panjinjin, I also see #232 and #233. Are you sure you don't want to make a _single_ pull request instead of three different ones?

**Comment by panjinjin** [comment]
Hi, @dberzano , thank you for asking! Yeah, I should have make #232 #233 #234 a single pull request. However, I haven't figure it out how to do that using this graphical interface. Could you please tell me how to do it? Thank you very much!

**Comment by dberzano** [comment]
Hi @panjinjin it's better if you do it from your computer. I suggest you to simply reset to the upstream master, and cherry-pick the three different commits, while closing the current PRs. You will open a new PR for clarity.

I suggest you do that in a new branch (in my example, called `new-feature`).

```
git checkout -b new-feature
git fetch --all
git reset --hard origin/master
git cherry-pick 341d61749c52ec0fc10832c2d20118613e389b67  # 232
git cherry-pick b5d00e1dc0efae5a23b5134a72d19a24831dc148  # 233
git cherry-pick 0488a5af3b44fb3afe0ef29727eb4f7cd1d20cbf  # 234
git push --set-upstream panjinjin new-feature
```

and then open a pull request.

Note that there is a "Close pull request" button at the end of each pull request that you can use for retiring them.

**Pull request closed without merging**
