### PR TITLE
Minor book-keeping

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by a-mathis** [comment]
@ktf I used to be able to accept pull requests to this repository, could you kindly take a look what happened? Maybe by mistake I removed myself from some e-group, which is the one relevant for this folder? Thanks a lot!

**Comment by ktf** [comment]
Looks like I cannot recreate it. Can you or one of the admin recontact service now?

**Comment by a-mathis** [comment]
@ktf Thanks a lot for taking a look! Dario used to create the e-group back then, who is the responsible I should contact now?

**Comment by ktf** [comment]
Mmm... probably @pzhristov. I opened a ticket in service now, let's follow it up there.

**Comment by a-mathis** [comment]
@ktf thanks a lot!

**Pull request merged**
