### PR TITLE
Tracking QA

### PR DESCRIPTION
**Pull request by aiola**

### CODE REVIEW

**Comment by aiola** [comment]
+1

**Comment by aiola** [comment]
+1

**Comment by aiola** [comment]
+1

**Comment by aiola** [comment]
+1

**Comment by aiola** [comment]
+1

**Comment by raymondEhlers** [comment]
Hi @aiola,

Seeing what you did here for the THnSparse, I think you might be curious about the THnSparse approach that I recently used in AliAnalysisTaskEmcalJetHPerformance. I basically use a map and a wrapper to allow a fill map from axis to value to be defined once in UserCreateOutputObjects. Then, I  select which axes to fill and how they are defined (binning, etc) in YAML. For the definition of the sparse, see [here](https://github.com/alisw/AliPhysics/blob/master/PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx#L250), and for filling it (I think this is is the nicest part), see [here](https://github.com/alisw/AliPhysics/blob/master/PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx#L408).

Best,
Raymond

**Comment by aiola** [comment]
Hi Raymond,
thanks, interesting approach! For the moment I just made few changes to resurrect an old task of mine, but I will definitely look into your approach if I need to expand it more.
Best,
Salvatore

**Comment by raymondEhlers** [comment]
Hi @aiola ,

Of course - just wanted to make the suggestion for the future!

Best,
Raymond

**Pull request merged**
