### PR TITLE
PWGPP/EMCAL: add trigger selection Pi0Calib

### PR DESCRIPTION
**Pull request by EwaGlimos**

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by mfasDa** [comment]
Not sure this is of relevance but as far as I recall we also took data with 0EMC/0DMC, those have only EMCAL in readout as EMCAL was in PHYSICS2 and no tracking/trigger detectors. The physics selection should identify them as kEMC7. Not sure you want to add them.

**Comment by gconesab** [comment]
> Not sure this is of relevance but as far as I recall we also took data with 0EMC/0DMC, those have only EMCAL in readout as EMCAL was in PHYSICS2 and no tracking/trigger detectors. The physics selection should identify them as kEMC7. Not sure you want to add them.

Well, the calibration data was always taken with kEMC7, so I would think it should be considered

**Comment by EwaGlimos** [comment]
> Not sure this is of relevance but as far as I recall we also took data with 0EMC/0DMC, those have only EMCAL in readout as EMCAL was in PHYSICS2 and no tracking/trigger detectors. The physics selection should identify them as kEMC7. Not sure you want to add them.

I had some problems with getting a proper response from the Physics Selection. I believe the workaround I implemented should include also those events for the EMC7

**Comment by FriederikeBock** [comment]
+1

**Pull request merged**
