### PR TITLE
Test nDim Fits for TPC Splines

### PR DESCRIPTION
**Pull request by alcaliva**
Test Multi-dimensional parametrization of TPC dE/dx

### CODE REVIEW

**Comment by wiechula** [comment]
+1

**Comment by alcaliva** [comment]
I have added the missing entry in PWGPP/CMakeLists.txt

**Comment by wiechula** [comment]
+test

**Comment by wiechula** [comment]
@alcaliva ,
in CMakeLists.txt there are quite many changes which don't belong to your modification. I think something went wrong here. Please check.

**Comment by alcaliva** [comment]
I fixed the CMakeList.txt file

**Comment by miranov25** [comment]
+Test

**Comment by ktf** [comment]
+test

**Comment by bdoenigu** [comment]
+1

**Pull request closed without merging**
