### PR TITLE
Update AliAnalysisTaskNetLambdaTrad.cxx: Update cuts

### PR DESCRIPTION
**Pull request by eumaka**

### CODE REVIEW

**Comment by eumaka** [comment]
Can someone kindly merge this pull request

**Comment by aohlson** [comment]
+1

**Comment by rbertens** [comment]
+1 hi @eumaka , @majanik already gave a '+1' two days ago, no idea why it didn't merge. Let's try again :) !

**Comment by eumaka** [comment]
Thanks!

**Pull request merged**
