### PR TITLE
Update for HM trigger in AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx

### PR DESCRIPTION
**Pull request by dkaratov**
Adding a command to override automatic trigger selection from fEventCuts to get all the kHighMultV0 triggered events.

### CODE REVIEW

**Comment by ddobrigk** [comment]
@dkaratov this is great! Did you test this already? Thanks!!!

**Comment by ddobrigk** [comment]
Ah wait a second - @dkaratov I think you have two spurious text files with some nonsense in them that went together with this PR. Can you please remove them? Thanks!

**Comment by ddobrigk** [comment]
In case it helps, @dkaratov https://github.com/alisw/AliPhysics/pull/22665 here is only the change you meant to do :-D

**Comment by ddobrigk** [comment]
Hi @dkaratov the change you wanted has been merged already so I think this PR can be closed. Can you close it please? Thanks a lot! :-D

**Comment by dkaratov** [comment]
Hi @ddobrigk , I tested it locally and it works. Yes, sorry about the extra text files, that is something left from long time ago, I overlooked it.

**Pull request closed without merging**
