### PR TITLE
Added a new Method to the bad channel code that scales the hits/event…

### PR DESCRIPTION
**Pull request by jokonig**
… of each cell according to the cells position on the detector. This makes the masking of channels more precise than without the scaling. Also a new method that identifies bad cells by their time distribution was implemented.

### CODE REVIEW

**Comment by dberzano** [comment]
+test

**Comment by gconesab** [comment]
+1

**Comment by mpuccio** [comment]
Hi, this PR breaks the AliPhysics compilation on mac (at least for me). Here the error:
```
/Users/mpuccio/alisw/sw/SOURCES/AliPhysics/0_ROOT6/0/PWGPP/EMCAL/BadChannelAna.cxx:773:26: error: variable-sized object may not be initialized
        Double_t arrHits[fNoOfCells] = {0.};
                         ^~~~~~~~~~
/Users/mpuccio/alisw/sw/SOURCES/AliPhysics/0_ROOT6/0/PWGPP/EMCAL/BadChannelAna.cxx:795:32: error: variable-sized object may not be initialized
        Int_t fFlag_forScaling[fNoOfCells] = {0};

```

**Comment by jokonig** [comment]
Hi, sorry for this mistake!
I changed it to: Double_t *arrHits = new Double_t[fNoOfCells];
                         TVectorD fFlagForScaling;
                         fFlagForScaling.ResizeTo(fNoOfCells);
I think this should work. I made a new pull request.

**Pull request merged**
