### PR TITLE
added toy to randomly place soft particles to jet in recursive parents

### PR DESCRIPTION
**Pull request by haandrew**

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+test

**Comment by haandrew** [comment]
Hi @mfasDa ,

There were some whitespace conflicts when I tried to rebase origin master. I tried to just checkout the remote version in HEAD to resolve the conflicts temporarily but it then recommended that I skip the patch in the rebase. But it told me my current branch master was up to date so then I pushed again... not sure if that's worked or not though... Let me know if there is anything else

**Comment by mfasDa** [comment]
+test

**Comment by haandrew** [comment]
Hi @mfasDa ,

I have done as you suggested. Thanks for the clear instructions! I have a corrupted AliRoot git repository which is causing me some issues with doing the build tests locally. I'm working on it but it's taking longer than I'd hoped and I just wanted to get this PR through.

Thanks a lot!

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
Hi @haandrew ,

In case you have a corrupted history in your local repository you can do the following once the commit is merged by the alibot into master in order to repair your master branch: You reset master by a certain amount of commits, let's say 100 for example, by `git reset --hard HEAD~100`, and then pull again from origin  with `git pull origin master`. After this the branch should be in sync again with origin master, which by now contains your commits as well. Don't forget to do a `git push -f yourremote master` to synchronize your github master as well.

Cheers

Markus

**Comment by haandrew** [comment]
Hi @mfasDa 

So I had already made my own attempt at fixing the issue by cloning a new git repository and replacing the corrupted one. I now have an uncorrupted repository that is up to date with master but I now get CMake errors when I try and install the changes. I have contacted the offline team for some more help.

Thanks for the advice,

Harry

**Comment by mfasDa** [comment]
Hi @haandrew,

I saw your post on the analysis task force mailing list. Your CMakeError comes from a repository split done at the end of last week (outsourcing of the HLT TPC calibration code into a separate package in order to be able to use it both in AliRoot and o2). As this is a new package you need to update your alidist (with the new package and the updated dependencies) and rebuild AliRoot/AliPhysics.

Cheers

Markus

**Pull request merged**
