### PR TITLE
Enhance pair QA

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by a-mathis** [comment]
+1

**Comment by a-mathis** [comment]
@ktf It appears the builds are stuck looking at the reports here: 
build/AliPhysics/root6  Building since 2020-11-11 15:50 UTC on alibuild01.cern.ch 

Could you have a look? Thanks!

**Comment by ktf** [comment]
@TimoWilken could you check what is going on?

**Comment by TimoWilken** [comment]
@ktf @a-mathis I see this error in the logs:
```
Using cached build for GSL
Building GSL@v1.16
ERROR: Error while executing .../aliphysics-root6/sw/SPECS/slc7_x86-64/GSL/v1.16-61/build.sh on `alibuild01.cern.ch'.
ERROR: Log can be found in .../aliphysics-root6/sw/BUILD/GSL-latest/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is .../aliphysics-root6/sw/BUILD/GSL-latest/GSL.
```
I've turned debug mode on now, so hopefully more helpful messages will follow soon.

**Comment by a-mathis** [comment]
@ktf @TimoWilken Any news on this? This PR is just about an AddTask which isn't even compiled

**Comment by a-mathis** [comment]
+1

**Comment by a-mathis** [comment]
@ktf @TimoWilken This is just a modification in the AddTask which is not even compiled, furthermore the logs are empty. Could you kindly have another look please?

**Pull request merged**
