### PR TITLE
restore old and p_T independent pre-selections, store 20% like-sign background in ML output

### PR DESCRIPTION
**Pull request by zhujh126**

### CODE REVIEW

**Comment by fcatalan92** [comment]
Hi @zhujh126, large part of your changes are commented. Is this intended?

**Comment by fcatalan92** [comment]
+test

**Comment by zhujh126** [comment]
> Hi @zhujh126, large part of your changes is commented. Is this intended?

Hi @fcatalan92 , yes, this is intentional. The new cuts don't work well.

**Comment by fcatalan92** [comment]
+1

**Pull request merged**
