### PR TITLE
PWG/EMCAL: Added new function for NCell efficiency and modified energy fine tuning for 1 cell clusters

### PR DESCRIPTION
**Pull request by jokonig**
New function for NCell efficiency based on (PCM-EMC) pi0 tagged photon clusters. 
Added a switch for th NCell efficiency to apply it only on photon clusters if wanted.
Added special treatment for 1 cell clusters in the MC cluster energy fine tuning, because non-linearity for 1 cell clusters different than for >= 2 cell clusters.

In PWGGA/GammaConv: 
Modified configs for PCM-EMC and EMC to check implementation in CF vs in AliCaloPhotonCuts
Modified (and simplified) Non-Linearity for 1 cell clusters in AliCaloPhotonCuts

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by jokonig** [comment]
Could someone have a look at this PR?

**Comment by gconesab** [comment]
I am fine with the changes in the files I handle, I let others approve, comment.

**Comment by FriederikeBock** [comment]
+1

**Pull request merged**
