### PR TITLE
analysis code of stongly intensive and FB correlations

### PR DESCRIPTION
**Pull request by isputows**
class to analysis FB correlations and strongly intensive quantities. 
Added header and body files with add task macro.

### CODE REVIEW

**Comment by aohlson** [comment]
+1

**Comment by aohlson** [comment]
Hi Iwona, 
I approved your pull request before realizing that it is a new class.  So your code is committed succesfully, but it will not be compiled within AliPhysics until your task name is added to the files CMakeLists.txt and PWGCFebyeLinkDef.h.  Could you make a new pull request with the appropriate lines added to those files?  
Thanks, and cheers, 
Alice

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+1

**Comment by mfasDa** [comment]
@isputows @aohlson This commit breaks the library tests due to undefined symbols of the streamer of class LRCParticle. Also be aware that a class with the same name is already defined elsewhere in AliAnalysisTaskLongRangeCorrelations.h.

**Comment by ktf** [comment]
Indeed I had to revert this. Not sure how it was possible that it got merged.

**Pull request merged**
