### PR TITLE
EMCal Embed: Improve recording of event properties

### PR DESCRIPTION
**Pull request by raymondEhlers**
Includes:
- A new class to record embedded properties after event selection
- Update jet response maker to use the class when using the new framework (enabled automatically only if the embedding helper has been created).
- Count number of embedded files
- Other small improvements (see commit messages for more)

### CODE REVIEW

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
@raymondEhlers it seems you have a typo : THistMAnager.h -> THistManager.h
was this code compiled successfully on your system?

**Comment by rbertens** [comment]
Hi @adriansev , @raymondEhlers 
This is something that can easily go unnoticed on Mac OS, or other system where file names are case-insensitive ...

**Comment by adriansev** [comment]
@rbertens oh, i see! thanks for info!

**Comment by raymondEhlers** [comment]
@rbertens is right - I'm on Mac OS, so this compiled without any warnings. I just pushed the fix!

**Comment by rbertens** [comment]
+test

**Comment by raymondEhlers** [comment]
Hi @rbertens,

Can I ask you a favor to +1 this now so it gets in for the tag? I'd really like to get this in before then, and I already have commit rights for PWG/EMCAL, so this approval really only covers the small changes to AliJetResponseMaker.* .

Thanks for considering!

Best,
Raymond

**Comment by rbertens** [comment]
+1 hi @raymondEhlers , i hope this +1 still comes in time for the tag!

**Comment by adriansev** [comment]
+test

**Comment by aiola** [comment]
+1

**Comment by raymondEhlers** [comment]
Thanks to everyone for their efforts! Sadly, I suspect that we just missed the tag, but that was my fault - I probably should have made my intended timeline clearer.

@rbertens I just noticed that I don't see you on the approvers list (since I have commit rights to PWG/EMCAL, I guess this list corresponds to PWGJE/EMCALJetTasks) - you might want to check on this?

**Comment by rbertens** [comment]
Hi @raymondEhlers , yes, you're right, actually it didn't feel it appropriate any more to have rights here because I do not develop enough in this folder. But then then, after writing a comment to the commit, my brain decided to forget this and add a pointless '+1' as old habits die hard ...

**Comment by adriansev** [comment]
+1

**Comment by raymondEhlers** [comment]
@rbertens Ah, okay, makes sense! Thanks for your help!

@adriansev Thank for your help in getting this committed! It seems that it made it into the additional tag of AliRoot + AliPhysics today, so things worked out okay! :-)

**Pull request merged**
