### PR TITLE
PWGDQ: Initial commit of new electron efficiency task

### PR DESCRIPTION
**Pull request by carstooon**
Initial commit of completely new designed efficiency task

### CODE REVIEW

**Comment by pdillens** [comment]
+1

**Comment by victor-gonzalez** [comment]
It seems this pull request is preventing AliPhysics today's tag compilation!
Could you please have a look at it?
Thanks!

**Comment by carstooon** [comment]
Hi,
I am having a look into it. Can you give me a hint?
On my computer, gcc4.9, it compiles without any problems.

Cheers

**Comment by victor-gonzalez** [comment]
I get this error compiling today's tag (my compiler is gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609, could that be the reason?, but someone else got the error with High Sierra also)

```
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'ROOT::TGenericClassInfo* ROOTDict::GenerateInitInstanceLocal(const std::vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7430:68: error: within this context
static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7432:7: error: within this context
vector<AliAnalysisTaskElectronEfficiencyV2::Particle> *ptr = 0;
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7433:69: error: within this context
static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<AliAnalysisTaskElectronEfficiencyV2::Particle>),0);
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7436:26: error: within this context
typeid(vector<AliAnalysisTaskElectronEfficiencyV2::Particle>), ::ROOT::DefineBehavior(ptr, ptr),
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7438:26: error: within this context
sizeof(vector<AliAnalysisTaskElectronEfficiencyV2::Particle>) );
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7444:112: error: within this context
instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<AliAnalysisTaskElectronEfficiencyV2::Particle> >()));
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: At global scope:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7448:91: error: within this context
static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)0x0); R__UseDummy(_R__UNIQUE_(Init));
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void ROOTDict::vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR_Dictionary()':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7452:52: error: within this context
::ROOTDict::GenerateInitInstanceLocal((const vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)0x0)->GetClass();
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void* ROOTDict::new_vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR(void*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7460:57: error: within this context
return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<AliAnalysisTaskElectronEfficiencyV2::Particle> : new vector<AliAnalysisTaskElectronEfficiencyV2::Particle>;
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7460:117: error: within this context
return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<AliAnalysisTaskElectronEfficiencyV2::Particle> : new vector<AliAnalysisTaskElectronEfficiencyV2::Particle>;
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void* ROOTDict::newArray_vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR(Long_t, void*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7463:56: error: within this context
return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<AliAnalysisTaskElectronEfficiencyV2::Particle>[nElements] : new vector<AliAnalysisTaskElectronEfficiencyV2::Particle>[nElements];
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7463:127: error: within this context
return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<AliAnalysisTaskElectronEfficiencyV2::Particle>[nElements] : new vector<AliAnalysisTaskElectronEfficiencyV2::Particle>[nElements];
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void ROOTDict::delete_vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR(void*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7467:16: error: within this context
delete ((vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)p);
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void ROOTDict::deleteArray_vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR(void*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7470:19: error: within this context
delete [] ((vector<AliAnalysisTaskElectronEfficiencyV2::Particle>*)p);
^
In file included from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.h:68:0,
from /local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:17:
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h: In function 'void ROOTDict::destruct_vectorlEAliAnalysisTaskElectronEfficiencyV2cLcLParticlegR(void*)':
/local/alice/sw/SOURCES/AliPhysics/alimaster/0/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h:108:9: error: 'class AliAnalysisTaskElectronEfficiencyV2::Particle' is private
class Particle{
^
/local/alice/sw/BUILD/bef315d79a4b5d31a629aea89b48d0009fdf4c42/AliPhysics/PWGDQ/dielectron/G__PWGDQdielectron.cxx:7473:15: error: within this context
typedef vector<AliAnalysisTaskElectronEfficiencyV2::Particle> current_t;
^
[ 28%] Building CXX object PWGCF/Correlations/DPhi/CMakeFiles/PWGCFCorrelationsDPhi-object.dir/Unfoldedhistos/AliCSTrackCutsBase.cxx.o
[ 28%] Building CXX object PWGCF/Correlations/DPhi/CMakeFiles/PWGCFCorrelationsDPhi-object.dir/Unfoldedhistos/AliCSTrackCuts.cxx.o
PWGDQ/dielectron/CMakeFiles/PWGDQdielectron-object.dir/build.make:1295: recipe for target 'PWGDQ/dielectron/CMakeFiles/PWGDQdielectron-object.dir/G__PWGDQdielectron.cxx.o' failed
make[2]: *** [PWGDQ/dielectron/CMakeFiles/PWGDQdielectron-object.dir/G__PWGDQdielectron.cxx.o] Error 1
CMakeFiles/Makefile2:9468: recipe for target 'PWGDQ/dielectron/CMakeFiles/PWGDQdielectron-object.dir/all' failed
make[1]: *** [PWGDQ/dielectron/CMakeFiles/PWGDQdielectron-object.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by carstooon** [comment]
Hey,
thanks for the info. I try to reproduce your error.
Do you compile against root5 or root6? I use root5.

I think whats causing problems is the use of a class in a class. Could it be that this is not supported by some compiler/OS/whatever systems?
Cheers

**Comment by victor-gonzalez** [comment]
root5. 
I also use root6 but haven't tried today's tag with it yet.
I believe is more the root serialization machinery which probably is not properly adapted yet to private embedded classes and its implementation is caught by the new compiler versions but tolerated by the previous ones.

**Comment by pzhristov** [comment]
Hi,

The problem is that the class Particle is private but is used in a
public method of the containing class. The following two line change
fixes it:

diff --git a/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
b/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
index 29bef503c6..4fae75796a 100644
--- a/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
+++ b/PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
@@ -104,7 +104,7 @@ public:
    void   AddTrackCuts(AliAnalysisFilter* filter)
{fTrackCuts.push_back(filter);}
 
 
-private:
+public:
   class Particle{
   public:
     Particle() :
@@ -125,6 +125,7 @@ private:
     std::vector<Bool_t> isMCSignal;
     std::vector<Bool_t> isReconstructed;
   };
+private:
   enum {kAllEvents=0, kPhysicsSelectionEvents, kFilteredEvents ,
kCentralityEvents, kLastBin};
 
   void    SetBinsLinear(const std::string variable, const double min,
const double max, const unsigned int steps);

I will make a pull request in a moment.


Cheers,

Peter

**Comment by carstooon** [comment]
Hello Peter,
thank you for spotting and fixing this bug!!

Do you have an idea why this bug does not affect me? I would like to not do the same mistake again.
I tested this task with jobs on the grid and did not experience problems.

Cheers
Carsten

**Comment by pzhristov** [comment]
Hi Carsten,

I observe this issue with Root6 in the compilation of the dictionary.
Root5 uses a trick

#define private public

which probably masks the problem.

Cheers,
Peter

**Comment by victor-gonzalez** [comment]
Which probably, as Peter says, masks it for your compiler version but not for mine.
Makes sense!
Thanks!
Cheers,
Víctor.

**Comment by carstooon** [comment]
Thank you for the explanation.
But nevertheless I think that "#define private public" is a very _special_ thing to do.

Cheers
Carsten

**Pull request merged**
