### PR TITLE
fix(PWGCF): changing counter type to double

### PR DESCRIPTION
**Pull request by pkarczma**
This fix allows to sum entries with non-unitary weights, which may happen depending on what exactly a user asks for.

### CODE REVIEW

**Comment by pkarczma** [comment]
@jgrosseo please have a look if this is fine

**Comment by jgrosseo** [comment]
That's look fine to me

**Comment by jgrosseo** [comment]
+1

**Comment by jgrosseo** [comment]
@TimoWilken Is this a known issue or related to the fact that this was a draft PR first (which triggered wrong comments from alibuild above)?

**Comment by TimoWilken** [comment]
@jgrosseo the failing builds are due to GNOME's GitLab being down (so we can't fetch libxml2). I can look into the wrong comments.

**Pull request merged**
