### PR TITLE
Including desciption about EMCAL OADB in doxygen

### PR DESCRIPTION
**Pull request by mfasDa**
Linking doxypage with description about accessing the EMCAL
OADB under the EMCAL core framework.

### CODE REVIEW

**Comment by mfasDa** [comment]
@dberzano In the global part this adds only OADB/EMCAL to the doxyfile since the authors wanted the file to be in that directory.

**Comment by mfasDa** [comment]
+1

**Comment by mfasDa** [comment]
These are basically the changes I requested in #4213

**Comment by mfasDa** [comment]
+1

**Comment by dberzano** [comment]
+1

**Pull request merged**
