### PR TITLE
bug fix in AliAnalysisTaskCMEMC.cxx (2nd)

### PR DESCRIPTION
**Pull request by rihanphys**
bug fix in AliAnalysisTaskCMEMC.cxx (2nd)

### CODE REVIEW

**Comment by dcaffarr** [comment]
+test

**Comment by pchrista** [comment]
+1

**Comment by akubera** [comment]
Note, you don't have to close a pull request to make a change, you can just push to the same branch, or edit your commit tree with rebase and do a `git push --force` and it will update the PR.

**Comment by vpacik** [comment]
+1

**Pull request merged**
