### PR TITLE
add rho histograms vs TT and fine-binned pt vs dphi histogram

### PR DESCRIPTION
**Pull request by jaimenorman**
- add histograms to to study TT bias in rho
- add fine-binned pt vs dphi histogram to allow for 'shift' in rho if needed.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+1

**Comment by jaimenorman** [comment]
@raymondEhlers I pushed an additional commit - could I get approval again on this pull request? 

Thanks!

**Comment by raymondEhlers** [comment]
+1

**Comment by jaimenorman** [comment]
@raymondEhlers thanks for the quick +1!

**Pull request merged**
