### PR TITLE
AliAnalysisTaskEmcalJetCDF updates

### PR DESCRIPTION
**Pull request by adriansev**

### CODE REVIEW

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
@dberzano It seems that there is a problem with build/AliPhysics/release build machine ... can i re-trigger just the build for build/AliPhysics/release or the recovery must be done by you? Thanks!!

**Comment by dberzano** [comment]
I am aware of the bizarre issue, let me take care of it.

**Comment by dberzano** [comment]
Could you maybe update the PR in the meanwhile? Like this, when I restart the workers, it will not schedule your PR at the end.

**Comment by adriansev** [comment]
@dberzano How can i update the PR? should i make a whitespace commit in the branch?

**Comment by dberzano** [comment]
I believe that a `git commit --amend` and a force-push are sufficient. You change the commit timestamp, therefore you change the hash.

**Comment by adriansev** [comment]
+test

**Comment by dberzano** [comment]
OK thanks. Note that it will take a long while, unfortunately. The workers are up now.

**Comment by adriansev** [comment]
+1

**Pull request merged**
