### PR TITLE
Small fix to add back the name of the origin and hmpid trees

### PR DESCRIPTION
**Pull request by iarsene**

### CODE REVIEW

**Comment by iarsene** [comment]
@jgrosseo This is the fix i was mentioning in mattermost

**Comment by jgrosseo** [comment]
+1

**Comment by iarsene** [comment]
The error is unrelated to this PR

**Comment by jgrosseo** [comment]
@TimoWilken Can you check why we get this unrelated error?

**Comment by TimoWilken** [comment]
@jgrosseo that was a problem with FLUKA that was fixed recently, as far as I know -- please let me know if you see this error again.

**Pull request merged**
