### PR TITLE
Pi0Cand binning adjustment

### PR DESCRIPTION
**Pull request by moliver813**
Adjust binning for a few axes of the Pi0Cand THnSparse.

### CODE REVIEW

**Comment by efranzis** [comment]
+test

**Comment by efranzis** [comment]
+1

**Comment by efranzis** [comment]
Does anyone know what the problem with this commit is?

**Comment by moliver813** [comment]
I am unable to find the logfile that is linked there.

**Comment by gconesab** [comment]
Maybe @dberzano knows and this is just a glitch in the system?

**Comment by gconesab** [comment]
+1
but now I see it approved, let's see

**Comment by dberzano** [comment]
Yes sometimes we have glitches with empty logfiles, they clear out automatically. Sorry about that.

**Pull request merged**
