### PR TITLE
New pass2-based LHC15o calib, V0fix HIJING MC

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf , @MichaelLettrich , 

The test fails, but I don't see any useful information in the "Details". 
@ddobrigk , I would merge by hand. 
The new file will cover also pass1, right? Just to be sure.

Cheers,

Chiara

**Comment by ddobrigk** [comment]
Hi @chiarazampolli, 

Yes, this covers pass1 too. BTW I have been getting these build problems (it shows the build is in error, but "Details" shows no error) since a few PRs already... I guess it's a system malfunction... 

Thank you! 
Ciao,
David

**Comment by TimoWilken** [comment]
@chiarazampolli Sorry, that's a known problem. We've been having intermittent trouble authenticating with the CERN GitLab to download a build dependency, there's a ticket open with CERN IT. I'll mark the test as pending so it gets picked up again sooner, hopefully it'll work next time.

**Comment by chiarazampolli** [comment]
Thanks @TimoWilken ! I am merging by hand, so that the commit goes in todays' analysis tag.
Chiara

**Pull request merged**
