### PR TITLE
Updating the class version

### PR DESCRIPTION
**Pull request by e-masson**

### CODE REVIEW

**Comment by dlodato** [comment]
Hi @e-masson, 
is this related to the previous commit, where you introduced a flag to listen the output?

**Comment by dlodato** [comment]
+test

**Comment by e-masson** [comment]
Hi @dlodato,
Exactly, the change was too important to run an analysis on grid with this new feature and no updated class version.
Best, Erwann

**Comment by dlodato** [comment]
+1

**Pull request merged**
