### PR TITLE
Bugfix in ZDC treatment in AODs (for ESD/AOD consistency)

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
+1

**Comment by ddobrigk** [comment]
+1

**Comment by dberzano** [comment]
Hello @ddobrigk, I have manually merged this one by mistake - unfortunately there is an error (which for some reason has not been displayed in the comment) and I am reverting it. Can you open a new pull request? The full log for the error is accessible.

**Comment by ddobrigk** [comment]
Hi Dario, 

Sorry for the inconvenience: I've now fixed the problem. I actually don't understand how I did not detect it in my local build somehow (which worked flawlessly). I also didn't get any error message from the tests here (at least not in the first ~20h after I committed), which made me think everything was fine... Sorry! 

Many many thanks!
Cheers,
David

**Comment by dberzano** [comment]
Hi @ddobrigk, we've had a glitch in our infrastructure, it's really not your fault! See, nobody's perfect, this is why we need automatic tests :-)

**Pull request merged**
