### PR TITLE
Make TArray class mebers object members

### PR DESCRIPTION
**Pull request by mfasDa**
- Change TArray pointer class members to object
  class members
- Use TArrayL64 for PAR event array instead of
  c-style dynamic array

### CODE REVIEW

**Comment by mfasDa** [comment]
+test

**Comment by mfasDa** [comment]
@gconesab Any objection

**Comment by mfasDa** [comment]
Reason for commit (in addition to automatic memory management by TArray): Streamer error introduced in #11882.

**Comment by gconesab** [comment]
> @gconesab Any objection

I guess I am ok.
+test

**Comment by ktf** [comment]
@gconesab do not forget to +1 this.

**Comment by mfasDa** [comment]
+1

@ktf Thanks for the reminder!

@gconesab I think it was now open long enough for review - I checked that the code works, I think it is fine to merge it now.

**Pull request merged**
