### PR TITLE
Expansion of the AODTrackFilter task to handle pt-dependent tracking efficiency

### PR DESCRIPTION
**Pull request by ChrisPliatskas**
Update of track filter task to include pt-dependent tracking efficiency variation. Code snippets replicated from AliEmcalJetTask parent class.

### CODE REVIEW

**Comment by raymondEhlers** [comment]
Do you want to add a method for initializing the TF1 from the yaml file? If not, you'll have to do all of that you in the configuration of your addtask macro, which may not be so nice / repeatable (you should also consider double checking the streamers?)

**Comment by ChrisPliatskas** [comment]
Hi @raymondEhlers, thank you for the comment. Indeed I was mistaken about the inheritance of the class. I added the methods which are needed for the yaml configuration based on the AliEmcalJetTask.

**Comment by raymondEhlers** [comment]
Hi @ChrisPliatskas , please check your commit - you somehow moved the files to `PWG/EMCAL/AliEmcalAodTrackFilterTask.{cxx,h}` from `PWG/EMCAL/EMCALtasks/AliEmcalAodTrackFilterTask.{cxx,h}`, which I can't imagine you meant to do

**Comment by raymondEhlers** [comment]
Thanks, looks like it's almost there. Please squash the commits down into one commit

**Pull request closed without merging**
