### PR TITLE
Add CALO triggers

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* EMCAL bits, classes and online
* DCAL bits, classes and online

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@qgp @ginnocen here are the extension for EMCAL and DCAL triggers

**Comment by benedikt-voelkel** [comment]
Hello @mfasDa 
With this PR we want to add the extraction of EMCAL and DCAL trigger flags and corresponding online info from the detector inputs. Can you confirm the correctness of the class names for both?
Thanks a lot!

**Comment by qgp** [comment]
+test

**Comment by qgp** [comment]
+1

**Comment by mfasDa** [comment]
@benedikt-voelkel I had a look at your code and the selection of the EMCAL jet triggers looks OK.

**Comment by benedikt-voelkel** [comment]
Hej @mfasDa 
Thanks a lot for the feedback :)

**Pull request merged**
