### PR TITLE
Added deuteron functionality to ITS3 improver task

### PR DESCRIPTION
**Pull request by mbucklan**

### CODE REVIEW

**Comment by arossi81** [comment]
Hi @mbucklan ,
as discussed via mail, please make the modification backward compatible, so that also files w/o deuteron graphs can still be used.

Cheers,
Andrea

**Comment by arossi81** [comment]
Hi @mbucklan,
thanks a lot! Can you just move the 
Bool_t isImproveDeuteron=kFALSE
argument of the AddTask in 4th place after the file names, so that who does not need deuteron will basically not even notice the modification (and no need to change the wagon settings in trains)?
Cheers,
Andrea

**Comment by mbucklan** [comment]
Hi @arossi81,
I have moved the argument to the 4th place in the AddTask.
Thanks,
Matt

**Comment by arossi81** [comment]
+1

**Pull request merged**
