### PR TITLE
Added FMD information for AOD analysis.

### PR DESCRIPTION
**Pull request by kreisl**
Added FMD information to reducedtree in case of AOD input.
The same FMD information as before is available in the reducedtrees for ESD input.

### CODE REVIEW

**Comment by zwound40** [comment]
+test

**Comment by dberzano** [comment]
Can this PR be either merged or closed?

**Comment by iarsene** [comment]
Hi, I will look at this in the next couple of hours and approve.
Cheers, Ionut

**Comment by iarsene** [comment]
+1

**Pull request merged**
