### PR TITLE
Adding histogram to get spherocity axis - D0 axis

### PR DESCRIPTION
**Pull request by mbjadhav**
Added 3D histogram to store the difference between spherocity axis and D meson axis.

### CODE REVIEW

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+1

**Comment by zconesa** [comment]
+test

**Comment by fprino** [comment]
Ciao,

I suggest to try to close this pull request and open another one with the correct files.

Cheers, Francesco

**Pull request closed without merging**
