### PR TITLE
Modifications to run with Mult FW on run2 PbPb data, different trigge…

### PR DESCRIPTION
**Pull request by dcaffarr**
…r selections

### CODE REVIEW

**Comment by rbertens** [comment]
+ test
ciao @dcaffarr , are the print statements that are left in the code (e.g.  Printf("quiiiiiiiiiiii"); ) intentional? 
thanks,
redmer

**Comment by rbertens** [comment]
+test
ciao @dcaffarr , are the print statements that are left in the code (e.g.  Printf("quiiiiiiiiiiii"); ) intentional? 
thanks,
redmer

**Comment by dcaffarr** [comment]
Of course not, it is a leftover from debugging... I have to correct this.

**Comment by rbertens** [comment]
ok, then i can wait with the '+1' until the PR is updated, unless it is urgent and you want it in as is. 
thanks,
redmer

**Comment by rbertens** [comment]
+1 Hi @dcaffarr what you did now is fine, the two pull requests gets 'merged' into one, that's now approved. thanks for the quick action

**Pull request merged**
