### PR TITLE
PWGGA/GammaConv: Adding more kinenmatic histograms for MC truth

### PR DESCRIPTION
**Pull request by mfasDa**
- Adding more kinematic histograms (pt, eta, phi) for the
  heavy meson and its decay products at various steps
  (all, in channel, reconstrutible, reconstructed)
- Fix indentation in various places
- Modernize: Use nullptr instead of NULL

### CODE REVIEW

**Comment by mfasDa** [comment]
Some histograms mainly needed for the D0: Look at the kinematics of the particle and the decay products but not only for reconstructed but also for all and reconstructible D0s.This is needed in order to check whether the decay products are in a kinematic range so that they can be reconstructed via the channel with Pi0 at all. Might also be helpful for the other heavy mesons.

**Comment by mfasDa** [comment]
Merge conflicts solved - review can start!

**Comment by mfasDa** [comment]
Hi @FriederikeBock , Hi @nschmidtALICE ,

I added the AOD MC case and resolved the merge conflicts. Can it be merged now?

Cheers

Markus

**Comment by nschmidtALICE** [comment]
+1

**Pull request merged**
