### PR TITLE
AliAnalysisTaskHFJetIPQA: apply cuts on jet properties via AliJetContainer

### PR DESCRIPTION
**Pull request by kagarner**
... instead of AliRDHFJetCuts

### CODE REVIEW

**Comment by mfasDa** [comment]
Please squash the commits and do a "git push -f" before merging the PR.

**Comment by kagarner** [comment]
Sorry for the inconvenience, is it okay like this?

**Comment by lcunquei** [comment]
+test

**Comment by lcunquei** [comment]
+1

**Pull request merged**
