### PR TITLE
Fill Et-M02 histo only for neutral clusters

### PR DESCRIPTION
**Pull request by ReneChristianSchach**

### CODE REVIEW

**Comment by e-masson** [comment]
+test

**Comment by e-masson** [comment]
Hi @ReneChristianSchach, there seems to be a problem in the tests, but I am not sure this is linked to your commit since this is not the first time I see this kind of error since yesterday...
Just to be sure, could you please double check your implementations?
Best,
Erwann

**Comment by ReneChristianSchach** [comment]
Hi @e-masson , I cannot access the error log so I have no idea what went wrong, but I have tested the changes locally before committing them and there were no problems. The changes are also rather small, I do not see how they could be problematic. 

Since all checks seem to be successful anyway, I think this error message can be ignored.
Best,
Rene

**Comment by e-masson** [comment]
Hi again @ReneChristianSchach, I think so. I cannot access the log either, but I think something is going wrong at an higher order (several mails were sent by people who had problems with AliRoot since yesterday).
Best,
Erwann

**Comment by ReneChristianSchach** [comment]
Hi again @e-masson , can you approve the merging anyway?

Best,
Rene

**Comment by e-masson** [comment]
Yes of course @ReneChristianSchach, sorry for missing!
Best,
Erwann

**Pull request merged**
