### PR TITLE
Uniform Binning for Asymmetric Charge and ptcut changed for QVector Calculation

### PR DESCRIPTION
**Pull request by prottayCMT**

### CODE REVIEW

**Comment by aohlson** [comment]
Hi @prottayCMT
Like I wrote on your previous pull request, in order for a new task to be compiled within AliPhysics, the task name also needs to be added to the files CMakeLists.txt and PWGflowTasksLinkDef.h. Could you update this pull request with the relevant lines added to those files as well? Then we can test it.
Thanks, and best wishes,
Alice

**Comment by prottayCMT** [comment]
Ok actually i am trying that only to add

**Comment by prottayCMT** [comment]
I have added my taskname to CMakeLists.txt and PWGflowTasksLinkDef.h. Can
you test it now or something else needs to be done?

With regards,
Prottay

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+1

**Pull request merged**
