### PR TITLE
Migrate TOF calibration AddTasks from AliRoot to AliPhysics

### PR DESCRIPTION
**Pull request by jezwilkinson**
Tasks AliTOFAnalysisTaskCalibTree & AliTOFAnalysisTaskCalibPass0 had been migrated to AliPhysics after AliRoot/AliPhysics split, but AddTask macros were orphaned in AliRoot (& not added to any CMakeLists, so inaccessible from LEGO train system). This patch migrates the missing macros to where they should be.

### CODE REVIEW

**Comment by preghenella** [comment]
+1

**Comment by preghenella** [comment]
+test

**Comment by chiarazampolli** [comment]
Hello,

What are these macros? Those for CPass are in:

$ALICE_PHYSICS/PWGPP/CalibMacros/CPass0
$ALICE_PHYSICS/PWGPP/CalibMacros/CPass1

Cheers,

Chiara

**Comment by jezwilkinson** [comment]
@chiarazampolli Ah. Sorry, my mistake then. Looks like those are indeed the same macros (give or take a couple of debug lines). Thought I'd searched through but must have missed this folder, not sure how that happened. I'll revert the pull request, apologies for the confusion.
In any case, those two macros seem to still exist in $ALICE_ROOT/TOF, which is what led to the confusion in the first place (as it looked like the tasks had moved but the macros not...).

**Comment by chiarazampolli** [comment]
Ciao Jeremy,
If they are the same macros, then we should remove them from TOF (not from PWGPP/CalibMacros, since we use them from there). Could you take care?

Chiara

**Comment by jezwilkinson** [comment]
Ciao Chiara,
The revert request (#997, https://github.com/alisw/AliPhysics/pull/997) should remove from the PWGPP/TOF folder and not touch the PWGPP/CalibMacros ones. Or do you mean to also remove from AliRoot?
--Jeremy

**Comment by chiarazampolli** [comment]
Ciao Jeremy,
Sorry for the late reply. I don't know if someone uses the macros from AliRoot, so I cannot really answer, but I would guess the macros are not needed in 2 places, so I would remove them from AliRoot.

Cheers,

Chiara

**Pull request merged**
