### PR TITLE
add studies of energy surrounding clusters

### PR DESCRIPTION
**Pull request by jdmulligan**
updates to my personal user task

### CODE REVIEW

**Comment by jdmulligan** [comment]
added several more commits, similar updates as above

**Comment by mfasDa** [comment]
+test

Hi @jdmulligan,

I have just a small comment: Please make all non-primitive reference-type function arguments which are not supposed to be changed by a function const. This applies to some occurrences of AliClusterContainer and AliEmcalJet.

Cheers

Markus

**Comment by jdmulligan** [comment]
Hi @mfasDa,

Commit added to clean this up.
Thanks for this suggestion, it is good that I start paying more attention to this :)

Cheers,
James

**Comment by mfasDa** [comment]
+test

Hi @jdmulligan ,

Thanks for cleaning! I am fine with the changes. In case there are no other comments by 2 pm Geneva time the PR will be merged.

Cheers

Markus

**Comment by mfasDa** [comment]
+1

**Pull request merged**
