### PR TITLE
add AliAnalysisTaskSEpPbCorrelationsMCYS.cxx

### PR DESCRIPTION
**Pull request by ysekiguc**

### CODE REVIEW

**Comment by ysekiguc** [comment]
Could you review?

**Comment by marslandALICE** [comment]
+test

**Comment by ysekiguc** [comment]
Could you test again?

**Comment by marslandALICE** [comment]
+test

**Comment by ysekiguc** [comment]
Hi,

I added my class, AliAnalysisTaskSEpPbCorrelationsMCYS, to PWGCFCorrelationsDPhiLinkDef.h and Cmakefile.tex.
But the compile error happened as 
Error: link requested for unknown class AliAnalysisTaskSEpPbCorrelationsMCYS /mnt/mesos/sandbox/sandbox/sw/SOURCES/AliPhysics/build_AliPhysics_release/0/PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h:77:

Something is missing to add my class to AliPhysics?
I very appreciate if you help.
Best Regards,
Yuko

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
Hi Yuko, 

The problem may be in the very first lines of AliAnalysisTaskSEpPbCorrelationsMCYS.h:
#ifndef ALIANALYSISTASKSEPPBCORRELATIONS
#define ALIANALYSISTASKSEPPBCORRELATIONS
and the corresponding #endif.  
Since this line is the same as in AliAnalysisTaskSEpPbCorrelationsYS.h, it may be preventing your class from being compiled.  

Furthermore, there are three small helper classes which are defined both in AliAnalysisTaskSEpPbCorrelationsMCYS.h and AliAnalysisTaskSEpPbCorrelationsYS.h: AliAssociatedTrackYS, AliMixTrackYS, and AliAssociatedVZEROYS.  It would be good to remove these double definitions.  

I hope this helps solve the problem!
Cheers, 
Alice

**Comment by aohlson** [comment]
+test

**Comment by aohlson** [comment]
+1

**Comment by ysekiguc** [comment]
Dear Alice and Mesut,

Thank you very much for your help.
I am sorry I missed many things......
I forgot to delete "endif" so I committed again.
Could you test again?

Best Regards,
Yuko

**Pull request merged**
