### PR TITLE
Updated mass histogram bining

### PR DESCRIPTION
**Pull request by SwatiSaha-1997**

### CODE REVIEW

**Comment by abilandz** [comment]
+1

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/5540/files should fix the issue. Unfortunately AliROOT will not work with any ROOT newer than v6.30.00.

**Comment by SwatiSaha-1997** [comment]
Dear @ktf , will I have to do anything in my code or it will me automatically merged? Please let me know.

**Comment by ktf** [comment]
+1

**Comment by abilandz** [comment]
+1

**Comment by abilandz** [comment]
+1

**Comment by abilandz** [comment]
+1

**Pull request merged**
