### PR TITLE
Fix auto_ptr deprecation errors in PWGCF

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
+test

#240 broke compilation on some machines because of the deprecated `auto_ptr` (also notifying @pbatzing). Can some expert check and merge if it works?

**Comment by pbatzing** [comment]
As I am the sole user and maintainer of libPWGCFThreePart at the moment, nobody except me will be able to confirm that this works and merge the code. At my end this fine and can be merged.

I am however puzzled that this issue first appears in #240 , as this particular lines of code have been present since I first introduced the class in AliRoot.

**Comment by rbertens** [comment]
Hi Paul, 
Since you're the only user I've approved the commit - otherwise it's stuck forever.

**Comment by dberzano** [comment]
Hi @rbertens, you need to comment on the PR, not on the commit :-)

**Comment by dberzano** [comment]
Hi @pbatzing, in #240 you turn all warnings into errors in the `CMakeLists.txt`, see [here](https://github.com/alisw/AliPhysics/pull/240/files#diff-69500f5234320e6f5ea8c74ade0d8309). This is good (very good actually), but had the side effect that the compiler on my machine (GCC v5.4.0) as _more_ warnings than the production one used for tests (GCC v4.9.3). One of these additional warnings (turned into errors) was the deprecation of `auto_ptr`.

**Comment by rbertens** [comment]
+1

**Comment by pbatzing** [comment]
Hi @dberzano I see. Then at least it should not happen more in the future. I think also I will update my local compiler, so that I catch such warnings (errors) on my end. Thanks for the fix.

**Comment by dberzano** [comment]
No worries, it's not your fault at all!

**Pull request merged**
