### PR TITLE
PWG/EMCAL and OADB/EMCAL: custom bad channel map feature added to EMCtender

### PR DESCRIPTION
**Pull request by nschmidtALICE**
With this small addition, it is now possible to load a custom bad channel map for testing purposes. The previous feature to set a different path for all calibrations remains unchanged with this update.

### CODE REVIEW

**Comment by jdmulligan** [comment]
HI Nicolas,

The EMCal Tender is no longer maintained and has been superceded by the EMCal Correction Task (http://alidoc.cern.ch/AliPhysics/master/_r_e_a_d_m_eemc_corrections.html). Is there a particular reason you need/want to commit this to the Tender? Otherwise I would suggest to add it to the new correction framework instead. Namely, the function you modify is located at AliEmcalCorrectionComponent::InitBadChannels(). I am happy to help with the implementation (or do it myself).

Cheers,
James

**Comment by loizides** [comment]
I'd like to keep the tender in sync with changes... so lets go ahead.

**Comment by nschmidtALICE** [comment]
Hello James,

we have not yet made the switch to the Correction Task in our group as all functionalities are still available with the "old tender". As this small change does not affect anyone and only provides a small improvement to the tender, it would be great if it could be added.

Cheers,
Nicolas

**Comment by gconesab** [comment]
I would still suggest to move to the new framework, in this way we will never abandon the tender.

**Comment by loizides** [comment]
I do not see what is wrong with the tender...
it has been proven stabel for many many years, and there is a large group of people using it, and that does not need all the xtra features of corr framework

**Comment by gconesab** [comment]
Hi Constantin, I will not maintain N frameworks. You can approve the request if you think it is the way to go.

**Comment by mfasDa** [comment]
@nschmidtALICE , @loizides 

First of all I agree with Raymond and Gustavo that it is a bad idea to keep and old and unmaintained framework alive. There is no coordinated effort put into this, so whoever is using it is on their own. In addition there were extensive test done by Raymond and James showing the correction task output is the same as for the tender.

Second, could you please elaborate a bit why this bypass is needed? Having bypasses can become dangerous, in particular if they are misused (i.e. copying one macro from another).

Cheers

Markus

**Comment by loizides** [comment]
The corr framework is much more than the tender... plus we can not afford now to change a functional system that is used by ~5 people out of which we have obtained 3 recent papers and 2 to come just because we do not want to add one easy change to the tender
I will approve the change

**Comment by loizides** [comment]
+1

**Comment by loizides** [comment]
Ok so it needs someone to approve with rights in all directories, gustavo can you please do it, in the end this stops nico from testing the maps he is creating!

**Comment by gconesab** [comment]
As a matter of principle, I do not want to approve it but I will. Future use and developments of this task will have to be be discussed again within the emcal community.

**Comment by gconesab** [comment]
+1

**Comment by raymondEhlers** [comment]
From our perspective, this principle is problematic for a few reasons:

- When the Corrections Framework was deployed, it was agreed in the EMCal group that it would be the maintained framework, and we would cease to maintain the tender.
- No one has been maintaining the tender for the last year, and there have been recently found bugs from the old corrections that are fixed in the Correction Framework and may not be fixed in the tender.
- As noted by Markus, we put in a significant amount of work to validate the Correction Framework against the tender, and we know they agree. We also made those tools available, so others can use them to validate their own analyses.
   - If the tender and Correction Framework diverge now, then we don't benefit from shared code, and we're more susceptible to bugs and non-uniformity across the EMCal.
- By default, the Correction Framework does as little or as much as you want it to. If you only want the aspects that correspond to the tender, no problem - just enable those components and you can ignore everything else.

Raymond + James

**Pull request merged**
