### PR TITLE
PWGGA/GammaConv  Updated CutString

### PR DESCRIPTION
**Pull request by AMechler**
Changed CutString for DCal analysis to new DCal eta range setting

### CODE REVIEW

**Comment by nschmidtALICE** [comment]
+1

**Comment by nschmidtALICE** [comment]
+1

**Comment by nschmidtALICE** [comment]
+test

**Comment by nschmidtALICE** [comment]
@dberzano : Somehow aliBuild fails here for apparently no reason. Could you please check that? Thanks in advance!

**Comment by AMechler** [comment]
we assume the error occurs because of additional commits after the +1

**Comment by dberzano** [comment]
As answered privately, sometimes errors occur because of infrastructure problems, but they will eventually clear auto automatically. The error has nothing to do with additional commits, which are supported and treated correctly by the infrastructure.

**Pull request closed without merging**
