### PR TITLE
add fmd analysis

### PR DESCRIPTION
**Pull request by ysekiguc**

### CODE REVIEW

**Comment by aohlson** [comment]
+1

**Comment by ysekiguc** [comment]
Hi,

The error occurs due to  AliAODForwardMult.h as following.
Some library should be added in Makefile?

Best Regards,
Yuko

[ 28%] Building CXX object PWGCF/Correlations/DPhi/CMakeFiles/PWGCFCorrelationsDPhi-object.dir/AliAnalysisTaskSEpPbCorrelationsYS.cxx.o
/mnt/mesos/sandbox/sandbox/sw/SOURCES/AliPhysics/0/0/PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsYS.cxx:62:31: fatal error: AliAODForwardMult.h: No such file or directory
 #include "AliAODForwardMult.h"
                               ^
compilation terminated.
make[2]: *** [PWGCF/Correlations/DPhi/CMakeFiles/PWGCFCorrelationsDPhi-object.dir/AliAnalysisTaskSEpPbCorrelationsYS.cxx.o] Error 1

**Comment by aohlson** [comment]
Hi @ysekiguc , 
Yes, you should add the directory 
${AliPhysics_SOURCE_DIR}/PWGLF/FORWARD/analysis2
to the include directories in CMakeLists.txt.  
In general, we try to avoid compiling outside libraries in PWGCF (i.e. from PWGLF), but since it's necessary then you can add it.  
Cheers, 
Alice

**Comment by aohlson** [comment]
+1

**Pull request merged**
