### PR TITLE
Adding AliAnalysisTaskPbPbTree_MCut.cxx to CMakeLists.txt & PWGDQdimu…

### PR DESCRIPTION
**Pull request by lucamicheletti93**
Adding AliAnalysisTaskPbPbTree_MCut.cxx to CMakeLists.txt & PWGDQdimonsLinkDef.h

### CODE REVIEW

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+1

**Comment by miweberSMI** [comment]
+1

**Comment by lucamicheletti93** [comment]
Dear experts,
I'm having some issues in the commit of my analysis task. Apparently the issue is related to AliMultSelection.h, as reported in the log file in attachment. I have checked in other similar tasks and it seems to me that I'm including the class properly, but maybe I'm missing something
[fullLog.txt](https://github.com/alisw/AliPhysics/files/5659096/fullLog.txt)

Luca

**Comment by miweberSMI** [comment]
+1

**Pull request merged**
