### PR TITLE
PWGGA/GammaConv: Added QA before meson selection.

### PR DESCRIPTION
**Pull request by hjbossi**
-In addition fixed negation for meson is selected.

### CODE REVIEW

**Comment by dmuhlhei** [comment]
Could you please help me: I don't understand the changes in the BGHandler. Where is "GetNBackgroundEventsInBuffer" defined, for example?

**Comment by hjbossi** [comment]
Hi Daniel,

I believe this is a result of conflicts with different versions of the code
that Markus and I worked on separately. We will prepare another commit
today with the changes.

Thank you for asking! I appreciate the help!

Hannah

**Comment by mfasDa** [comment]
Hi @dmuhlhei,

The new function is intended to return the number of background events for a given bin in (z, multiplicity) currently stored in the buffer (not the maximum number of events / buffer size!). I don't see such a function implemented up to now.

We access this information via the function size of std::vector, which returns the number of events currently stored in the vector.

It would be helpful to have such a member function available, i.e. in a loop over background events one wants to loop only over the events which are actually stored in the buffer, not the maximum possible amount.

Best Regards

Markus

**Comment by dmuhlhei** [comment]
thanks a lot :)

What is the purpose of 'AliGammaConversionMotherBGVector1'? The typedef is added, but I do not see where it is used.

**Comment by mfasDa** [comment]
ah, this is a leftover remanent which was there just for illustration. Thanks for spotting it! While it does not harm it certainly should not end up in the repo. @hjbossi could you please remove the typedef and add a new patch for this?

**Comment by hjbossi** [comment]
This change should be fixed now!

**Comment by dmuhlhei** [comment]
thx! +1

**Comment by dmuhlhei** [comment]
+1

**Pull request merged**
