### PR TITLE
ITS+TPC+TRD reconstruction performance characterization

### PR DESCRIPTION
**Pull request by miranov25**
New variable extInnerParamV added to the filtered ESD trees.

### CODE REVIEW

**Comment by miranov25** [comment]
+1

**Comment by miranov25** [comment]
+1 
Looks again wrong permissions

**Comment by dberzano** [comment]
@miranov25 it looks your CERN account is not mapped to your GitHub account though. I could not find your user mapping in the configuration. Btw once again, it is worthless to type `+1` if you are not mentioned: the system will ignore your comment! Could you please follow [the tutorial](alisw.github.io/git-tutorial) and map your CERN account with your GitHub one? It's the first thing explained there.

**Comment by dberzano** [comment]
Anyway @miranov25 have you read the [pull request guidelines](http://alisw.github.io/git-advanced/#how-to-write-a-pull-request)? Your two commit messages are badly styled. Please:

* Keep the first line < 50 characters, and have it concise
* Explain more extensively what you do in the _next_ lines

Do not try to fit everything in the first line please. It would be good if you refactored your commit messages before the approval.

**Comment by miranov25** [comment]
Hallo Dario.

Concerning privileges, I followed the tutorial. Maybe not enough carefull.
 
* Whomai
* https://alisw.cern.ch/alice-github/whoami
*Hello Marian Ivanov.
You are mivanov at CERN and miranov25 on GitHub.*

* Checking again permission on the gihub 
https://github.com/settings/connections/applications/02fe9974bc04e2089b08
* Access public information (read-only)

Maybe problem is connected to the fact I have user names mivanov and miranov ?

Until we will solve the proeblem, can somebody approve my push request?

Marian.

**Comment by dberzano** [comment]
Hi Marian, can you please address the commit messages issue? If you reformat them according to the guideline I'll approve your PR.

**Comment by dberzano** [comment]
...and your username is now mapped, there was an internal issue that prevented this from happening, sorry about that.

**Comment by miranov25** [comment]
If I understand correclty you suggest to change the commit message.
I did not find easy way to do it. 
What is proposed by gihub:
*https://help.github.com/articles/changing-a-commit-message/
git commit --amend*    is not simple and I have another problem why I can not do it

**Comment by dberzano** [comment]
You have two commits. Therefore,

```
git rebase -i HEAD^2
```

You will see something like (most recent commit at the bottom):

```
pick e8551bb PWGPP-272 - Combined tracking benchmark. Adding TPC+TRD track pr...
pick 95ddc10 PWGPP-272 - adding residual histograms for deltaPX, deltaPXconst...
```

Change the `pick` into `reword`, save the file and exit the editor.

You will be prompted to re-enter the commit messages in order, first for the oldest commit then for the newest.

Let us know if it works 👍

**Comment by miranov25** [comment]
I did not write a reason why I did not want to do further modification.
My software is on lustre. Last 2 days lustre is very unstable. I was lucky to push the commit today in the morning. 
```
git rebase -i HEAD~2
```
After modifying commit message lustre is stuck .... git not responding
Not sure when will it be back ...

**Comment by dberzano** [comment]
No rush. Besides, you can clone (just clone; not build) the repo on your laptop an fix the commit messages from there.

**Comment by miranov25** [comment]
Hallo

I modified history according comments and I pushed them to my AliPhysics.
We can cancel this request and I will make new pull request.

Not sure how to cancel old one.

Marian

**Pull request closed without merging**
