### PR TITLE
Change the structure of the output files and their size

### PR DESCRIPTION
**Pull request by gskorodu**
- The information about the prompt V0 is not included in the output file anymore.
- Tighter topological cuts are used for the analysed tracks, thus making the output lighter.
- The structure of the output file (TTree) is changed (nested now).
- As a result the output file is of order 200(!) lighter than in the previous version.

### CODE REVIEW

**Comment by mkruegerGitHub** [comment]
+1

**Comment by mkruegerGitHub** [comment]
+test

**Comment by mkruegerGitHub** [comment]
+test

**Comment by gskorodu** [comment]
Hi @mkruegerGitHub 

could you, please, check my updated task? I changed the code a bit and it runs locally both with root5 and root6 now.

Best regards, 
Georgijs

**Comment by mkruegerGitHub** [comment]
+test

**Comment by mkruegerGitHub** [comment]
+test

**Comment by gskorodu** [comment]
Hi @mkruegerGitHub

could you, please, check my updated task? I left only one ClassDef title per header and it seems to work now: load_library_PWGLFQATasks and load_library_PWGLFSTRANGENESS are indeed loaded (locally) and there is apparently no conflict anymore.

Best regards,
Georgijs

**Comment by mkruegerGitHub** [comment]
+1

**Pull request merged**
