### PR TITLE
T0: Add 0TVX efficiency histogram to QA

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
We add 0TVX efficincy histogram to QA

**Comment by fprino** [comment]
Hi Alla,

it seems to me that:
- you forgot to increment the class revision number of AliT0AnalysisTaskQA.h
- something went wrong in the modification of PWGPP/CalibMacros/CPass1/AddTaskT0Calib.C (please have a look at the diff attached to this ticket).

Can you please check and fix?

Cheers, Francesco

**Comment by fprino** [comment]
HI Alla,

thanks for incrementing the class revision.
Is it OK that there are essentially no changes in PWGPP/CalibMacros/CPass1/AddTaskT0Calib.C?
From the diff the only changes are related to white spaces.

Cheers, Francesco

**Comment by AllaMaevskaya** [comment]
Hello

no difference in CalibMacros needed,  only white space. My goal is to add 0TVX efficiency histogram to QA task.

Best regards
Alla

**Comment by fprino** [comment]
Hi Alla,
 but for the CPass0 macro something was changed:
+  UInt_t timeStart = grpData->GetTimeStart();
+  UInt_t timeEnd = grpData->GetTimeEnd();
+  mytask->SetStartEndTime(timeStart,timeEnd);
+  cout<<"T0 start time  "<<timeStart<<" end time "<<timeEnd<<endl;

Is this OK?

Cheers, Francesco

**Comment by AllaMaevskaya** [comment]
Sorry , I don't see difference with 
https://github.com/alisw/AliPhysics/blob/master/PWGPP/CalibMacros/CPass0/AddTaskT0Calib.C
lines 85-88

Best regards
Alla

**Comment by AllaMaevskaya** [comment]
I think it was empty line removed

**Comment by fprino** [comment]
Hi Alla,
you can see the difference here:
https://github.com/alisw/AliPhysics/pull/3287/files
It seems there are 4 lines that were added:
```
+  UInt_t timeStart = grpData->GetTimeStart();
+  UInt_t timeEnd = grpData->GetTimeEnd();
+  mytask->SetStartEndTime(timeStart,timeEnd);
+  cout<<"T0 start time  "<<timeStart<<" end time "<<timeEnd<<endl;

```

**Comment by AllaMaevskaya** [comment]
Yes, but look here 
https://github.com/alisw/AliPhysics/blob/master/PWGPP/CalibMacros/CPass0/AddTaskT0Calib.C
The only difference is empty line

**Comment by raymondEhlers** [comment]
Hi @AllaMaevskaya ,

I just noticed your PR and that it is related to `AliT0AnalysisTaskQA`, so I wanted to make a brief general comment (it's not related to the changes you introduce here). This class causes a warning on startup for anyone using ROOT 6. The warning is:
```
Warning in <TInterpreter::ReadRootmapFile>: class  AliT0AnalysisTaskQA found in libT0calib  is already in libPWGPP
```
It is caused by having two class both named `AliT0AnalysisTaskQA`. One is in `$ALICE_ROOT/T0/T0calib` and the other is in `$ALICE_PHYSICS/PWGPP/T0`. Would it be possible for one of these to be renamed to remove the warning when loading the rootmaps?

Thanks!

**Comment by fprino** [comment]
Hi Alla,

I checked the file in your link and also on my local version of the master and indeed the lines are there.
I am however confused by the diff that we see in this pull request, which shows 4 lines added.
@dberzano can you please have a look? Might it be that something went wrong in creating the diff?


I am sorry to bother, but this is a macro used in the CPass'es so we should make sure that we do not screw it up.
On this respect: @AllaMaevskaya: wouldn't it be safer to commit only the QA task, that you changed and not the AddTask macro in which you just modified (according to what you write ) whaite spaces?

Cheers, Francesco

**Comment by dberzano** [comment]
@AllaMaevskaya please look more closely, GitHub is not wrong: you did modify your task, it's not only empty lines. Be aware that you have actually re-added some lines:

```diff
+  UInt_t timeStart = grpData->GetTimeStart();
+  UInt_t timeEnd = grpData->GetTimeEnd();
+  mytask->SetStartEndTime(timeStart,timeEnd);
+  cout<<"T0 start time  "<<timeStart<<" end time "<<timeEnd<<endl;
```

that were already present some lines after, see the full context here:

```diff
+  
+  //  AliCDBEntry* entryGRP = AliCDBManager::Instance()->Get("GRP/GRP/Data");
+  // AliGRPObject* grpData = dynamic_cast<AliGRPObject*>(entryGRP->GetObject());
+  UInt_t timeStart = grpData->GetTimeStart();
+  UInt_t timeEnd = grpData->GetTimeEnd();
+  mytask->SetStartEndTime(timeStart,timeEnd);
+  cout<<"T0 start time  "<<timeStart<<" end time "<<timeEnd<<endl;
 
   //  AliCDBEntry* entryGRP = AliCDBManager::Instance()->Get("GRP/GRP/Data");
   // AliGRPObject* grpData = dynamic_cast<AliGRPObject*>(entryGRP->GetObject());
  UInt_t timeStart = grpData->GetTimeStart();
  UInt_t timeEnd = grpData->GetTimeEnd();
  mytask->SetStartEndTime(timeStart,timeEnd);
  cout<<"T0 start time  "<<timeStart<<" end time "<<timeEnd<<endl;
```

This is quite clearly a mistake...

**Comment by dberzano** [comment]
@AllaMaevskaya @fprino note that I have fixed the problem myself, see my only commit in this PR, e4f545e5e254f7dbf4bb5b5122e42b82629c0817.

**Comment by dberzano** [comment]
Last but not least: @AllaMaevskaya please give meaningful names to your pull requests. "T0 dev" is quite generic. I have renamed it as you can see.

**Comment by dberzano** [comment]
+test

**Comment by fprino** [comment]
Hi Dario,

thanks for the fix!
We still have pending the comment from @raymondEhlers.
Maybe this can be treated in a next pull request, upon clarification by Alla.
In the meanwhile I launch the comilation test.

Cheers, Francesco

**Comment by fprino** [comment]
+test

**Comment by raymondEhlers** [comment]
Hi @fprino ,

An additional pull request to resolve my comment would be good with me. I didn't intend to hold up this PR with my comment - I just wanted to bring it up so that it can be addressed eventually :-)

Best,
Raymond

**Comment by fprino** [comment]
+1
@AllaMaevskaya , please implement at your earliest convenience the suggestion of @raymondEhlers .
Cheers, Francesco

**Pull request merged**
