### PR TITLE
chore(PWGCF): code clean-up in AliAnalysisTaskPhiCorrelations class

### PR DESCRIPTION
**Pull request by pkarczma**
Clean-up of .h & .cxx files for AliAnalysisTaskPhiCorrelations class:
- Fix indentation issues
- Convert all tab characters to spaces
- Remove unnecessary whitespaces
- Keep curly brackets consistent across the files
- Adjust spaces to improve readability

### CODE REVIEW

**Comment by ktf** [comment]
Please do not use draft for PRs to be approved immediately. Closing.

**Comment by pkarczma** [comment]
Hi @ktf I still wanted to work on this PR, but from what I know adding 'WIP' in the PR title is deprecated and should no longer be used. What method should I use then when I want to open a pull request but I do not want to merge it immediately? Should I avoid making such PR and wait until everything is ready?

**Comment by ktf** [comment]
The problem is that you are have "immediate approval" rights and that conflicts with the "draft" status. While this is effectively an issue to be solved on the CI side, since it blocks the daily builds from starting I am kindly asking you not to open  a PR which triggers such a race condition.

**Comment by pkarczma** [comment]
@ktf Thanks for your explanation, I will avoid using 'draft' PR in the future then.

**Pull request closed without merging**
