### PR TITLE
All track types status getters/setters use ULong64_t

### PR DESCRIPTION
**Pull request by shahor02**
Since the bit mask of AliESDtrack needs to use >32 bits, all getters and setters of Alice track type
(starting from AliVParticle) status (GetStatus, SetStatus) are returning/acceptring ULong64_t instead
of ULong_t

### CODE REVIEW

**Comment by shahor02** [comment]
+test

**Comment by akubera** [comment]
+test

**Comment by bdoenigu** [comment]
+1

**Comment by mfasDa** [comment]
+test

**Comment by shahor02** [comment]
Hi,
Please don't merge this PR since it depends on the another PR in the aliroot master. This will be done by @dberzano during new tag creation.

Cheers,
   Ruben

**Comment by dberzano** [comment]
This PR has been tested separately in [ALIROOT-7894](https://alice.its.cern.ch/jira/browse/ALIROOT-7894) and we are merging it manually.

**Pull request merged**
