### PR TITLE
Update code

### PR DESCRIPTION
**Pull request by sumitsaha92**

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+test

**Comment by mfasDa** [comment]
2 more requests:
- Please squash the commits into 1 when done!
- Please use a more meaningful commit message!

**Comment by sumitsaha92** [comment]
modify the code from previous error message and add background subtraction part.

**Comment by raymondEhlers** [comment]
+test I'd be good if you could address Markus' comments. Note that the comments that you make on the PR here don't affect the actual commit messages

**Comment by pzhristov** [comment]
Is this pull request still needed?

**Comment by sumitsaha92** [comment]
Dear Peter,

Sorry for late reply. At the moment pull request not needed.

________________________________

**Pull request closed without merging**
