### PR TITLE
Adding different SPD selections

### PR DESCRIPTION
**Pull request by afestant**
Adding the possibility to select tracks with 5 ITS points checking the hit on SPD layers. Adding kOnlyFirst and kOnlySecond cases to ESDtrackcuts definition.

### CODE REVIEW

**Comment by fprino** [comment]
Hi Andrea,
you probably changed some indentations because the diff in github shows all the lines as changed.
Can you please check?
Cheers, Fancesco

**Comment by afestant** [comment]
Hi Francesco,
yes, I did change the indentation, sorry! The updated task compiles locally on my computer and I checked in the diff the lines that have actually changed and they should be correct, if you look at the new file in the diff, the lines changed are:
.cxx
l577, l588
l782-792

AddTask
l1, l40
l52-69
Cheers, Andrea

**Comment by mpuccio** [comment]
Hi, it is possible to check the diff on github without the whitespace changes, you just need to append [?w=1](https://github.com/alisw/AliPhysics/pull/3598/files?w=1) to the diff url (it does the same of `git diff -w`).

Cheers!
Max

**Comment by fprino** [comment]
+1 (thanks Max for the hint)

**Pull request merged**
