### PR TITLE
Code aesthetics

### PR DESCRIPTION
**Pull request by e-masson**
Comments and general indentation.

### CODE REVIEW

**Comment by dlodato** [comment]
+1

**Comment by e-masson** [comment]
Hi Davide, thanks! I am using macOS as main interface but my AliPhysics installation is on the same SL server at Subatech. Anyway I did not modify anything concerning md5, do you think that the code cleaning I made could cause an issue?

**Comment by dlodato** [comment]
@e-masson I remember there have been some problems of this sort, but not specifically which.
It could also have been due to something completely unrelated.
Maybe (hopefully) a bit of rumour for nothing, but I thought it was worth mentioning the possibility for this to happen..

**Comment by e-masson** [comment]
Of course, you did well!

**Pull request merged**
