### PR TITLE
swtich to nanoAOD

### PR DESCRIPTION
**Pull request by magicep0t**

### CODE REVIEW

**Comment by bhohlweger** [comment]
+1

**Comment by bhohlweger** [comment]
+test

**Comment by bhohlweger** [comment]
+1

**Comment by ktf** [comment]
@ihrivnac was vmc retagged?

**Comment by ihrivnac** [comment]
@ktf, do you mean geant4_vmc? If so, the latest tags are proposed in this PR https://github.com/alisw/alidist/pull/2114

**Comment by ktf** [comment]
nevermind the issue was something else.

**Pull request merged**
