### PR TITLE
Clear background vector

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by mpuccio** [comment]
Hi @ktf, it looks like there is another Friday issue on the builders. Many PRs are affected, could you please have a look?

**Comment by ktf** [comment]
Could you try force pushing some change to this PR? we lost a big machine (plus other issues this morning).

**Comment by mpuccio** [comment]
Fingers crossed

**Comment by mpuccio** [comment]
@ktf still the same...

**Comment by ktf** [comment]
I saw... :-/ Investigating...

**Pull request merged**
