### PR TITLE
PWGGA/GammaConv: Omit deletion of the fListHistos in AliCaloTrackMatc…

### PR DESCRIPTION
**Pull request by pgonzale83**
…her as the analysis fails in the GSI train if list is stored in the global output

### CODE REVIEW

**Comment by FriederikeBock** [comment]
Hi Pedro,

thinking about it a little I am wondering whether we don't wanna introduce a flag for GSI running, because its so specific to GSI and in general we should free this memory again. 
Wouldn't this make more sense and then implement it as well for all the other classes, where we removedn the deletion to not make it crash at GSI?

Regards,
Friederike

**Comment by pgonzale83** [comment]
Hi Friederike,
I agree with you, it can be dangerous if we don't free the memory in the Grid.
I am going to implement a flag to check if we are running on the grid or  on the GSI.
Best regards,
Pedro G.

**Comment by FriederikeBock** [comment]
Hi Pedro,
very good, thanks so much!
Regards,
Friederike

**Comment by FriederikeBock** [comment]
Hi Pedro,

could you increase the ClassDef please.

Regards,
Friederike

**Comment by FriederikeBock** [comment]
+1
Thanks!

**Comment by pgonzale83** [comment]
Hi Friederike, 
I have increased the classDef from 2 to 3.
Another thing, I wanted to implement something similar in the classes: AliConversionMesonCuts and AliConversionPhotonCuts but I was not sure if the deletion of fHistograms were commented in those classes because they crashed at the GSI or they were commented because they also crashed in the Grid.  do you know the reason?

Best regards,

Pedro G.

**Pull request merged**
