### PR TITLE
Fix include paths for JETHF

### PR DESCRIPTION
**Pull request by dstocco**
See https://alice.its.cern.ch/jira/browse/ALPHY-89

### CODE REVIEW

**Comment by arossi81** [comment]
+1

**Comment by arossi81** [comment]
Hi @dstocco,
I think it was my fault, since I first approved Auro's commit, thinking that it was included also another dependence (about the rho task) and I thought yours was fixing what discussed in the JIRA ticket. Anyhow, right now I think we can keep Auro's commit and neglect yours, since they are identical. Right?
Cheers,
Andrea

**Comment by MycrofD** [comment]
Hi @arossi81 , @dstocco ,
I found out about Diego's PR after having created one on my own. We kind of did both the PR's around the same time. Anyway, they are identical and only one was required.
Best, 
Auro

**Comment by dstocco** [comment]
Sorry, we made the PR almost at the same time.
Since Auro's fix is committed, I can close this one.
Thanks!
Cheers,
Diego

**Pull request closed without merging**
