### PR TITLE
This is for debugging and might not conform to best c++ standards

### PR DESCRIPTION
**Pull request by fibnumb**
This is for debugging and might not conform to best c++ standards, my code is crashing on the lego train yet runs fine locally with Root5 and Root6.  The changes made in this PR will only be temporary

### CODE REVIEW

**Comment by raymondEhlers** [comment]
It also works fine on a local test train?

**Comment by fibnumb** [comment]
Yes. I think it is some kind of memory leak that I’m not hitting by using a local machine.

**Comment by raymondEhlers** [comment]
+test

**Comment by raymondEhlers** [comment]
Humm, I suspect that should be quite rare, but it's your task, so this commit is fine by me

**Comment by raymondEhlers** [comment]
+1

**Pull request merged**
