### PR TITLE
Small modification to hybrid tracks

### PR DESCRIPTION
**Pull request by smaff92**
Just added manual TPC selection

### CODE REVIEW

**Comment by mkruegerGitHub** [comment]
+1

**Comment by smaff92** [comment]
Hi Mario,

Thanks for approving my merge request.
It seems that the build failed, but I do not quite understand why? 
It built on my local environment, and there's not a build log produced in either root6/release branch.
Am I doing something wrong on my end, or are the checks not working properly?

Best Regards
Adrian.N

**Comment by mkruegerGitHub** [comment]
Hi Adrian,
this is not related to your code, there seems to be a central problem with the building.
Cheers,
  Mario

**Comment by smaff92** [comment]
Hi Mario,

Thank you for the clarification!

Best Regards
Adrian.N

**Pull request merged**
