### PR TITLE
Reorder names of input variables

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Pinging @andreaalici for information.

**Comment by jezwilkinson** [comment]
+1

**Comment by chiarazampolli** [comment]
Hello @dberzano , @ktf ,

I think this is the same issue as a few days ago... Last time it took quite some hours to "self-fix", could you please check, so that we don't miss tomorrow tag?

Thanks!

Chiara

**Comment by ktf** [comment]
I moved the worker to a different machine. Let me know if it does not turn green in a few hours.

**Comment by chiarazampolli** [comment]
Still not merged... should we retrigger the tests?

**Comment by ktf** [comment]
Yes, please.

**Comment by chiarazampolli** [comment]
I cannot do it... @jezwilkinson , @afestant , @cterrevo , could you please re-approve?

Thanks!

**Comment by afestant** [comment]
+1

**Comment by ktf** [comment]
(for the record, it's actually already rebuilding).

**Comment by chiarazampolli** [comment]
Hello @ktf , 

Again issues with ROOT6... 

Cheers,

Chiara

**Comment by ktf** [comment]
I am checking...

**Comment by ktf** [comment]
I think I understand the problem. The ROOT build is actually on the threshold of our build timeout since we moved to v6-16-00 and on slower machines that triggers a kill. I will try to trigger the caching of the externals...

**Comment by ktf** [comment]
No, never mind, it is an "out of memory" error while compiling...

**Comment by ktf** [comment]
+test

**Pull request merged**
