### PR TITLE
PWG/EMCal: Modified additional cell scale (now SM dependent)

### PR DESCRIPTION
**Pull request by jokonig**
- Now the cell scale it can have different values depending on the SM type (full, 2/3 and 1/3)

### CODE REVIEW

**Comment by gconesab** [comment]
+test

**Comment by raymondEhlers** [comment]
For what it's worth, it looks good to me

**Comment by gconesab** [comment]
+test

**Comment by gconesab** [comment]
+test

**Comment by gconesab** [comment]
+1

**Pull request merged**
