### PR TITLE
Fixed building AliPhysics without Fastjet

### PR DESCRIPTION
**Pull request by osaarima**

### CODE REVIEW

**Comment by raymondEhlers** [comment]
+1

**Comment by dongjokim** [comment]
+1

**Comment by osaarima** [comment]
Dear reviewers. Can this be checked so it could be merged?

**Comment by rihanphys** [comment]
+test--
       With regards,

Md Rihan Haque,
Research Assistant Professor,
Department of Physics, Warsaw University of Technology,
Koszykowa 75, 00-662 Warszawa, Poland

**Comment by jgrosseo** [comment]
Not sure why it does not accept your verdict

**Comment by jgrosseo** [comment]
+1

**Pull request merged**
