### PR TITLE
Improvements to YAML config class

### PR DESCRIPTION
**Pull request by raymondEhlers**
Includes an improved interface and refactoring additional utility functions from the EMCal Correction Framework to the YAML configuration class

### CODE REVIEW

**Comment by aiola** [comment]
+test, it looks fine to me, maybe @mfasDa wants to take a look as well

**Comment by raymondEhlers** [comment]
That error is rather difficult to interpret, but I think I just fixed it with my latest commit (of course, it doesn't show up on clang, so it's a bit difficult to debug)

**Comment by mfasDa** [comment]
+test

If the error is fixed I would think it should be approved.

**Comment by aiola** [comment]
+1

**Comment by raymondEhlers** [comment]
Thanks @aiola and @mfasDa !

**Pull request merged**
