### PR TITLE
Add addtask and config macro for pp phimeson polarisation analysis, and minor modification to Pb-Pb task

### PR DESCRIPTION
**Pull request by arvindkhuntia**
Please approve  to commit in master branch

### CODE REVIEW

**Comment by bdoenigu** [comment]
+1

**Comment by arvindkhuntia** [comment]
Please approve for the checks

**Comment by bdoenigu** [comment]
+1

**Comment by arvindkhuntia** [comment]
(1) Removed the addtask and config macro for pp analysis [phi-resonance]

Please approve  the minor modification to the Pb-Pb analysis macro

**Comment by BongHwi** [comment]
+1

**Comment by arvindkhuntia** [comment]
Please approve for the checks

**Comment by bdoenigu** [comment]
+1

**Pull request merged**
