### PR TITLE
Fix for ROOT6

### PR DESCRIPTION
**Pull request by davidrohr**
cannot include macro with $ALICE_PHYSICS in #include directory, and le is not in $ROOT_INCLUDE_PATH.

As discussed with @dberzano , this is a better fix as compared to alisw/alidist#1246, as it does not pollute the global include space.

### CODE REVIEW

**Comment by davidrohr** [comment]
+test

**Comment by dmuhlhei** [comment]
Hi, may I ask why there is a change from AliInfo() to Info() for the AddTask_ConversionAODProduction.C?

**Comment by davidrohr** [comment]
AliInfo needs ClassName(), which is not available in the macro

**Comment by dmuhlhei** [comment]
So this is only an issue for a macro? Since we use AliInfo in various places

**Comment by davidrohr** [comment]
Yes, in any class that inherits from TObject it is OK. But the macro is a plain C function, so ClassName is not defined. Since the macro was never compiled, and apparently that error message was never triggered, we didn't see the problem with ROOT5.

**Comment by dmuhlhei** [comment]
+1

**Comment by fprino** [comment]
+1

**Pull request merged**
