### PR TITLE
Update TOF pid params for PbPb 2018 (pass2)

### PR DESCRIPTION
**Pull request by njacazio**
Updated TOF resolution in OADB after recalibration for pass2

### CODE REVIEW

**Comment by njacazio** [comment]
PR for OADB is now open @noferini @pantonioli @preghenella

**Comment by chiarazampolli** [comment]
+1

**Comment by chiarazampolli** [comment]
Ciao @njacazio , 

To be sure, this change is in the OADB ONLY for pass2, right? The entry was updated only for the new reconstruction.

Chiara

**Comment by njacazio** [comment]
Ciao @chiarazampolli, indeed this change is for pass2 only.
Cheers,
Nicolo'

**Pull request merged**
