### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by xinyepeng**

### CODE REVIEW

**Comment by jezwilkinson** [comment]
+1

**Comment by jezwilkinson** [comment]
Hello @xinyepeng,
it looks like there were some lingering instances of fD0PtCut elsewhere in the task when you removed the variable from the header...
As a general rule, please try compiling the task locally against the master before making the pull request, this would have been caught by that.
Thanks, --Jeremy

**Comment by jezwilkinson** [comment]
+test

**Comment by xinyepeng** [comment]
Hi,

Sorry, it’s fixed now. I compiled locally, it seems be fine form my side.

Best,
Xinye

**Comment by jezwilkinson** [comment]
+1

**Pull request merged**
