### PR TITLE
Move KF functions to AliVertexingHFUtils

### PR DESCRIPTION
**Pull request by zhujh126**
Move KF functions to AliVertexingHFUtils and add class AliAnalysisTaskSEXicZero2XiPifromKFP and AddTaskLc2pKs0FromKFParticle.C

### CODE REVIEW

**Comment by fgrosa** [comment]
+test

**Comment by zhujh126** [comment]
The configuration of KF should be added in CMakeLists For HFCJ, HFe and JE.
The following classes include "AliVertexingHFUtils" or use function of "AliVertexingHFUtils":
PWGHF/correlationHF/AliHFCorrelator.h
PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.cxx

Since we add KF function in "AliVertexingHFUtils", if one wants to use "AliVertexingHFUtils", the corresponding KF configuration should be added in CMakeLists. Otherwise, when compiling, it will crash and return error "donot find KF class".

**Comment by jezwilkinson** [comment]
+test

**Comment by mfasDa** [comment]
Hi, 

Making specialized libraries dependent on each other creates the high risk to introduce circular dependencies. In case of EMCALJetTask the dependency is only introduced by 

```
  static TString  GetGenerator(Int_t label, AliAODMCHeader* header);
```

Also other functions are pretty common for many analysis. Have you thought about outsourcing the class or at least part of its functionality to PWG - that is usually the place for common functionality an is designed to have no dependency on any PWG library, the risk of circular dependencies is minimal there.

Cheers

Markus

**Comment by fgrosa** [comment]
Hi Markus, 

I agree that we should limit as much as possible dependencies among specialized libraries. However, unfortunately it is not possible to move `AliVertexingHFUtils` to PWG, because it heavily depends on vertexingHF (since it was originally meant to be a class with utils methods for vertexingHF), but indeed it would be possible to move the `GetGenerator` method in another class in PWG if this is needed also for PWGJE.

Cheers,
Fabrizio

**Comment by mfasDa** [comment]
Hi Fabrizio,

I think jets are not the only user of the utility functions but there are also users, i.e. DQ and HFE are using functionality from the class as well.

I will add the +test for EMCALJetTasks but please let's keep in discussion how we can disentangle the libraries again.

Cheers

Markus

**Comment by mfasDa** [comment]
+test

**Comment by fgrosa** [comment]
Hi Markus, 

yes indeed we should consider to move the methods that are used in other libraries in another util class. A possibility would be to move them in [AliAnalysisUtils.h](https://github.com/alisw/AliPhysics/blob/master/OADB/AliAnalysisUtils.h), if they do not require particular dependencies. Then we could remove the dependency on vertexinHF from the other libraries.
 
Cheers,
Fabrizio

**Comment by fcolamar** [comment]
+test

**Comment by jezwilkinson** [comment]
+1

**Comment by jezwilkinson** [comment]
@mfasDa @fgrosa @fcolamar It seems that the tests went OK, are we happy to go ahead with the merge? (actually it seems somehow the build system only wants to have the +1 from HFCJ, but just to check with everyone given the discussion from before)
Cheers,
--Jeremy

**Comment by fgrosa** [comment]
Hi @jeremy, for me the PR can be merged! It seems indeed that we need a +1 from @fcolamar. 
I will do the modifications discussed with @mfasDa in a second stage, to remove the dependencies on vertexingHF from the other libraries (as much as possible).

**Comment by fcolamar** [comment]
+1

**Pull request merged**
