### PR TITLE
implement the pt re-weight

### PR DESCRIPTION
**Pull request by XiaozhiBai**

### CODE REVIEW

**Comment by XiaozhiBai** [comment]
Xiaozhi implements the pt re-weight for the MC, I would like to commit the code and people can use it.

**Comment by ktf** [comment]
Is this still worked on?

**Comment by miweberSMI** [comment]
Hi @ktf,

I think @XiaozhiBai wanted that @iarsene checks this PR, so maybe lets wait for feedback from him.

Thanks and cheers,
Michael

**Comment by iarsene** [comment]
+test

**Comment by iarsene** [comment]
Hi,
Unfortunately this took too long and now this PR is in conflict due to other changes commited in the mean time. It might be easier to just drop this and make a new PR. The changes are rather isolated so it should be easy to merge.
Ionut

**Comment by XiaozhiBai** [comment]
Hi Ionut, 
Thanks for the review, I will make a new PR, you can reject the previous one.
Cheers
Xiaozhi

**Pull request closed without merging**
