### PR TITLE
PWGUD/Diffractive/Resonance folder removed

### PR DESCRIPTION
**Pull request by kimbyumkyu**
Dear all, 
I removed unused histograms and optimised the embedding method (PYTHIA jet to Heavy ion data). Many thanks for your approvals in advance.

Regards,
Beomkyu

### CODE REVIEW

**Comment by akubera** [comment]
+1

**Comment by kimbyumkyu** [comment]
Hi UD folder people, 
can I request you a +1. It is strange that in previous time I had a right in the UD section, but it looks that I lost it.

**Comment by pbuehler** [comment]
+1

**Comment by mbroz84** [comment]
+1

**Pull request merged**
