### PR TITLE
Final Update for BR, Norm, MCPtShape

### PR DESCRIPTION
**Pull request by cterrevo**
update with the current version of HFSystErr and Final Update for BR, Norm, MCPtShape

### CODE REVIEW

**Comment by zconesa** [comment]
Ciao Cristina,
Your commit seems incompatible with the previous one, could you please check? The diff shows many differences on spaces, and also removal of some Lc systematic function.
Cheers, Zaida

**Comment by cterrevo** [comment]
Ciao Zaida, 

the previous commit was approved only today,  but is was a request of 2 days ago, 
so in the meantime a lot of commits were done in AliHFSystErr, including Lc code by Jaime. 
This new file should restore all the commits done since 2 days ago, plus other changes for D0
I checked the file.. I see that there are a lot of spaces, too, and indeed I don’t know why
cheers, 
Cristina

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+1

Hi Cristina,
Ok, I trust you did checks.
Cheers, Zaida

**Comment by cterrevo** [comment]
Ciao Zaida, 
thanks!
cheers, 
Cristina

**Comment by fprino** [comment]
Hi Cristina,

I cannot approve this commit: it removes the method I added for the pp 2016, as you can see from the diff file.
Can you please close this pull request, update your local version of AliHFSystErr and then commit the changes you need to commit?

Thanks!

Ciao, Francesco

**Comment by cterrevo** [comment]
Ciao Francesco, 

yes, I see! 
sorry, 
cheers, 

Cristina

**Pull request closed without merging**
