### PR TITLE
finer granularity, added A.Kalweit nuclei cuts

### PR DESCRIPTION
**Pull request by bschaefe**
High purity deuterons are sought for flow analysis.  Track and event selection cuts are made following N.Sharma and A.Kalweit's analysis note "Nucleus and anti-nucleus production..."  Principals are TOF t-t_pi and TPC dEdx.

### CODE REVIEW

**Comment by majanik** [comment]
+1

**Comment by aohlson** [comment]
+test

**Comment by bschaefe** [comment]
had to remove namespace used in local running

**Comment by ktf** [comment]
+test

**Comment by aohlson** [comment]
+1

**Pull request merged**
