### PR TITLE
Adds an energy swap map for determining same-position PS distribution

### PR DESCRIPTION
**Pull request by moliver813**
Adds an energy swap map for determining same-position PS distribution
Also cleans up a few couts.

### CODE REVIEW

**Comment by moliver813** [comment]
Found a potential error I need to fix first; I think the SetE option isn't what I want, as it only changes the E entry of the TLorentzVector

**Comment by moliver813** [comment]
Should be correct now

**Comment by e-masson** [comment]
+test

**Comment by e-masson** [comment]
+1

**Pull request merged**
