### PR TITLE
Revert change to make sure dailies can compile.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@mpuccio we seem to have a problem with the version of treelite used by the daily builds. Was it updated as well?

**Comment by ktf** [comment]
+1

**Comment by mpuccio** [comment]
I thought it was, but does it mean that the pr checker runs different defaults wrt the release?

**Comment by mpuccio** [comment]
Indeed there is a mismatch between PR checker and release...

**Pull request closed without merging**
