### PR TITLE
first version of v1 task for single muon analysis

### PR DESCRIPTION
**Pull request by AudreyFrancisco**
Added AliAnalysisTaskV1SingleMu task performing the analysis for single muon directed flow
The task requires packages from PWG/muon and PWG/FLOW

### CODE REVIEW

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
Hi Audrey,
I launched the test, but I have just seen that you put the new class in a new subdirectory, but for the linkdef and makefile used the hfe one. I am not sure we want to add such dependencies between the electron / muon analyses (they don't need muon-specific classes). Can't we create a new library for the new directory?

**Comment by AudreyFrancisco** [comment]
Hi @zconesa 
my mistake I put it in the wrong directory. But you are right, it is cleaner to move it under PWGHF.

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+test

**Comment by zconesa** [comment]
+1

**Pull request merged**
