### PR TITLE
Pair cut

### PR DESCRIPTION
**Pull request by KonstantinMikhaylov**
Pair cut is for both standard and special (kaon) cases

### CODE REVIEW

**Comment by KonstantinMikhaylov** [comment]
+1

**Comment by dberzano** [comment]
@KonstantinMikhaylov you cannot approve if you are not mentioned, sorry.

**Comment by dberzano** [comment]
+test

**Comment by KonstantinMikhaylov** [comment]
+1 This Pair cut should be included to the AliPhysics

**Comment by dberzano** [comment]
@KonstantinMikhaylov as said already once, **you cannot approve if you are not mentioned!**

**Comment by rbertens** [comment]
Hello, I see this conversation because I'm mentioned (I don't to comment +1 as this is not my PAG).
In the CERN git history I see that @KonstantinMikhaylov actually has(had) write access to this folder. Shouldn't this pull request then go through, if tests are passed and accounts are properly mapped (correct me if I'm wrong please). 
Thanks,
Redmer

**Comment by KonstantinMikhaylov** [comment]
Hi, I did "push" a lot of times before migration. Now I do not understand what to do. Ask somebody to get new rights? 
Thanks,
Konstantin

**Comment by dberzano** [comment]
@KonstantinMikhaylov you should ask the PWGCF conveners to be added to the egroup `alice-svn-pwgcf`. We ported the permissions from our previous system as they were, but in many cases persons _lost_ permissions as they _accidentally_ had broader permissions before, instead of the proper ones.

**Comment by dberzano** [comment]
Hi @KonstantinMikhaylov, it looks you are in the egroup. Have you mapped your GitHub account to your CERN account? It looks you didn't, therefore our system does not know you. Can you do that by reading the first paragraph [here](http://alisw.github.io/git-tutorial/)? Thanks!

**Comment by KonstantinMikhaylov** [comment]
Hi Dario, I did it yesterday. One thing could be a problem. My username in GIT is KonstantinMikhaylov, but at cern I'm mikhaylo. Anyway I will check everything at https://alisw.cern.ch/alice-github/login again. Now I cannot reach this site for some reasons. Thanks, Konstantin

**Comment by dberzano** [comment]
Hi, the system is up and running, and accessible (I have just verified) - yesterday it was accessible too, and some people mapped their accounts. The difference in usernames is not a problem. Let me know if you manage! :-)

**Comment by KonstantinMikhaylov** [comment]
Hi, it seems I mapped: https://alisw.cern.ch/alice-github/whoami : Hello Konstantin Mikhaylov.
You are mikhaylo at CERN and KonstantinMikhaylov on GitHub.
Proceed to the tutorial.

**Comment by dberzano** [comment]
+1 @KonstantinMikhaylov I confirm you are now mapped, and starting from the next PR you'll be able to commit directly without approval. This time I am doing that. Thanks for your patience!

**Comment by KonstantinMikhaylov** [comment]
Hi Dario, Thanks a lot! Konstantin

**Pull request merged**
