### PR TITLE
AliAnalysisTaskEmcalJetCDF : fix histo finding, add to namespace load…

### PR DESCRIPTION
**Pull request by adriansev**
…_config and AddJetContainerJetTask utility functions

### CODE REVIEW

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
@dberzano @ktf Hi! I have a strange compilation error in OTHER place than the commit. Any idea what is going on? Thanks a lot!

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
@dberzano @ktf ping?

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
+test

**Comment by raymondEhlers** [comment]
Naive guess, but by including AliEmcalJetTask, your task explicitly depends on the fastjet headers. So I think you need to indicate that in the CMakeLists (and maybe LinkDef?)

**Comment by adriansev** [comment]
> Naive guess, but by including AliEmcalJetTask, your task explicitly depends on the fastjet headers. So I think you need to indicate that in the CMakeLists (and maybe LinkDef?)

@raymondEhlers well, the error is in AliEmcalJetTask.h:232 not in my code .. but, how one can indicate such dependency? maybe it should be done for AliEmcalJetTask instead?

**Comment by adriansev** [comment]
+test

**Comment by raymondEhlers** [comment]
@adriansev But I think the error is caused by the changes in your code (namely, including the headers without changing the CMakeLists). Since you now explicitly include the fastjet headers (through AliEmcalJetTask) I think you need to move you task into this section of the CMakeLists: https://github.com/alisw/AliPhysics/blob/016fe3472165b5dc96845538a96c1875ec32a45e/PWGJE/EMCALJetTasks/CMakeLists.txt#L248 .

**Comment by adriansev** [comment]
+test

**Comment by adriansev** [comment]
this branch is a mess ... i will clean up an try again

**Pull request closed without merging**
