### PR TITLE
Add classes which used KFParticle

### PR DESCRIPTION
**Pull request by zhujh126**
Add classes AliRDHFCutsKFP.cxx and AliAnalysisTaskSEXicZero2XiPifromKFP.cxx into vertexingHF/CMakeLists.txt and vertexingHF/PWGHFvertexingHFLinkDef.h

### CODE REVIEW

**Comment by jezwilkinson** [comment]
+test

**Comment by jezwilkinson** [comment]
+test

**Comment by jezwilkinson** [comment]
+test

**Comment by jezwilkinson** [comment]
+test

**Comment by cterrevo** [comment]
+test

**Comment by cterrevo** [comment]
+1

**Comment by cterrevo** [comment]
+1

**Pull request merged**
