### PR TITLE
Update AliAnalysisTaskNetLambdaTrad.h

### PR DESCRIPTION
**Pull request by eumaka**

### CODE REVIEW

**Comment by rbertens** [comment]
Hi @eumaka , do you want to add the changes to the .cxx to this same PR?

**Comment by eumaka** [comment]
@rbertens yes. 
it appears to go to separate pull request for each file. Previous command line tools does not grant me access to combine both files into one PR.

**Comment by rbertens** [comment]
Hi @eumaka , 
Can you make a new PR, that contains the changes to the .cxx file? This should then get mered with this PR (which is currently still open), as soon as that happens, I can approve the merged request which contains changes to both files. 

In general, if you want to push changes to multiple files in one PR, you can do

git add <file1>
git add <file2>

etc ... for all files (or you can add them all ad once in various ways, e.g dong 'git add -u' ), then

git commit -m " some useful commit mesage " 

and 
git push eumaka

and then make the PR .

**Comment by eumaka** [comment]
@rbertens thanks. A new PR #5878 was created with the updated .cxx file

**Comment by eumaka** [comment]
@rbertens I have corrected the issue. It was an issue of my fork of aliphysics not being up to date. Please see #5881 for the updated pull request. I will now close this present one.

**Pull request closed without merging**
