### PR TITLE
Antonio's embedding task

### PR DESCRIPTION
**Pull request by btrzecia**
Antonio's task to embedd data events to Monte-Carlo.

### CODE REVIEW

**Comment by fcolamar** [comment]
+test

**Comment by fcolamar** [comment]
+1

**Comment by mfasDa** [comment]
Commit breaks compilation on macOS:

/Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGHF/jetsHF/AliEmbeddingEventForHFTask.cxx:902:22: error: ordered comparison between pointer and zero ('AliAODMCParticle *' and 'int')
        if (mcGranma >= 0) {
            ~~~~~~~~ ^  ~
/Users/markusfasel/alice/sw/SOURCES/AliPhysics/ali-master/0/PWGHF/jetsHF/AliEmbeddingEventForHFTask.cxx:951:22: error: ordered comparison between pointer and zero ('TParticle *' and 'int')
        if (mcGranma >= 0) {
            ~~~~~~~~ ^  ~

**Comment by btrzecia** [comment]
Thanks for reporting this. The fix is committed.

**Comment by fcolamar** [comment]
+test

**Pull request merged**
